function estadoSiguiente = paso_rk4( ...
    funcionDinamica, tiempo, estadoActual, dt, varargin)
%PASO_RK4 Integra un sistema dinámico mediante Runge-Kutta de cuarto orden.
%
% Uso:
%
%   estadoSiguiente = paso_rk4( ...
%       funcionDinamica, ...
%       tiempo, ...
%       estadoActual, ...
%       dt ...
%   );
%
% La función dinámica debe tener esta forma:
%
%   derivada = funcionDinamica(tiempo, estado, argumentos...)
%
% Entradas:
%   funcionDinamica : función que calcula dx/dt
%   tiempo          : tiempo actual [s]
%   estadoActual    : vector de estados
%   dt              : paso de integración [s]
%   varargin        : parámetros adicionales opcionales
%
% Salida:
%   estadoSiguiente : estado integrado después de dt segundos

    %% Validaciones

    if ~isa(funcionDinamica, 'function_handle')

        error( ...
            'paso_rk4:FuncionInvalida', ...
            'funcionDinamica debe ser un function handle.' ...
        );

    end

    if ~isnumeric(estadoActual) || isempty(estadoActual)

        error( ...
            'paso_rk4:EstadoInvalido', ...
            'estadoActual debe ser un vector numérico.' ...
        );

    end

    if ~isscalar(dt) || ~isfinite(dt) || dt <= 0

        error( ...
            'paso_rk4:PasoInvalido', ...
            'dt debe ser un número positivo y finito.' ...
        );

    end

    %% Asegurar vector columna

    estadoActual = estadoActual(:);

    %% Runge-Kutta de cuarto orden

    k1 = funcionDinamica( ...
        tiempo, ...
        estadoActual, ...
        varargin{:} ...
    );

    k2 = funcionDinamica( ...
        tiempo + dt/2, ...
        estadoActual + (dt/2)*k1, ...
        varargin{:} ...
    );

    k3 = funcionDinamica( ...
        tiempo + dt/2, ...
        estadoActual + (dt/2)*k2, ...
        varargin{:} ...
    );

    k4 = funcionDinamica( ...
        tiempo + dt, ...
        estadoActual + dt*k3, ...
        varargin{:} ...
    );

    %% Estado siguiente

    estadoSiguiente = estadoActual + ...
        (dt/6) * (k1 + 2*k2 + 2*k3 + k4);

end