function comando = leer_comando_teclado(figura)
%LEER_COMANDO_TECLADO
% Convierte el estado interno del teclado en comandos utilizables
% por la simulación y por el controlador de vuelo.
%
% CONTROLES CONTINUOS
%
%   comando.mandoAdelante
%       -1 = atrás
%        0 = neutro
%       +1 = adelante
%
%   comando.mandoDerecha
%       -1 = izquierda
%        0 = neutro
%       +1 = derecha
%
%   comando.mandoAltura
%       -1 = reducir referencia de altura
%        0 = mantener referencia
%       +1 = aumentar referencia de altura
%
%   comando.mandoYaw
%       -1 = girar izquierda
%        0 = neutro
%       +1 = girar derecha
%
% COMANDOS DISCRETOS
%
%   comando.solicitudSubirUnMetro
%       Se activa una sola vez después de presionar Shift.
%
%   comando.solicitudBajarUnMetro
%       Se activa una sola vez después de presionar Espacio.
%
% Después de leerlos, las solicitudes discretas se limpian dentro
% del estado del teclado. De esta manera una pulsación produce
% solamente una maniobra.
%
% COMPATIBILIDAD
%
% También se conservan:
%
%   comando.roll
%   comando.pitch
%   comando.yaw
%   comando.throttle
%   comando.subirThrottle
%   comando.bajarThrottle
%
% para no romper simulaciones anteriores.

    %% ============================================================
    % VALIDAR FIGURA
    % =============================================================

    if ~isgraphics(figura, 'figure')

        error( ...
            'leer_comando_teclado:FiguraInvalida', ...
            'La entrada debe ser una figura válida.' ...
        );

    end

    %% ============================================================
    % CREAR ESTADO SI NO EXISTE
    % =============================================================

    if ~isappdata(figura, 'estadoTeclado')

        setappdata( ...
            figura, ...
            'estadoTeclado', ...
            crear_estado_teclado() ...
        );

    end

    estado = getappdata( ...
        figura, ...
        'estadoTeclado' ...
    );

    %% ============================================================
    % COMPATIBILIDAD CON ESTADOS ANTERIORES
    % =============================================================

    estado = asegurar_campo( ...
        estado, ...
        'subirThrottle', ...
        false ...
    );

    estado = asegurar_campo( ...
        estado, ...
        'bajarThrottle', ...
        false ...
    );

    estado = asegurar_campo( ...
        estado, ...
        'throttle', ...
        0.50 ...
    );

    estado = asegurar_campo( ...
        estado, ...
        'rollIzquierda', ...
        false ...
    );

    estado = asegurar_campo( ...
        estado, ...
        'rollDerecha', ...
        false ...
    );

    estado = asegurar_campo( ...
        estado, ...
        'pitchAdelante', ...
        false ...
    );

    estado = asegurar_campo( ...
        estado, ...
        'pitchAtras', ...
        false ...
    );

    estado = asegurar_campo( ...
        estado, ...
        'yawIzquierda', ...
        false ...
    );

    estado = asegurar_campo( ...
        estado, ...
        'yawDerecha', ...
        false ...
    );

    estado = asegurar_campo( ...
        estado, ...
        'armado', ...
        false ...
    );

    estado = asegurar_campo( ...
        estado, ...
        'solicitudSubirUnMetro', ...
        false ...
    );

    estado = asegurar_campo( ...
        estado, ...
        'solicitudBajarUnMetro', ...
        false ...
    );

    estado = asegurar_campo( ...
        estado, ...
        'resetSolicitado', ...
        false ...
    );

    estado = asegurar_campo( ...
        estado, ...
        'salirSolicitado', ...
        false ...
    );

    %% ============================================================
    % COMANDOS CONTINUOS NORMALIZADOS
    % =============================================================

    mandoDerecha = ...
        double(logical(estado.rollDerecha)) - ...
        double(logical(estado.rollIzquierda));

    mandoAdelante = ...
        double(logical(estado.pitchAdelante)) - ...
        double(logical(estado.pitchAtras));

    mandoYaw = ...
        double(logical(estado.yawDerecha)) - ...
        double(logical(estado.yawIzquierda));

    mandoAltura = ...
        double(logical(estado.subirThrottle)) - ...
        double(logical(estado.bajarThrottle));

    %% Interfaz nueva para el controlador traslacional

    comando.mandoAdelante = ...
        saturar(mandoAdelante, -1, 1);

    comando.mandoDerecha = ...
        saturar(mandoDerecha, -1, 1);

    comando.mandoAltura = ...
        saturar(mandoAltura, -1, 1);

    comando.mandoYaw = ...
        saturar(mandoYaw, -1, 1);

    %% ============================================================
    % CAMPOS COMPATIBLES CON LA SIMULACIÓN ANTERIOR
    % =============================================================

    comando.roll = ...
        comando.mandoDerecha;

    comando.pitch = ...
        comando.mandoAdelante;

    comando.yaw = ...
        comando.mandoYaw;

    comando.throttle = saturar( ...
        double(estado.throttle), ...
        0, ...
        1 ...
    );

    comando.subirThrottle = ...
        logical(estado.subirThrottle);

    comando.bajarThrottle = ...
        logical(estado.bajarThrottle);

    %% ============================================================
    % COMANDOS DISCRETOS
    % =============================================================

    % Copiar las solicitudes antes de limpiarlas.

    comando.solicitudSubirUnMetro = ...
        logical(estado.solicitudSubirUnMetro);

    comando.solicitudBajarUnMetro = ...
        logical(estado.solicitudBajarUnMetro);

    comando.reset = ...
        logical(estado.resetSolicitado);

    comando.salir = ...
        logical(estado.salirSolicitado);

    %% ============================================================
    % ESTADO DE ARMADO
    % =============================================================

    comando.armado = ...
        logical(estado.armado);

    comando.origen = ...
        "TECLADO";

    %% ============================================================
    % CONSUMIR SOLICITUDES DE UN SOLO CICLO
    % =============================================================

    % Shift y espacio solo deben producir una orden por pulsación.
    %
    % El bloqueo de cada tecla seguirá activo hasta que físicamente
    % se suelte mediante tecla_liberada.

    estado.solicitudSubirUnMetro = ...
        false;

    estado.solicitudBajarUnMetro = ...
        false;

    % El reinicio también se consume como una orden discreta.

    estado.resetSolicitado = ...
        false;

    %% ============================================================
    % GUARDAR ESTADO ACTUALIZADO
    % =============================================================

    setappdata( ...
        figura, ...
        'estadoTeclado', ...
        estado ...
    );

end


function estructura = asegurar_campo( ...
    estructura, ...
    nombreCampo, ...
    valorPredeterminado ...
)
%ASEGURAR_CAMPO Agrega un campo cuando todavía no existe.

    if ~isfield(estructura, nombreCampo)

        estructura.(nombreCampo) = ...
            valorPredeterminado;

    end

end


function valorSaturado = saturar( ...
    valor, ...
    limiteInferior, ...
    limiteSuperior ...
)
%SATURAR Limita un valor escalar dentro de un intervalo.

    if ~isscalar(valor) || ...
            ~isfinite(valor)

        error( ...
            'leer_comando_teclado:ValorInvalido', ...
            'Los comandos del teclado deben ser escalares finitos.' ...
        );

    end

    valorSaturado = max( ...
        limiteInferior, ...
        min(limiteSuperior, valor) ...
    );

end