function actualizar_visualizacion_dron( ...
    visual, ...
    estado, ...
    comando, ...
    tiempo, ...
    datos ...
)
%ACTUALIZAR_VISUALIZACION_DRON
% Actualización optimizada de la visualización del dron.
%
% La simulación puede controlar independientemente la frecuencia de:
%
%   - Movimiento y orientación del modelo 3D.
%   - Cámara.
%   - Trayectoria.
%   - Piso.
%   - Paneles de texto.
%
% Esto evita reconstruir todos los elementos gráficos en cada paso
% del modelo físico.
%
% CAMPOS OPCIONALES DE DATOS
%
%   datos.actualizarGeometria
%   datos.actualizarCamara
%   datos.actualizarTrayectoria
%   datos.actualizarPiso
%   datos.actualizarTexto
%
% Cuando estos campos no existen, se supone true para mantener
% compatibilidad con llamadas anteriores.
%
% IMPORTANTE:
%
% Esta función no ejecuta DRAWNOW.
% El bucle principal de la simulación será el único responsable de
% procesar los eventos gráficos y del teclado.

    %% ============================================================
    % ARGUMENTOS OPCIONALES
    % =============================================================

    if nargin < 5 || isempty(datos)

        datos = struct();

    end

    if nargin < 4 || isempty(tiempo)

        tiempo = 0;

    end

    if nargin < 3 || isempty(comando)

        comando = struct();

    end

    %% ============================================================
    % VALIDAR VISUALIZACIÓN
    % =============================================================

    if ~isstruct(visual) || ...
            ~isfield(visual, 'figura') || ...
            ~isgraphics(visual.figura, 'figure')

        return;

    end

    if ~isfield(visual, 'transformacion') || ...
            ~isgraphics(visual.transformacion)

        return;

    end

    %% ============================================================
    % VALIDAR ESTADO
    % =============================================================

    estado = estado(:);

    if numel(estado) < 12 || ...
            any(~isfinite(estado(1:12)))

        return;

    end

    %% ============================================================
    % SELECCIONAR QUÉ ELEMENTOS ACTUALIZAR
    % =============================================================

    actualizarGeometria = logical( ...
        obtener_campo( ...
            datos, ...
            'actualizarGeometria', ...
            true ...
        ) ...
    );

    actualizarCamara = logical( ...
        obtener_campo( ...
            datos, ...
            'actualizarCamara', ...
            actualizarGeometria ...
        ) ...
    );

    actualizarTrayectoria = logical( ...
        obtener_campo( ...
            datos, ...
            'actualizarTrayectoria', ...
            true ...
        ) ...
    );

    actualizarPiso = logical( ...
        obtener_campo( ...
            datos, ...
            'actualizarPiso', ...
            false ...
        ) ...
    );

    actualizarTexto = logical( ...
        obtener_campo( ...
            datos, ...
            'actualizarTexto', ...
            true ...
        ) ...
    );

    %% ============================================================
    % EXTRAER ESTADO
    % =============================================================

    xN_m = estado(1);
    yE_m = estado(2);
    zD_m = estado(3);

    phi_rad = estado(7);
    theta_rad = estado(8);
    psi_rad = estado(9);

    alturaActual_m = ...
        -zD_m;

    posicionGrafica = [
        xN_m
        yE_m
        alturaActual_m
    ];

    %% ============================================================
    % ACTUALIZAR MODELO 3D
    % =============================================================

    if actualizarGeometria

        R_B_N = matriz_rotacion_body_ned( ...
            phi_rad, ...
            theta_rad, ...
            psi_rad ...
        );

        % Conversión de NED/FRD a la representación gráfica donde
        % Z positiva apunta hacia arriba.

        cambioEjes = ...
            diag([1, 1, -1]);

        R_grafica = ...
            cambioEjes * ...
            R_B_N * ...
            cambioEjes;

        matrizTransformacion = ...
            eye(4);

        matrizTransformacion(1:3, 1:3) = ...
            R_grafica;

        matrizTransformacion(1:3, 4) = ...
            posicionGrafica;

        set( ...
            visual.transformacion, ...
            'Matrix', ...
            matrizTransformacion ...
        );

    end

    %% ============================================================
    % CÁMARA SEGUIDORA OPTIMIZADA
    % =============================================================

    if actualizarCamara && ...
            isfield(visual, 'ejes') && ...
            isgraphics(visual.ejes, 'axes')

        actualizarCamaraAhora = ...
            true;

        if isappdata(visual.figura, 'ultimaPosicionCamara')

            ultimaPosicionCamara = getappdata( ...
                visual.figura, ...
                'ultimaPosicionCamara' ...
            );

            desplazamientoCamara_m = norm( ...
                posicionGrafica - ...
                ultimaPosicionCamara(:) ...
            );

            % No mover la cámara por desplazamientos inferiores
            % a cinco centímetros.

            actualizarCamaraAhora = ...
                desplazamientoCamara_m >= 0.05;

        end

        if actualizarCamaraAhora

            radioHorizontal_m = ...
                4.5;

            limiteInferiorZ_m = max( ...
                -0.20, ...
                alturaActual_m - 1.50 ...
            );

            limiteSuperiorZ_m = max( ...
                3.0, ...
                alturaActual_m + 3.0 ...
            );

            set( ...
                visual.ejes, ...
                'XLim', ...
                [ ...
                    xN_m - radioHorizontal_m, ...
                    xN_m + radioHorizontal_m ...
                ], ...
                'YLim', ...
                [ ...
                    yE_m - radioHorizontal_m, ...
                    yE_m + radioHorizontal_m ...
                ], ...
                'ZLim', ...
                [ ...
                    limiteInferiorZ_m, ...
                    limiteSuperiorZ_m ...
                ] ...
            );

            camtarget( ...
                visual.ejes, ...
                posicionGrafica.' ...
            );

            setappdata( ...
                visual.figura, ...
                'ultimaPosicionCamara', ...
                posicionGrafica ...
            );

        end

    end

    %% ============================================================
    % PISO DINÁMICO OPTIMIZADO
    % =============================================================

    % El piso solamente se reconstruye cuando el dron se alejó
    % considerablemente del centro anterior.

    if isfield(visual, 'piso') && ...
            isgraphics(visual.piso)

        centroPisoActual = [
            round(xN_m)
            round(yE_m)
        ];

        debeActualizarPiso = ...
            actualizarPiso;

        if ~isappdata(visual.figura, 'ultimoCentroPiso')

            debeActualizarPiso = ...
                true;

        else

            ultimoCentroPiso = getappdata( ...
                visual.figura, ...
                'ultimoCentroPiso' ...
            );

            desplazamientoPiso_m = norm( ...
                centroPisoActual - ...
                ultimoCentroPiso(:) ...
            );

            if desplazamientoPiso_m >= 2.0

                debeActualizarPiso = ...
                    true;

            end

        end

        if debeActualizarPiso

            radioPiso_m = ...
                7;

            separacionCuadricula_m = ...
                1;

            [xPiso, yPiso] = meshgrid( ...
                centroPisoActual(1)-radioPiso_m: ...
                separacionCuadricula_m: ...
                centroPisoActual(1)+radioPiso_m, ...
                centroPisoActual(2)-radioPiso_m: ...
                separacionCuadricula_m: ...
                centroPisoActual(2)+radioPiso_m ...
            );

            set( ...
                visual.piso, ...
                'XData', ...
                xPiso, ...
                'YData', ...
                yPiso, ...
                'ZData', ...
                zeros(size(xPiso)) ...
            );

            setappdata( ...
                visual.figura, ...
                'ultimoCentroPiso', ...
                centroPisoActual ...
            );

        end

    end

    %% ============================================================
    % TRAYECTORIA CON BÚFER LIMITADO
    % =============================================================

    if actualizarTrayectoria && ...
            isfield(visual, 'trayectoria') && ...
            isgraphics(visual.trayectoria)

        if isappdata(visual.figura, 'trayectoriaX')

            trayectoriaX = getappdata( ...
                visual.figura, ...
                'trayectoriaX' ...
            );

            trayectoriaY = getappdata( ...
                visual.figura, ...
                'trayectoriaY' ...
            );

            trayectoriaZ = getappdata( ...
                visual.figura, ...
                'trayectoriaZ' ...
            );

        else

            trayectoriaX = [];
            trayectoriaY = [];
            trayectoriaZ = [];

        end

        agregarPunto = ...
            isempty(trayectoriaX);

        if ~agregarPunto

            ultimaPosicion = [
                trayectoriaX(end)
                trayectoriaY(end)
                trayectoriaZ(end)
            ];

            % No agregar decenas de puntos prácticamente iguales.

            agregarPunto = ...
                norm(posicionGrafica - ultimaPosicion) >= 0.015;

        end

        if agregarPunto

            trayectoriaX(end + 1) = ...
                posicionGrafica(1);

            trayectoriaY(end + 1) = ...
                posicionGrafica(2);

            trayectoriaZ(end + 1) = ...
                posicionGrafica(3);

        end

        % Búfer fijo para evitar que la simulación se vuelva cada
        % vez más pesada conforme transcurre el tiempo.

        maximoPuntosTrayectoria = ...
            700;

        if numel(trayectoriaX) > maximoPuntosTrayectoria

            indiceInicial = ...
                numel(trayectoriaX) - ...
                maximoPuntosTrayectoria + 1;

            trayectoriaX = ...
                trayectoriaX(indiceInicial:end);

            trayectoriaY = ...
                trayectoriaY(indiceInicial:end);

            trayectoriaZ = ...
                trayectoriaZ(indiceInicial:end);

        end

        setappdata( ...
            visual.figura, ...
            'trayectoriaX', ...
            trayectoriaX ...
        );

        setappdata( ...
            visual.figura, ...
            'trayectoriaY', ...
            trayectoriaY ...
        );

        setappdata( ...
            visual.figura, ...
            'trayectoriaZ', ...
            trayectoriaZ ...
        );

        set( ...
            visual.trayectoria, ...
            'XData', ...
            trayectoriaX, ...
            'YData', ...
            trayectoriaY, ...
            'ZData', ...
            trayectoriaZ ...
        );

    end

    %% ============================================================
    % OMITIR TEXTOS EN ACTUALIZACIONES RÁPIDAS
    % =============================================================

    if ~actualizarTexto

        return;

    end

    %% ============================================================
    % COMPLETAR COMANDO
    % =============================================================

    comando.armado = logical( ...
        obtener_campo( ...
            comando, ...
            'armado', ...
            false ...
        ) ...
    );

    comando.origen = string( ...
        obtener_campo( ...
            comando, ...
            'origen', ...
            "DESCONOCIDO" ...
        ) ...
    );

    comando.mandoAdelante = obtener_campo( ...
        comando, ...
        'mandoAdelante', ...
        obtener_campo(comando, 'pitch', 0) ...
    );

    comando.mandoDerecha = obtener_campo( ...
        comando, ...
        'mandoDerecha', ...
        obtener_campo(comando, 'roll', 0) ...
    );

    comando.mandoAltura = obtener_campo( ...
        comando, ...
        'mandoAltura', ...
        0 ...
    );

    comando.mandoYaw = obtener_campo( ...
        comando, ...
        'mandoYaw', ...
        obtener_campo(comando, 'yaw', 0) ...
    );

    %% ============================================================
    % COMPLETAR DATOS GENERALES
    % =============================================================

    datos.alturaObjetivo_m = obtener_campo( ...
        datos, ...
        'alturaObjetivo_m', ...
        alturaActual_m ...
    );

    datos.modoHorizontal = string( ...
        obtener_campo( ...
            datos, ...
            'modoHorizontal', ...
            "SIN CONTROL" ...
        ) ...
    );

    datos.velocidadUp_m_s = obtener_campo( ...
        datos, ...
        'velocidadUp_m_s', ...
        -estado(6) ...
    );

    datos.empujeMotores_N = obtener_campo( ...
        datos, ...
        'empujeMotores_N', ...
        zeros(4, 1) ...
    );

    datos.empujeMotores_N = ...
        datos.empujeMotores_N(:);

    if numel(datos.empujeMotores_N) < 4

        datos.empujeMotores_N(end + 1:4, 1) = ...
            0;

    end

    datos.empujeMotores_N = ...
        datos.empujeMotores_N(1:4);

    datos.empujeTotal_N = obtener_campo( ...
        datos, ...
        'empujeTotal_N', ...
        sum(datos.empujeMotores_N) ...
    );

    datos.empujeHoverTotal_N = obtener_campo( ...
        datos, ...
        'empujeHoverTotal_N', ...
        NaN ...
    );

    datos.saturacionMotores = logical( ...
        obtener_campo( ...
            datos, ...
            'saturacionMotores', ...
            false ...
        ) ...
    );

    %% ============================================================
    % COMPLETAR MANIOBRA
    % =============================================================

    datos.maniobra = obtener_campo( ...
        datos, ...
        'maniobra', ...
        struct() ...
    );

    datos.maniobra.activa = logical( ...
        obtener_campo( ...
            datos.maniobra, ...
            'activa', ...
            false ...
        ) ...
    );

    datos.maniobra.tipo = string( ...
        obtener_campo( ...
            datos.maniobra, ...
            'tipo', ...
            "NINGUNA" ...
        ) ...
    );

    datos.maniobra.tiempoTranscurrido_s = obtener_campo( ...
        datos.maniobra, ...
        'tiempoTranscurrido_s', ...
        0 ...
    );

    datos.maniobra.alturaInicial_m = obtener_campo( ...
        datos.maniobra, ...
        'alturaInicial_m', ...
        alturaActual_m ...
    );

    datos.maniobra.alturaObjetivo_m = obtener_campo( ...
        datos.maniobra, ...
        'alturaObjetivo_m', ...
        datos.alturaObjetivo_m ...
    );

    datos.resultadoAscenso = completar_resultado( ...
        obtener_campo( ...
            datos, ...
            'resultadoAscenso', ...
            struct() ...
        ) ...
    );

    datos.resultadoDescenso = completar_resultado( ...
        obtener_campo( ...
            datos, ...
            'resultadoDescenso', ...
            struct() ...
        ) ...
    );

    %% ============================================================
    % PANEL DE ESTADO
    % =============================================================

    if comando.armado

        textoArmado = ...
            'ARMADO';

    else

        textoArmado = ...
            'DESARMADO / MOTORES APAGADOS';

    end

    velocidadTotal_m_s = ...
        norm(estado(4:6));

    textoEstado = sprintf([ ...
        'ESTADO DEL DRON\n' ...
        '-----------------------------\n' ...
        'Estado:        %s\n' ...
        'Tiempo:        %7.2f s\n' ...
        'Modo horiz.:   %s\n\n' ...
        'ALTURA\n' ...
        '-----------------------------\n' ...
        'Actual:        %7.3f m\n' ...
        'Objetivo:      %7.3f m\n' ...
        'Error:         %+7.3f m\n' ...
        'Vel. vertical: %+7.3f m/s\n\n' ...
        'POSICIÓN\n' ...
        '-----------------------------\n' ...
        'Norte:         %+7.3f m\n' ...
        'Este:          %+7.3f m\n' ...
        'Velocidad:      %7.3f m/s\n\n' ...
        'ORIENTACIÓN\n' ...
        '-----------------------------\n' ...
        'Roll:          %+7.2f grados\n' ...
        'Pitch:         %+7.2f grados\n' ...
        'Yaw:           %+7.2f grados\n\n' ...
        'COMANDOS\n' ...
        '-----------------------------\n' ...
        'Adelante:      %+5.1f\n' ...
        'Derecha:       %+5.1f\n' ...
        'Altura W/S:    %+5.1f\n' ...
        'Yaw:           %+5.1f\n\n' ...
        'Shift: subir 1 metro\n' ...
        'Espacio: bajar 1 metro\n' ...
        'X: apagar | Enter: armar\n' ...
        'R: reiniciar | Esc: salir\n'], ...
        textoArmado, ...
        tiempo, ...
        char(datos.modoHorizontal), ...
        alturaActual_m, ...
        datos.alturaObjetivo_m, ...
        datos.alturaObjetivo_m - alturaActual_m, ...
        datos.velocidadUp_m_s, ...
        xN_m, ...
        yE_m, ...
        velocidadTotal_m_s, ...
        rad2deg(phi_rad), ...
        rad2deg(theta_rad), ...
        rad2deg(psi_rad), ...
        comando.mandoAdelante, ...
        comando.mandoDerecha, ...
        comando.mandoAltura, ...
        comando.mandoYaw ...
    );

    if isfield(visual, 'textoEstado') && ...
            isgraphics(visual.textoEstado)

        set( ...
            visual.textoEstado, ...
            'String', ...
            textoEstado, ...
            'ForegroundColor', ...
            [0, 0, 0] ...
        );

    end

    %% ============================================================
    % PANEL DE MANIOBRA
    % =============================================================

    if datos.maniobra.activa

        textoManiobraActual = sprintf([ ...
            'Maniobra actual: %s\n' ...
            'Altura inicial:  %.3f m\n' ...
            'Altura objetivo: %.3f m\n' ...
            'Tiempo actual:   %.3f s\n' ...
            'Error restante:  %+.3f m\n'], ...
            char(datos.maniobra.tipo), ...
            datos.maniobra.alturaInicial_m, ...
            datos.maniobra.alturaObjetivo_m, ...
            datos.maniobra.tiempoTranscurrido_s, ...
            datos.maniobra.alturaObjetivo_m - ...
            alturaActual_m ...
        );

    else

        textoManiobraActual = sprintf([ ...
            'Maniobra actual: NINGUNA\n' ...
            'Altura automática disponible.\n' ...
        ]);

    end

    textoAscenso = formatear_resultado( ...
        'ÚLTIMO ASCENSO DE 1 METRO', ...
        datos.resultadoAscenso ...
    );

    textoDescenso = formatear_resultado( ...
        'ÚLTIMO DESCENSO DE 1 METRO', ...
        datos.resultadoDescenso ...
    );

    textoPanelManiobra = sprintf([ ...
        'MANIOBRAS AUTOMÁTICAS\n' ...
        '-----------------------------\n' ...
        '%s\n' ...
        '-----------------------------\n' ...
        '%s\n' ...
        '-----------------------------\n' ...
        '%s'], ...
        textoManiobraActual, ...
        textoAscenso, ...
        textoDescenso ...
    );

    if isfield(visual, 'textoManiobra') && ...
            isgraphics(visual.textoManiobra)

        set( ...
            visual.textoManiobra, ...
            'String', ...
            textoPanelManiobra, ...
            'ForegroundColor', ...
            [0, 0, 0] ...
        );

    end

    %% ============================================================
    % PANEL DE MOTORES
    % =============================================================

    empujeMotores_N = ...
        datos.empujeMotores_N;

    empujePromedioMotor_N = ...
        mean(empujeMotores_N);

    if datos.saturacionMotores

        textoSaturacion = ...
            'SÍ';

    else

        textoSaturacion = ...
            'NO';

    end

    if isfinite(datos.empujeHoverTotal_N)

        lineaHover = sprintf( ...
            'Diferencia hover: %+7.4f N\n', ...
            datos.empujeTotal_N - ...
            datos.empujeHoverTotal_N ...
        );

    else

        lineaHover = ...
            '';

    end

    textoMotores = sprintf([ ...
        'FUERZA ACTUAL DE MOTORES\n' ...
        '-----------------------------\n' ...
        'Motor 1:     %7.4f N\n' ...
        'Motor 2:     %7.4f N\n' ...
        'Motor 3:     %7.4f N\n' ...
        'Motor 4:     %7.4f N\n' ...
        'Promedio:    %7.4f N\n' ...
        'Total:       %7.4f N\n' ...
        '%s' ...
        'Saturación:  %s\n'], ...
        empujeMotores_N(1), ...
        empujeMotores_N(2), ...
        empujeMotores_N(3), ...
        empujeMotores_N(4), ...
        empujePromedioMotor_N, ...
        datos.empujeTotal_N, ...
        lineaHover, ...
        textoSaturacion ...
    );

    if isfield(visual, 'textoMotores') && ...
            isgraphics(visual.textoMotores)

        set( ...
            visual.textoMotores, ...
            'String', ...
            textoMotores, ...
            'ForegroundColor', ...
            [0, 0, 0] ...
        );

    end

end


function resultado = completar_resultado(resultado)
%COMPLETAR_RESULTADO Agrega campos predeterminados.

    if isempty(resultado) || ...
            ~isstruct(resultado)

        resultado = struct();

    end

    resultado.completado = logical( ...
        obtener_campo(resultado, 'completado', false) ...
    );

    resultado.tiempo_s = obtener_campo( ...
        resultado, ...
        'tiempo_s', ...
        NaN ...
    );

    resultado.alturaInicial_m = obtener_campo( ...
        resultado, ...
        'alturaInicial_m', ...
        NaN ...
    );

    resultado.alturaFinal_m = obtener_campo( ...
        resultado, ...
        'alturaFinal_m', ...
        NaN ...
    );

    resultado.empujeTotalPromedio_N = obtener_campo( ...
        resultado, ...
        'empujeTotalPromedio_N', ...
        NaN ...
    );

    resultado.empujePromedioMotor_N = obtener_campo( ...
        resultado, ...
        'empujePromedioMotor_N', ...
        NaN ...
    );

    resultado.empujeTotalMaximo_N = obtener_campo( ...
        resultado, ...
        'empujeTotalMaximo_N', ...
        NaN ...
    );

    resultado.empujeTotalMinimo_N = obtener_campo( ...
        resultado, ...
        'empujeTotalMinimo_N', ...
        NaN ...
    );

end


function texto = formatear_resultado(titulo, resultado)
%FORMATEAR_RESULTADO Genera el resumen de una maniobra.

    if ~resultado.completado

        texto = sprintf([ ...
            '%s\n' ...
            'Sin medición disponible.\n'], ...
            titulo ...
        );

        return;

    end

    texto = sprintf([ ...
        '%s\n' ...
        'Tiempo:              %7.3f s\n' ...
        'Altura inicial:      %7.3f m\n' ...
        'Altura final:        %7.3f m\n' ...
        'Cambio real:         %+7.3f m\n' ...
        'Empuje prom. total:  %7.4f N\n' ...
        'Empuje prom. motor:  %7.4f N\n' ...
        'Empuje máx. total:   %7.4f N\n' ...
        'Empuje mín. total:   %7.4f N\n'], ...
        titulo, ...
        resultado.tiempo_s, ...
        resultado.alturaInicial_m, ...
        resultado.alturaFinal_m, ...
        resultado.alturaFinal_m - resultado.alturaInicial_m, ...
        resultado.empujeTotalPromedio_N, ...
        resultado.empujePromedioMotor_N, ...
        resultado.empujeTotalMaximo_N, ...
        resultado.empujeTotalMinimo_N ...
    );

end


function valor = obtener_campo( ...
    estructura, ...
    nombreCampo, ...
    valorPredeterminado ...
)
%OBTENER_CAMPO Obtiene un campo o devuelve el valor predeterminado.

    if isstruct(estructura) && ...
            isfield(estructura, nombreCampo)

        valor = ...
            estructura.(nombreCampo);

    else

        valor = ...
            valorPredeterminado;

    end

end


function R_B_N = matriz_rotacion_body_ned(phi, theta, psi)
%MATRIZ_ROTACION_BODY_NED Rotación del cuerpo FRD hacia NED.

    cPhi = cos(phi);
    sPhi = sin(phi);

    cTheta = cos(theta);
    sTheta = sin(theta);

    cPsi = cos(psi);
    sPsi = sin(psi);

    R_B_N = [ ...
        cTheta*cPsi, ...
        sPhi*sTheta*cPsi - cPhi*sPsi, ...
        cPhi*sTheta*cPsi + sPhi*sPsi;

        cTheta*sPsi, ...
        sPhi*sTheta*sPsi + cPhi*cPsi, ...
        cPhi*sTheta*sPsi - sPhi*cPsi;

        -sTheta, ...
        sPhi*cTheta, ...
        cPhi*cTheta ...
    ];

end