function actualizar_visualizacion_dron(visual, estado, comando, tiempo)
%ACTUALIZAR_VISUALIZACION_DRON Actualiza posición y orientación.
%
% Estado esperado:
%
%   estado(1)  = xN
%   estado(2)  = yE
%   estado(3)  = zD
%   estado(4)  = u
%   estado(5)  = v
%   estado(6)  = w
%   estado(7)  = phi
%   estado(8)  = theta
%   estado(9)  = psi
%   estado(10) = p
%   estado(11) = q
%   estado(12) = r

    if numel(estado) < 12

        error( ...
            'actualizar_visualizacion_dron:EstadoInvalido', ...
            'El vector de estado debe contener 12 elementos.' ...
        );

    end

    %% Estados de posición

    xN = estado(1);
    yE = estado(2);
    zD = estado(3);

    %% Ángulos de Euler

    phi = estado(7);
    theta = estado(8);
    psi = estado(9);

    %% Matriz Body-FRD hacia NED

    R_B_N = matriz_rotacion_body_ned(phi, theta, psi);

    % MATLAB muestra Z positivo hacia arriba.
    % Nuestro modelo usa Z positivo hacia abajo.
    cambioEjes = diag([1, 1, -1]);

    % Convierte la orientación del modelo a la visualización.
    R_grafica = cambioEjes * R_B_N * cambioEjes;

    %% Posición gráfica

    posicionGrafica = [ ...
        xN;
        yE;
        -zD ...
    ];

    %% Matriz homogénea

    matrizTransformacion = eye(4);

    matrizTransformacion(1:3, 1:3) = R_grafica;
    matrizTransformacion(1:3, 4) = posicionGrafica;

    set( ...
        visual.transformacion, ...
        'Matrix', matrizTransformacion ...
    );
%% Cámara seguidora

% Posición actual del dron en coordenadas gráficas.
centroX = posicionGrafica(1);
centroY = posicionGrafica(2);
alturaGrafica = posicionGrafica(3);

% Tamaño visible alrededor del dron.
radioVistaHorizontal = 5.0;
radioVistaVertical = 3.0;

% Mover los límites de la ventana junto con el dron.
xlim( ...
    visual.ejes, ...
    [ ...
        centroX - radioVistaHorizontal, ...
        centroX + radioVistaHorizontal ...
    ] ...
);

ylim( ...
    visual.ejes, ...
    [ ...
        centroY - radioVistaHorizontal, ...
        centroY + radioVistaHorizontal ...
    ] ...
);

zlim( ...
    visual.ejes, ...
    [ ...
        alturaGrafica - radioVistaVertical, ...
        alturaGrafica + radioVistaVertical ...
    ] ...
);

% Hacer que la cámara siempre apunte al dron.
camtarget( ...
    visual.ejes, ...
    [centroX, centroY, alturaGrafica] ...
);

%% Piso dinámico

% Redondeamos para evitar que la cuadrícula tiemble
% con cada pequeño movimiento del dron.
centroPisoX = round(centroX);
centroPisoY = round(centroY);

radioPiso = 7;
separacionCuadricula = 1;

[xPiso, yPiso] = meshgrid( ...
    centroPisoX-radioPiso:separacionCuadricula:centroPisoX+radioPiso, ...
    centroPisoY-radioPiso:separacionCuadricula:centroPisoY+radioPiso ...
);

zPiso = zeros(size(xPiso));

set( ...
    visual.piso, ...
    'XData', xPiso, ...
    'YData', yPiso, ...
    'ZData', zPiso ...
);
    %% Actualizar trayectoria

    trayectoriaX = get(visual.trayectoria, 'XData');
    trayectoriaY = get(visual.trayectoria, 'YData');
    trayectoriaZ = get(visual.trayectoria, 'ZData');

    if isempty(trayectoriaX) || all(isnan(trayectoriaX))

        trayectoriaX = posicionGrafica(1);
        trayectoriaY = posicionGrafica(2);
        trayectoriaZ = posicionGrafica(3);

    else

        trayectoriaX(end + 1) = posicionGrafica(1);
        trayectoriaY(end + 1) = posicionGrafica(2);
        trayectoriaZ(end + 1) = posicionGrafica(3);

    end

    % Evita guardar demasiados puntos gráficos.
    maximoPuntos = 1200;

    if numel(trayectoriaX) > maximoPuntos

        trayectoriaX = trayectoriaX(end-maximoPuntos+1:end);
        trayectoriaY = trayectoriaY(end-maximoPuntos+1:end);
        trayectoriaZ = trayectoriaZ(end-maximoPuntos+1:end);

    end

    set( ...
        visual.trayectoria, ...
        'XData', trayectoriaX, ...
        'YData', trayectoriaY, ...
        'ZData', trayectoriaZ ...
    );

    %% Texto del dashboard

    if comando.armado
        textoArmado = 'ARMADO';
    else
        textoArmado = 'DESARMADO';
    end

    altura = -zD;

    textoDashboard = sprintf([ ...
        'GEMELO VIRTUAL\n\n' ...
        'Estado: %s\n' ...
        'Origen: %s\n' ...
        'Tiempo: %7.2f s\n\n' ...
        'COMANDOS\n' ...
        '--------------------\n' ...
        'Throttle: %7.2f\n' ...
        'Roll:     %7.2f\n' ...
        'Pitch:    %7.2f\n' ...
        'Yaw:      %7.2f\n\n' ...
        'POSICION\n' ...
        '--------------------\n' ...
        'xN:       %7.2f m\n' ...
        'yE:       %7.2f m\n' ...
        'Altura:   %7.2f m\n\n' ...
        'ORIENTACION\n' ...
        '--------------------\n' ...
        'Roll:     %7.2f grados\n' ...
        'Pitch:    %7.2f grados\n' ...
        'Yaw:      %7.2f grados\n\n' ...
        'CONTROLES\n' ...
        '--------------------\n' ...
        'Espacio: armar\n' ...
        'W / S: altura\n' ...
        'Flechas: movimiento\n' ...
        'A / D: yaw\n' ...
        'R: reiniciar\n' ...
        'Esc: salir\n'], ...
        textoArmado, ...
        char(comando.origen), ...
        tiempo, ...
        comando.throttle, ...
        comando.roll, ...
        comando.pitch, ...
        comando.yaw, ...
        xN, ...
        yE, ...
        altura, ...
        rad2deg(phi), ...
        rad2deg(theta), ...
        rad2deg(psi) ...
    );

    set(visual.texto, 'String', textoDashboard);

end


function R_B_N = matriz_rotacion_body_ned(phi, theta, psi)
%MATRIZ_ROTACION_BODY_NED Convierte vectores de Body-FRD hacia NED.

    cPhi = cos(phi);
    sPhi = sin(phi);

    cTheta = cos(theta);
    sTheta = sin(theta);

    cPsi = cos(psi);
    sPsi = sin(psi);

    R_B_N = [ ...
        cTheta*cPsi, ...
        sPhi*sTheta*cPsi - cPhi*sPsi, ...
        cPhi*sTheta*cPsi + sPhi*sPsi;

        cTheta*sPsi, ...
        sPhi*sTheta*sPsi + cPhi*cPsi, ...
        cPhi*sTheta*sPsi - sPhi*cPsi;

        -sTheta, ...
        sPhi*cTheta, ...
        cPhi*cTheta ...
    ];

end