function actualizar_visualizacion_dron( ...
    visual, ...
    estado, ...
    comando, ...
    tiempo, ...
    datos ...
)
%ACTUALIZAR_VISUALIZACION_DRON
% Actualiza el CAD real, la cámara seguidora, la cuadrícula móvil,
% la trayectoria y los paneles de información.
%
% La cámara y el mapa siguen automáticamente al dron para evitar
% que salga del encuadre durante movimientos rápidos.
%
% Esta función no ejecuta DRAWNOW. El procesamiento de eventos queda
% a cargo de simulacion_interactiva_fisica.m.

    %% ============================================================
    % ARGUMENTOS OPCIONALES
    % =============================================================

    if nargin < 5 || isempty(datos)

        datos = struct();

    end

    if nargin < 4 || isempty(tiempo)

        tiempo = 0;

    end

    if nargin < 3 || isempty(comando)

        comando = struct();

    end

    %% ============================================================
    % VALIDAR OBJETOS GRÁFICOS
    % =============================================================

    if ~isstruct(visual) || ...
            ~isfield(visual, 'figura') || ...
            ~isgraphics(visual.figura, 'figure')

        return;

    end

    if ~isfield(visual, 'ejes') || ...
            ~isgraphics(visual.ejes, 'axes')

        return;

    end

    if ~isfield(visual, 'transformacion') || ...
            ~isgraphics(visual.transformacion)

        return;

    end

    %% ============================================================
    % VALIDAR ESTADO
    % =============================================================

    estado = ...
        estado(:);

    if numel(estado) < 12 || ...
            any(~isfinite(estado(1:12)))

        return;

    end

    %% ============================================================
    % BANDERAS DE ACTUALIZACIÓN
    % =============================================================

    actualizarGeometria = logical( ...
        obtener_campo( ...
            datos, ...
            'actualizarGeometria', ...
            true ...
        ) ...
    );

    actualizarCamara = logical( ...
        obtener_campo( ...
            datos, ...
            'actualizarCamara', ...
            actualizarGeometria ...
        ) ...
    );

    actualizarTrayectoria = logical( ...
        obtener_campo( ...
            datos, ...
            'actualizarTrayectoria', ...
            true ...
        ) ...
    );

    actualizarPiso = logical( ...
        obtener_campo( ...
            datos, ...
            'actualizarPiso', ...
            false ...
        ) ...
    );

    actualizarTexto = logical( ...
        obtener_campo( ...
            datos, ...
            'actualizarTexto', ...
            true ...
        ) ...
    );

    % Aunque la simulación solicite la cámara a menor frecuencia,
    % la hacemos seguir al dron cada vez que se mueve la geometría.

    actualizarCamara = ...
        actualizarCamara || ...
        actualizarGeometria;

    %% ============================================================
    % EXTRAER ESTADO DEL DRON
    % =============================================================

    xN_m = ...
        estado(1);

    yE_m = ...
        estado(2);

    zD_m = ...
        estado(3);

    phi_rad = ...
        estado(7);

    theta_rad = ...
        estado(8);

    psi_rad = ...
        estado(9);

    alturaActual_m = ...
        -zD_m;

    posicionGrafica = [
        xN_m
        yE_m
        alturaActual_m
    ];

    %% ============================================================
    % ACTUALIZAR POSICIÓN Y ORIENTACIÓN DEL CAD
    % =============================================================

    if actualizarGeometria

        R_B_N = matriz_rotacion_body_ned( ...
            phi_rad, ...
            theta_rad, ...
            psi_rad ...
        );

        % Conversión de NED a coordenadas gráficas con Z positiva
        % hacia arriba.

        cambioEjes = ...
            diag([1, 1, -1]);

        R_grafica = ...
            cambioEjes * ...
            R_B_N * ...
            cambioEjes;

        matrizTransformacion = ...
            eye(4);

        matrizTransformacion(1:3, 1:3) = ...
            R_grafica;

        matrizTransformacion(1:3, 4) = ...
            posicionGrafica;

        set( ...
            visual.transformacion, ...
            'Matrix', ...
            matrizTransformacion ...
        );

    end

    %% ============================================================
    % CÁMARA SEGUIDORA
    % =============================================================

    if actualizarCamara

        % La ventana visible mide aproximadamente 1.3 x 1.3 metros.

        radioHorizontal_m = ...
            0.65;

        % Mostrar ligeramente más espacio frente al dron.

        adelantoCamara_m = ...
            0.18;

        centroCamaraX_m = ...
            xN_m + ...
            adelantoCamara_m * cos(psi_rad);

        centroCamaraY_m = ...
            yE_m + ...
            adelantoCamara_m * sin(psi_rad);

        limiteInferiorZ_m = max( ...
            0, ...
            alturaActual_m - 0.45 ...
        );

        limiteSuperiorZ_m = max( ...
            1.0, ...
            alturaActual_m + 0.85 ...
        );

        set( ...
            visual.ejes, ...
            'XLim', ...
            [ ...
                centroCamaraX_m - radioHorizontal_m, ...
                centroCamaraX_m + radioHorizontal_m ...
            ], ...
            'YLim', ...
            [ ...
                centroCamaraY_m - radioHorizontal_m, ...
                centroCamaraY_m + radioHorizontal_m ...
            ], ...
            'ZLim', ...
            [ ...
                limiteInferiorZ_m, ...
                limiteSuperiorZ_m ...
            ] ...
        );

        camtarget( ...
            visual.ejes, ...
            [ ...
                xN_m, ...
                yE_m, ...
                alturaActual_m ...
            ] ...
        );

        setappdata( ...
            visual.figura, ...
            'ultimaPosicionCamara', ...
            posicionGrafica ...
        );

    end

    %% ============================================================
    % CUADRÍCULA MÓVIL
    % =============================================================

    if isfield(visual, 'piso') && ...
            isgraphics(visual.piso)

        separacionCuadricula_m = ...
            0.10;

        radioPiso_m = ...
            1.50;

        pasoMovimientoPiso_m = ...
            0.20;

        centroPisoActual = [
            round(xN_m / pasoMovimientoPiso_m) * ...
                pasoMovimientoPiso_m

            round(yE_m / pasoMovimientoPiso_m) * ...
                pasoMovimientoPiso_m
        ];

        debeActualizarPiso = ...
            actualizarPiso;

        if ~isappdata(visual.figura, 'ultimoCentroPiso')

            debeActualizarPiso = ...
                true;

        else

            ultimoCentroPiso = getappdata( ...
                visual.figura, ...
                'ultimoCentroPiso' ...
            );

            ultimoCentroPiso = ...
                ultimoCentroPiso(:);

            if numel(ultimoCentroPiso) < 2 || ...
                    any(~isfinite(ultimoCentroPiso(1:2)))

                debeActualizarPiso = ...
                    true;

            else

                desplazamientoPiso_m = norm( ...
                    centroPisoActual - ...
                    ultimoCentroPiso(1:2) ...
                );

                debeActualizarPiso = ...
                    debeActualizarPiso || ...
                    desplazamientoPiso_m >= ...
                    pasoMovimientoPiso_m;

            end

        end

        if debeActualizarPiso

            vectorX = ...
                centroPisoActual(1) - radioPiso_m: ...
                separacionCuadricula_m: ...
                centroPisoActual(1) + radioPiso_m;

            vectorY = ...
                centroPisoActual(2) - radioPiso_m: ...
                separacionCuadricula_m: ...
                centroPisoActual(2) + radioPiso_m;

            [xPiso, yPiso] = meshgrid( ...
                vectorX, ...
                vectorY ...
            );

            zPiso = ...
                zeros(size(xPiso));

            set( ...
                visual.piso, ...
                'XData', ...
                xPiso, ...
                'YData', ...
                yPiso, ...
                'ZData', ...
                zPiso ...
            );

            setappdata( ...
                visual.figura, ...
                'ultimoCentroPiso', ...
                centroPisoActual ...
            );

        end

    end

    %% ============================================================
    % TRAYECTORIA LIMITADA
    % =============================================================

    if actualizarTrayectoria && ...
            isfield(visual, 'trayectoria') && ...
            isgraphics(visual.trayectoria)

        if isappdata(visual.figura, 'trayectoriaX')

            trayectoriaX = getappdata( ...
                visual.figura, ...
                'trayectoriaX' ...
            );

            trayectoriaY = getappdata( ...
                visual.figura, ...
                'trayectoriaY' ...
            );

            trayectoriaZ = getappdata( ...
                visual.figura, ...
                'trayectoriaZ' ...
            );

        else

            trayectoriaX = [];
            trayectoriaY = [];
            trayectoriaZ = [];

        end

        agregarPunto = ...
            isempty(trayectoriaX);

        if ~agregarPunto

            ultimaPosicion = [
                trayectoriaX(end)
                trayectoriaY(end)
                trayectoriaZ(end)
            ];

            agregarPunto = norm( ...
                posicionGrafica - ...
                ultimaPosicion ...
            ) >= 0.015;

        end

        if agregarPunto

            trayectoriaX(end + 1) = ...
                xN_m;

            trayectoriaY(end + 1) = ...
                yE_m;

            trayectoriaZ(end + 1) = ...
                alturaActual_m;

        end

        maximoPuntosTrayectoria = ...
            600;

        if numel(trayectoriaX) > ...
                maximoPuntosTrayectoria

            indiceInicial = ...
                numel(trayectoriaX) - ...
                maximoPuntosTrayectoria + 1;

            trayectoriaX = ...
                trayectoriaX(indiceInicial:end);

            trayectoriaY = ...
                trayectoriaY(indiceInicial:end);

            trayectoriaZ = ...
                trayectoriaZ(indiceInicial:end);

        end

        setappdata( ...
            visual.figura, ...
            'trayectoriaX', ...
            trayectoriaX ...
        );

        setappdata( ...
            visual.figura, ...
            'trayectoriaY', ...
            trayectoriaY ...
        );

        setappdata( ...
            visual.figura, ...
            'trayectoriaZ', ...
            trayectoriaZ ...
        );

        set( ...
            visual.trayectoria, ...
            'XData', ...
            trayectoriaX, ...
            'YData', ...
            trayectoriaY, ...
            'ZData', ...
            trayectoriaZ ...
        );

    end

    %% ============================================================
    % ACTUALIZACIÓN DE TEXTO
    % =============================================================

    if ~actualizarTexto

        return;

    end

    %% ============================================================
    % COMPLETAR COMANDOS
    % =============================================================

    comando.armado = logical( ...
        obtener_campo( ...
            comando, ...
            'armado', ...
            false ...
        ) ...
    );

    comando.mandoAdelante = obtener_campo( ...
        comando, ...
        'mandoAdelante', ...
        0 ...
    );

    comando.mandoDerecha = obtener_campo( ...
        comando, ...
        'mandoDerecha', ...
        0 ...
    );

    comando.mandoAltura = obtener_campo( ...
        comando, ...
        'mandoAltura', ...
        0 ...
    );

    comando.mandoYaw = obtener_campo( ...
        comando, ...
        'mandoYaw', ...
        0 ...
    );

    %% ============================================================
    % COMPLETAR DATOS
    % =============================================================

    datos.alturaObjetivo_m = obtener_campo( ...
        datos, ...
        'alturaObjetivo_m', ...
        alturaActual_m ...
    );

    datos.modoHorizontal = string( ...
        obtener_campo( ...
            datos, ...
            'modoHorizontal', ...
            "SIN CONTROL" ...
        ) ...
    );

    datos.velocidadUp_m_s = obtener_campo( ...
        datos, ...
        'velocidadUp_m_s', ...
        -estado(6) ...
    );

    datos.empujeMotores_N = obtener_campo( ...
        datos, ...
        'empujeMotores_N', ...
        zeros(4, 1) ...
    );

    datos.empujeMotores_N = ...
        datos.empujeMotores_N(:);

    if numel(datos.empujeMotores_N) < 4

        datos.empujeMotores_N(4, 1) = ...
            0;

    end

    datos.empujeMotores_N = ...
        datos.empujeMotores_N(1:4);

    datos.empujeTotal_N = obtener_campo( ...
        datos, ...
        'empujeTotal_N', ...
        sum(datos.empujeMotores_N) ...
    );

    datos.empujeHoverTotal_N = obtener_campo( ...
        datos, ...
        'empujeHoverTotal_N', ...
        NaN ...
    );

    datos.saturacionMotores = logical( ...
        obtener_campo( ...
            datos, ...
            'saturacionMotores', ...
            false ...
        ) ...
    );

    datos.maniobra = obtener_campo( ...
        datos, ...
        'maniobra', ...
        struct() ...
    );

    datos.maniobra.activa = logical( ...
        obtener_campo( ...
            datos.maniobra, ...
            'activa', ...
            false ...
        ) ...
    );

    datos.maniobra.tipo = string( ...
        obtener_campo( ...
            datos.maniobra, ...
            'tipo', ...
            "NINGUNA" ...
        ) ...
    );

    datos.maniobra.tiempoTranscurrido_s = obtener_campo( ...
        datos.maniobra, ...
        'tiempoTranscurrido_s', ...
        0 ...
    );

    datos.maniobra.alturaInicial_m = obtener_campo( ...
        datos.maniobra, ...
        'alturaInicial_m', ...
        alturaActual_m ...
    );

    datos.maniobra.alturaObjetivo_m = obtener_campo( ...
        datos.maniobra, ...
        'alturaObjetivo_m', ...
        datos.alturaObjetivo_m ...
    );

    datos.resultadoAscenso = completar_resultado( ...
        obtener_campo( ...
            datos, ...
            'resultadoAscenso', ...
            struct() ...
        ) ...
    );

    datos.resultadoDescenso = completar_resultado( ...
        obtener_campo( ...
            datos, ...
            'resultadoDescenso', ...
            struct() ...
        ) ...
    );

    %% ============================================================
    % PANEL DE ESTADO
    % =============================================================

    if comando.armado

        estadoArmado = ...
            'ARMADO';

    else

        estadoArmado = ...
            'DESARMADO';

    end

    velocidadTotal_m_s = ...
        norm(estado(4:6));

    textoEstado = sprintf([ ...
        'ESTADO DEL DRON\n' ...
        '-----------------------------\n' ...
        'Estado:        %s\n' ...
        'Tiempo:        %7.2f s\n' ...
        'Modo horiz.:   %s\n\n' ...
        'ALTURA\n' ...
        '-----------------------------\n' ...
        'Actual:        %7.3f m\n' ...
        'Objetivo:      %7.3f m\n' ...
        'Error:         %+7.3f m\n' ...
        'Vel. vertical: %+7.3f m/s\n\n' ...
        'POSICIÓN\n' ...
        '-----------------------------\n' ...
        'Norte:         %+7.3f m\n' ...
        'Este:          %+7.3f m\n' ...
        'Velocidad:      %7.3f m/s\n\n' ...
        'ORIENTACIÓN\n' ...
        '-----------------------------\n' ...
        'Roll:          %+7.2f grados\n' ...
        'Pitch:         %+7.2f grados\n' ...
        'Yaw:           %+7.2f grados\n\n' ...
        'CONTROLES\n' ...
        '-----------------------------\n' ...
        'Adelante:      %+5.2f\n' ...
        'Derecha:       %+5.2f\n' ...
        'Altura W/S:    %+5.2f\n' ...
        'Yaw:           %+5.2f\n'], ...
        estadoArmado, ...
        tiempo, ...
        char(datos.modoHorizontal), ...
        alturaActual_m, ...
        datos.alturaObjetivo_m, ...
        datos.alturaObjetivo_m - alturaActual_m, ...
        datos.velocidadUp_m_s, ...
        xN_m, ...
        yE_m, ...
        velocidadTotal_m_s, ...
        rad2deg(phi_rad), ...
        rad2deg(theta_rad), ...
        rad2deg(psi_rad), ...
        comando.mandoAdelante, ...
        comando.mandoDerecha, ...
        comando.mandoAltura, ...
        comando.mandoYaw ...
    );

    if isfield(visual, 'textoEstado') && ...
            isgraphics(visual.textoEstado)

        set( ...
            visual.textoEstado, ...
            'String', ...
            textoEstado ...
        );

    end

    %% ============================================================
    % PANEL DE MANIOBRAS
    % =============================================================

    if datos.maniobra.activa

        textoActual = sprintf([ ...
            'Maniobra actual: %s\n' ...
            'Altura inicial:  %.3f m\n' ...
            'Altura objetivo: %.3f m\n' ...
            'Tiempo actual:   %.3f s\n'], ...
            char(datos.maniobra.tipo), ...
            datos.maniobra.alturaInicial_m, ...
            datos.maniobra.alturaObjetivo_m, ...
            datos.maniobra.tiempoTranscurrido_s ...
        );

    else

        textoActual = sprintf([ ...
            'Maniobra actual: NINGUNA\n' ...
            'Shift: subir un metro\n' ...
            'Espacio: bajar un metro\n' ...
        ]);

    end

    textoAscenso = formatear_resultado( ...
        'ÚLTIMO ASCENSO', ...
        datos.resultadoAscenso ...
    );

    textoDescenso = formatear_resultado( ...
        'ÚLTIMO DESCENSO', ...
        datos.resultadoDescenso ...
    );

    textoManiobra = sprintf([ ...
        'MANIOBRAS AUTOMÁTICAS\n' ...
        '-----------------------------\n' ...
        '%s\n' ...
        '-----------------------------\n' ...
        '%s\n' ...
        '-----------------------------\n' ...
        '%s'], ...
        textoActual, ...
        textoAscenso, ...
        textoDescenso ...
    );

    if isfield(visual, 'textoManiobra') && ...
            isgraphics(visual.textoManiobra)

        set( ...
            visual.textoManiobra, ...
            'String', ...
            textoManiobra ...
        );

    end

    %% ============================================================
    % PANEL DE MOTORES
    % =============================================================

    if datos.saturacionMotores

        textoSaturacion = ...
            'SÍ';

    else

        textoSaturacion = ...
            'NO';

    end

    textoMotores = sprintf([ ...
        'FUERZA ACTUAL DE MOTORES\n' ...
        '-----------------------------\n' ...
        'Motor 1:    %7.4f N\n' ...
        'Motor 2:    %7.4f N\n' ...
        'Motor 3:    %7.4f N\n' ...
        'Motor 4:    %7.4f N\n' ...
        'Total:      %7.4f N\n' ...
        'Saturación: %s\n'], ...
        datos.empujeMotores_N(1), ...
        datos.empujeMotores_N(2), ...
        datos.empujeMotores_N(3), ...
        datos.empujeMotores_N(4), ...
        datos.empujeTotal_N, ...
        textoSaturacion ...
    );

    if isfield(visual, 'textoMotores') && ...
            isgraphics(visual.textoMotores)

        set( ...
            visual.textoMotores, ...
            'String', ...
            textoMotores ...
        );

    end

end


function resultado = completar_resultado(resultado)

    if ~isstruct(resultado)

        resultado = ...
            struct();

    end

    resultado.completado = logical( ...
        obtener_campo( ...
            resultado, ...
            'completado', ...
            false ...
        ) ...
    );

    resultado.tiempo_s = obtener_campo( ...
        resultado, ...
        'tiempo_s', ...
        NaN ...
    );

    resultado.alturaInicial_m = obtener_campo( ...
        resultado, ...
        'alturaInicial_m', ...
        NaN ...
    );

    resultado.alturaFinal_m = obtener_campo( ...
        resultado, ...
        'alturaFinal_m', ...
        NaN ...
    );

    resultado.empujeTotalPromedio_N = obtener_campo( ...
        resultado, ...
        'empujeTotalPromedio_N', ...
        NaN ...
    );

    resultado.empujePromedioMotor_N = obtener_campo( ...
        resultado, ...
        'empujePromedioMotor_N', ...
        NaN ...
    );

    resultado.empujeTotalMaximo_N = obtener_campo( ...
        resultado, ...
        'empujeTotalMaximo_N', ...
        NaN ...
    );

    resultado.empujeTotalMinimo_N = obtener_campo( ...
        resultado, ...
        'empujeTotalMinimo_N', ...
        NaN ...
    );

end


function texto = formatear_resultado( ...
    titulo, ...
    resultado ...
)

    if ~resultado.completado

        texto = sprintf([ ...
            '%s\n' ...
            'Sin medición disponible.\n'], ...
            titulo ...
        );

        return;

    end

    texto = sprintf([ ...
        '%s\n' ...
        'Tiempo:             %.3f s\n' ...
        'Altura inicial:     %.3f m\n' ...
        'Altura final:       %.3f m\n' ...
        'Cambio real:        %+.3f m\n' ...
        'Empuje prom. total: %.4f N\n'], ...
        titulo, ...
        resultado.tiempo_s, ...
        resultado.alturaInicial_m, ...
        resultado.alturaFinal_m, ...
        resultado.alturaFinal_m - ...
        resultado.alturaInicial_m, ...
        resultado.empujeTotalPromedio_N ...
    );

end


function valor = obtener_campo( ...
    estructura, ...
    nombreCampo, ...
    valorPredeterminado ...
)

    if isstruct(estructura) && ...
            isfield(estructura, nombreCampo)

        valor = ...
            estructura.(nombreCampo);

    else

        valor = ...
            valorPredeterminado;

    end

end


function R_B_N = matriz_rotacion_body_ned( ...
    phi, ...
    theta, ...
    psi ...
)

    cPhi = cos(phi);
    sPhi = sin(phi);

    cTheta = cos(theta);
    sTheta = sin(theta);

    cPsi = cos(psi);
    sPsi = sin(psi);

    R_B_N = [
        cTheta*cPsi, ...
        sPhi*sTheta*cPsi - cPhi*sPsi, ...
        cPhi*sTheta*cPsi + sPhi*sPsi

        cTheta*sPsi, ...
        sPhi*sTheta*sPsi + cPhi*cPsi, ...
        cPhi*sTheta*sPsi - sPhi*cPsi

        -sTheta, ...
        sPhi*cTheta, ...
        cPhi*cTheta
    ];

end