function visual = crear_visualizacion_dron()
%CREAR_VISUALIZACION_DRON
% Crea la representación gráfica 3D del dron y los paneles de
% información de la simulación interactiva.
%
% La ventana contiene:
%
%   - Representación tridimensional del dron.
%   - Trayectoria recorrida.
%   - Cámara seguidora.
%   - Estado general del vuelo.
%   - Altura actual y altura objetivo.
%   - Resultados de ascenso y descenso de un metro.
%   - Fuerza instantánea de cada motor.
%
% Los textos se muestran en color negro para facilitar su lectura.
%
% Esta función solamente crea los objetos gráficos.
% actualizar_visualizacion_dron será responsable de cambiar los datos.

    %% ============================================================
    % VENTANA PRINCIPAL
    % =============================================================

    figura = figure( ...
        'Name', ...
        'Simulador físico interactivo del dron', ...
        'NumberTitle', ...
        'off', ...
        'Color', ...
        'white', ...
        'Position', ...
        [70, 45, 1320, 780], ...
        'WindowStyle', ...
        'normal' ...
    );

    %% ============================================================
    % EJES TRIDIMENSIONALES
    % =============================================================

    ejes = axes( ...
        'Parent', ...
        figura, ...
        'Units', ...
        'normalized', ...
        'Position', ...
        [0.04, 0.08, 0.68, 0.86] ...
    );

    hold(ejes, 'on');
    grid(ejes, 'on');
    box(ejes, 'on');

    axis(ejes, 'equal');
    axis(ejes, 'vis3d');

    xlim(ejes, [-5, 5]);
    ylim(ejes, [-5, 5]);
    zlim(ejes, [0, 5]);

    view(ejes, 38, 25);

    xlabel(ejes, 'X Norte [m]');
    ylabel(ejes, 'Y Este [m]');
    zlabel(ejes, 'Altura [m]');

    title( ...
        ejes, ...
        'Gemelo virtual del KIWO E88' ...
    );

    %% ============================================================
    % PISO
    % =============================================================

    [xPiso, yPiso] = meshgrid( ...
        -5:1:5, ...
        -5:1:5 ...
    );

    zPiso = zeros( ...
        size(xPiso) ...
    );

    piso = surf( ...
        ejes, ...
        xPiso, ...
        yPiso, ...
        zPiso, ...
        'FaceColor', ...
        [0.85, 0.85, 0.85], ...
        'FaceAlpha', ...
        0.20, ...
        'EdgeColor', ...
        [0.65, 0.65, 0.65], ...
        'HandleVisibility', ...
        'off' ...
    );

    %% ============================================================
    % TRANSFORMACIÓN GENERAL DEL DRON
    % =============================================================

    transformacion = hgtransform( ...
        'Parent', ...
        ejes ...
    );

    %% ============================================================
    % DIMENSIONES GRÁFICAS
    % =============================================================

    % Estas dimensiones son únicamente visuales.
    %
    % La dinámica utiliza las dimensiones físicas almacenadas
    % dentro de caso_real_dron.m.

    longitudBrazo = ...
        0.48;

    radioMotor = ...
        0.075;

    radioCentro = ...
        0.11;

    %% ============================================================
    % BRAZOS EN CONFIGURACIÓN X
    % =============================================================

    plot3( ...
        [-longitudBrazo, longitudBrazo], ...
        [-longitudBrazo, longitudBrazo], ...
        [0, 0], ...
        'LineWidth', ...
        6, ...
        'Color', ...
        [0.12, 0.12, 0.12], ...
        'Parent', ...
        transformacion ...
    );

    plot3( ...
        [-longitudBrazo, longitudBrazo], ...
        [longitudBrazo, -longitudBrazo], ...
        [0, 0], ...
        'LineWidth', ...
        6, ...
        'Color', ...
        [0.12, 0.12, 0.12], ...
        'Parent', ...
        transformacion ...
    );

    %% ============================================================
    % GEOMETRÍA BASE DE LAS ESFERAS
    % =============================================================

    [sx, sy, sz] = sphere(18);

    %% ============================================================
    % CUERPO CENTRAL
    % =============================================================

    cuerpoCentral = surface( ...
        'XData', ...
        radioCentro * sx, ...
        'YData', ...
        radioCentro * sy, ...
        'ZData', ...
        radioCentro * sz, ...
        'FaceColor', ...
        [0.15, 0.45, 0.85], ...
        'EdgeColor', ...
        'none', ...
        'Parent', ...
        transformacion ...
    );

    %% ============================================================
    % POSICIONES GRÁFICAS DE LOS MOTORES
    % =============================================================

    posicionesMotores = [
         longitudBrazo,  longitudBrazo, 0
         longitudBrazo, -longitudBrazo, 0
        -longitudBrazo,  longitudBrazo, 0
        -longitudBrazo, -longitudBrazo, 0
    ];

    %% ============================================================
    % CREAR MOTORES
    % =============================================================

    motoresGraficos = gobjects(4, 1);

    for numeroMotor = 1:4

        posicionMotor = ...
            posicionesMotores(numeroMotor, :);

        motoresGraficos(numeroMotor) = surface( ...
            'XData', ...
            radioMotor * sx + posicionMotor(1), ...
            'YData', ...
            radioMotor * sy + posicionMotor(2), ...
            'ZData', ...
            radioMotor * sz + posicionMotor(3), ...
            'FaceColor', ...
            [0.80, 0.20, 0.20], ...
            'EdgeColor', ...
            'none', ...
            'Parent', ...
            transformacion ...
        );

    end

    %% ============================================================
    % INDICADOR FRONTAL
    % =============================================================

    indicadorFrontal = patch( ...
        'XData', ...
        [0.18, 0.72, 0.18], ...
        'YData', ...
        [-0.14, 0, 0.14], ...
        'ZData', ...
        [0.04, 0.04, 0.04], ...
        'FaceColor', ...
        [1.00, 0.75, 0.05], ...
        'EdgeColor', ...
        [0.40, 0.25, 0.00], ...
        'LineWidth', ...
        1.5, ...
        'Parent', ...
        transformacion ...
    );

    %% ============================================================
    % TRAYECTORIA RECORRIDA
    % =============================================================

    trayectoria = plot3( ...
        ejes, ...
        NaN, ...
        NaN, ...
        NaN, ...
        'LineWidth', ...
        1.8, ...
        'Color', ...
        [0.25, 0.25, 0.75], ...
        'DisplayName', ...
        'Trayectoria' ...
    );

    %% ============================================================
    % PANEL 1: ESTADO GENERAL
    % =============================================================

    textoEstado = uicontrol( ...
        figura, ...
        'Style', ...
        'text', ...
        'Units', ...
        'normalized', ...
        'Position', ...
        [0.745, 0.54, 0.24, 0.40], ...
        'BackgroundColor', ...
        [0.96, 0.96, 0.96], ...
        'ForegroundColor', ...
        [0, 0, 0], ...
        'HorizontalAlignment', ...
        'left', ...
        'FontName', ...
        'Consolas', ...
        'FontSize', ...
        10.5, ...
        'FontWeight', ...
        'normal', ...
        'String', ...
        sprintf([ ...
            'ESTADO DEL DRON\n\n' ...
            'Inicializando simulación...\n' ...
        ]) ...
    );

    %% ============================================================
    % PANEL 2: MANIOBRAS DE UN METRO
    % =============================================================

    textoManiobra = uicontrol( ...
        figura, ...
        'Style', ...
        'text', ...
        'Units', ...
        'normalized', ...
        'Position', ...
        [0.745, 0.245, 0.24, 0.275], ...
        'BackgroundColor', ...
        [0.98, 0.98, 0.98], ...
        'ForegroundColor', ...
        [0, 0, 0], ...
        'HorizontalAlignment', ...
        'left', ...
        'FontName', ...
        'Consolas', ...
        'FontSize', ...
        10, ...
        'FontWeight', ...
        'normal', ...
        'String', ...
        sprintf([ ...
            'MANIOBRAS DE 1 METRO\n' ...
            '--------------------------\n' ...
            'Maniobra actual: ninguna\n\n' ...
            'ÚLTIMO ASCENSO\n' ...
            'Tiempo:  sin medición\n' ...
            'Fuerza:  sin medición\n\n' ...
            'ÚLTIMO DESCENSO\n' ...
            'Tiempo:  sin medición\n' ...
            'Fuerza:  sin medición\n' ...
        ]) ...
    );

    %% ============================================================
    % PANEL 3: FUERZA DE LOS MOTORES
    % =============================================================

    textoMotores = uicontrol( ...
        figura, ...
        'Style', ...
        'text', ...
        'Units', ...
        'normalized', ...
        'Position', ...
        [0.745, 0.075, 0.24, 0.15], ...
        'BackgroundColor', ...
        [0.96, 0.96, 0.96], ...
        'ForegroundColor', ...
        [0, 0, 0], ...
        'HorizontalAlignment', ...
        'left', ...
        'FontName', ...
        'Consolas', ...
        'FontSize', ...
        10, ...
        'FontWeight', ...
        'normal', ...
        'String', ...
        sprintf([ ...
            'FUERZA ACTUAL DE MOTORES\n' ...
            '--------------------------\n' ...
            'M1: 0.0000 N\n' ...
            'M2: 0.0000 N\n' ...
            'M3: 0.0000 N\n' ...
            'M4: 0.0000 N\n' ...
            'Total: 0.0000 N\n' ...
        ]) ...
    );

    %% ============================================================
    % ILUMINACIÓN
    % =============================================================

    camlight( ...
        ejes, ...
        'headlight' ...
    );

    lighting( ...
        ejes, ...
        'gouraud' ...
    );

    %% ============================================================
    % GUARDAR ELEMENTOS GRÁFICOS
    % =============================================================

    visual.figura = ...
        figura;

    visual.ejes = ...
        ejes;

    visual.transformacion = ...
        transformacion;

    visual.trayectoria = ...
        trayectoria;

    visual.piso = ...
        piso;

    visual.cuerpoCentral = ...
        cuerpoCentral;

    visual.motoresGraficos = ...
        motoresGraficos;

    visual.indicadorFrontal = ...
        indicadorFrontal;

    visual.posicionesMotores = ...
        posicionesMotores;

    %% Textos nuevos

    visual.textoEstado = ...
        textoEstado;

    visual.textoManiobra = ...
        textoManiobra;

    visual.textoMotores = ...
        textoMotores;

    % Compatibilidad con actualizar_visualizacion_dron anterior.
    %
    % El campo visual.texto continúa apuntando al panel principal.

    visual.texto = ...
        textoEstado;

    %% ============================================================
    % FORZAR DIBUJO
    % =============================================================

    drawnow;

end