function visual = crear_visualizacion_dron()
%CREAR_VISUALIZACION_DRON Crea la representación gráfica 3D del dron.
%
% El dron se representa mediante:
%   - Dos brazos cruzados en X
%   - Cuatro motores
%   - Centro de masa
%   - Indicador frontal
%   - Trayectoria recorrida
%   - Panel de información

    %% Ventana principal

    figura = figure( ...
        'Name', 'Simulador interactivo del dron', ...
        'NumberTitle', 'off', ...
        'Color', 'white', ...
        'Position', [100, 80, 1150, 720] ...
    );

    %% Ejes tridimensionales

    ejes = axes( ...
        'Parent', figura, ...
        'Units', 'normalized', ...
        'Position', [0.05, 0.08, 0.68, 0.86] ...
    );

    hold(ejes, 'on');
    grid(ejes, 'on');

    axis(ejes, 'equal');
    axis(ejes, 'vis3d');

    xlim(ejes, [-5, 5]);
    ylim(ejes, [-5, 5]);
    zlim(ejes, [0, 5]);

    view(ejes, 38, 25);

    xlabel(ejes, 'X Norte [m]');
    ylabel(ejes, 'Y Este [m]');
    zlabel(ejes, 'Altura [m]');

    title(ejes, 'Gemelo virtual del dron');

    %% Piso

    [xPiso, yPiso] = meshgrid(-5:1:5, -5:1:5);

    zPiso = zeros(size(xPiso));

    piso = surf( ...
        ejes, ...
        xPiso, ...
        yPiso, ...
        zPiso, ...
        'FaceColor', [0.85, 0.85, 0.85], ...
        'FaceAlpha', 0.20, ...
        'EdgeColor', [0.65, 0.65, 0.65], ...
        'HandleVisibility', 'off' ...
    );

    %% Transformación general del dron

    transformacion = hgtransform( ...
        'Parent', ejes ...
    );

    %% Dimensiones gráficas del dron

    longitudBrazo = 0.48;

    radioMotor = 0.075;

    radioCentro = 0.11;

    %% Brazos en configuración X

    plot3( ...
        [-longitudBrazo, longitudBrazo], ...
        [-longitudBrazo, longitudBrazo], ...
        [0, 0], ...
        'LineWidth', 6, ...
        'Color', [0.12, 0.12, 0.12], ...
        'Parent', transformacion ...
    );

    plot3( ...
        [-longitudBrazo, longitudBrazo], ...
        [longitudBrazo, -longitudBrazo], ...
        [0, 0], ...
        'LineWidth', 6, ...
        'Color', [0.12, 0.12, 0.12], ...
        'Parent', transformacion ...
    );

    %% Geometría base de las esferas

    [sx, sy, sz] = sphere(18);

    %% Esfera central

    surface( ...
        'XData', radioCentro * sx, ...
        'YData', radioCentro * sy, ...
        'ZData', radioCentro * sz, ...
        'FaceColor', [0.15, 0.45, 0.85], ...
        'EdgeColor', 'none', ...
        'Parent', transformacion ...
    );

    %% Posiciones de los cuatro motores

    posicionesMotores = [ ...
         longitudBrazo,  longitudBrazo, 0;
         longitudBrazo, -longitudBrazo, 0;
        -longitudBrazo,  longitudBrazo, 0;
        -longitudBrazo, -longitudBrazo, 0 ...
    ];

    %% Crear motores

    for numeroMotor = 1:4

        posicion = posicionesMotores(numeroMotor, :);

        surface( ...
            'XData', radioMotor * sx + posicion(1), ...
            'YData', radioMotor * sy + posicion(2), ...
            'ZData', radioMotor * sz + posicion(3), ...
            'FaceColor', [0.80, 0.20, 0.20], ...
            'EdgeColor', 'none', ...
            'Parent', transformacion ...
        );

    end

    %% Indicador frontal

    patch( ...
        'XData', [0.18, 0.72, 0.18], ...
        'YData', [-0.14, 0, 0.14], ...
        'ZData', [0.04, 0.04, 0.04], ...
        'FaceColor', [1.00, 0.75, 0.05], ...
        'EdgeColor', [0.40, 0.25, 0.00], ...
        'LineWidth', 1.5, ...
        'Parent', transformacion ...
    );

    %% Trayectoria recorrida

    trayectoria = plot3( ...
        ejes, ...
        NaN, ...
        NaN, ...
        NaN, ...
        'LineWidth', 1.8, ...
        'Color', [0.25, 0.25, 0.75] ...
    );

    %% Panel de información

    texto = uicontrol( ...
        figura, ...
        'Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.76, 0.08, 0.22, 0.86], ...
        'BackgroundColor', [0.96, 0.96, 0.96], ...
        'ForegroundColor', [0.10, 0.10, 0.10], ...
        'HorizontalAlignment', 'left', ...
        'FontName', 'Consolas', ...
        'FontSize', 11, ...
        'String', 'Inicializando...' ...
    );

    %% Iluminación

    camlight(ejes, 'headlight');

    lighting(ejes, 'gouraud');

    %% Guardar elementos gráficos

    visual.figura = figura;

    visual.ejes = ejes;

    visual.transformacion = transformacion;

    visual.trayectoria = trayectoria;

    visual.texto = texto;

    visual.piso = piso;

end