function visual = crear_visualizacion_dron()
%CREAR_VISUALIZACION_DRON Crea la visualización 3D del dron real.
%
% Esta versión utiliza:
%
%   cad/Dron.stl
%       ↓
%   cargar_modelo_dron_cad.m
%       ↓
%   Patch triangular
%       ↓
%   hgtransform
%
% El CAD queda conectado a la misma transformación utilizada por
% actualizar_visualizacion_dron.m. Por lo tanto, no es necesario
% modificar:
%
%   - simulacion_interactiva_fisica.m
%   - actualizar_visualizacion_dron.m
%   - controlador_traslacional.m
%   - controlador_actitud.m
%
% CAMPOS PRINCIPALES DE SALIDA:
%
%   visual.figura
%   visual.ejes
%   visual.transformacion
%   visual.modeloDron
%   visual.trayectoria
%   visual.piso
%   visual.textoEstado
%   visual.textoManiobra
%   visual.textoMotores
%
% El modelo STL pierde los colores originales del ensamble. Por eso
% se dibuja con un color uniforme y sombreado tridimensional.

    %% ============================================================
    % CARGAR EL CAD PROCESADO
    % =============================================================

    fprintf('\n');
    fprintf('Preparando visualización del dron real...\n');

    CAD = cargar_modelo_dron_cad();

    if isempty(CAD.caras) || ...
            isempty(CAD.vertices_m)

        error( ...
            'crear_visualizacion_dron:CADVacio', ...
            'El modelo CAD no contiene caras o vértices.' ...
        );

    end

    %% ============================================================
    % AJUSTAR ESCALA VISUAL AL DRON FÍSICO
    % =============================================================

    % Dimensión horizontal mayor medida para el dron real:
    %
    %   Largo aproximado: 17 cm.
    %   Ancho aproximado: 14 cm.
    %
    % El escalado es uniforme, por lo que no deforma el CAD.

    dimensionHorizontalObjetivo_m = ...
        0.17;

    dimensionHorizontalCAD_m = max( ...
        CAD.dimensiones_m(1:2) ...
    );

    if ~isfinite(dimensionHorizontalCAD_m) || ...
            dimensionHorizontalCAD_m <= 0

        error( ...
            'crear_visualizacion_dron:DimensionCADInvalida', ...
            'La dimensión horizontal del CAD no es válida.' ...
        );

    end

    factorEscalaCAD = ...
        dimensionHorizontalObjetivo_m / ...
        dimensionHorizontalCAD_m;

    verticesVisuales_m = ...
        CAD.vertices_m * ...
        factorEscalaCAD;

    dimensionesVisuales_m = ...
        CAD.dimensiones_m * ...
        factorEscalaCAD;

    fprintf('CAD integrado en la visualización.\n');
    fprintf('  Dimensión visual X: %.4f m\n', ...
        dimensionesVisuales_m(1));

    fprintf('  Dimensión visual Y: %.4f m\n', ...
        dimensionesVisuales_m(2));

    fprintf('  Dimensión visual Z: %.4f m\n', ...
        dimensionesVisuales_m(3));

    fprintf('  Factor de escala:   %.6f\n', ...
        factorEscalaCAD);

    fprintf('  Triángulos:         %d\n\n', ...
        CAD.numeroCaras);

    %% ============================================================
    % CREAR FIGURA
    % =============================================================

    figura = figure( ...
        'Name', ...
        'Gemelo virtual — KIWO E88 real V1', ...
        'NumberTitle', ...
        'off', ...
        'Color', ...
        [0.96, 0.97, 0.98], ...
        'Units', ...
        'normalized', ...
        'Position', ...
        [0.025, 0.055, 0.95, 0.88], ...
        'MenuBar', ...
        'none', ...
        'ToolBar', ...
        'figure', ...
        'Interruptible', ...
        'on', ...
        'BusyAction', ...
        'queue' ...
    );

    %% ============================================================
    % EJES PRINCIPALES
    % =============================================================

    ejes = axes( ...
        'Parent', ...
        figura, ...
        'Units', ...
        'normalized', ...
        'Position', ...
        [0.045, 0.075, 0.655, 0.865], ...
        'Box', ...
        'on', ...
        'NextPlot', ...
        'add', ...
        'Color', ...
        [0.985, 0.99, 1.0], ...
        'XGrid', ...
        'on', ...
        'YGrid', ...
        'on', ...
        'ZGrid', ...
        'on', ...
        'GridAlpha', ...
        0.20, ...
        'MinorGridAlpha', ...
        0.10, ...
        'FontSize', ...
        10 ...
    );

    hold( ...
        ejes, ...
        'on' ...
    );

    axis( ...
        ejes, ...
        'equal' ...
    );

    axis( ...
        ejes, ...
        'vis3d' ...
    );

    daspect( ...
        ejes, ...
        [1, 1, 1] ...
    );

    xlabel( ...
        ejes, ...
        'Norte X [m]' ...
    );

    ylabel( ...
        ejes, ...
        'Este Y [m]' ...
    );

    zlabel( ...
        ejes, ...
        'Altura [m]' ...
    );

    title( ...
        ejes, ...
        'KIWO E88 real V1 — modelo CAD' ...
    );

    view( ...
        ejes, ...
        42, ...
        24 ...
    );

    camproj( ...
        ejes, ...
        'perspective' ...
    );

    %% Límites iniciales

    xlim( ...
        ejes, ...
        [-.75, .75] ...
    );

    ylim( ...
        ejes, ...
        [-.75, .75] ...
    );

    zlim( ...
        ejes, ...
        [0, 2.5] ...
    );

    %% ============================================================
    % PISO
    % =============================================================

    radioPiso_m = ...
        1.5;

    separacionCuadricula_m = ...
        .10;

    [xPiso, yPiso] = meshgrid( ...
        -radioPiso_m: ...
        separacionCuadricula_m: ...
        radioPiso_m ...
    );

    zPiso = ...
        zeros(size(xPiso));

    piso = surf( ...
        ejes, ...
        xPiso, ...
        yPiso, ...
        zPiso, ...
        'FaceColor', ...
        [0.92, 0.94, 0.96], ...
        'FaceAlpha', ...
        0.32, ...
        'EdgeColor', ...
        [0.70, 0.73, 0.77], ...
        'EdgeAlpha', ...
        0.55, ...
        'LineWidth', ...
        0.50, ...
        'HitTest', ...
        'off' ...
    );

    %% ============================================================
    % LÍNEAS DE REFERENCIA DEL MUNDO
    % =============================================================

    longitudEjesMundo_m = ...
        0.75;

    plot3( ...
        ejes, ...
        [0, longitudEjesMundo_m], ...
        [0, 0], ...
        [0.003, 0.003], ...
        'LineWidth', ...
        2.0, ...
        'HitTest', ...
        'off' ...
    );

    plot3( ...
        ejes, ...
        [0, 0], ...
        [0, longitudEjesMundo_m], ...
        [0.003, 0.003], ...
        'LineWidth', ...
        2.0, ...
        'HitTest', ...
        'off' ...
    );

    %% ============================================================
    % TRAYECTORIA
    % =============================================================

    trayectoria = plot3( ...
        ejes, ...
        NaN, ...
        NaN, ...
        NaN, ...
        '-', ...
        'LineWidth', ...
        1.35, ...
        'HitTest', ...
        'off' ...
    );

    %% ============================================================
    % TRANSFORMACIÓN DEL DRON
    % =============================================================

    transformacion = hgtransform( ...
        'Parent', ...
        ejes ...
    );

    %% ============================================================
    % MODELO CAD REAL
    % =============================================================

    modeloDron = patch( ...
        'Parent', ...
        transformacion, ...
        'Faces', ...
        CAD.caras, ...
        'Vertices', ...
        verticesVisuales_m, ...
        'FaceColor', ...
        CAD.colorSugerido, ...
        'EdgeColor', ...
        CAD.colorBordeSugerido, ...
        'FaceAlpha', ...
        1.0, ...
        'FaceLighting', ...
        'gouraud', ...
        'BackFaceLighting', ...
        'reverselit', ...
        'AmbientStrength', ...
        0.32, ...
        'DiffuseStrength', ...
        0.82, ...
        'SpecularStrength', ...
        0.30, ...
        'SpecularExponent', ...
        18, ...
        'HitTest', ...
        'off' ...
    );

    %% ============================================================
    % MARCADOR DISCRETO DEL FRENTE
    % =============================================================

    % Este pequeño punto permite comprobar que +X corresponde al
    % frente del dron. Puede eliminarse posteriormente si ya se
    % confirmó la orientación.

    radioMarcador_m = ...
        max(0.004, 0.025 * dimensionHorizontalObjetivo_m);

    centroMarcadorFrente_m = [
        0.47 * dimensionesVisuales_m(1)
        0
        0
    ];

    [xMarcador, yMarcador, zMarcador] = sphere( ...
        10 ...
    );

   marcadorFrente = surface( ...
    'Parent', ...
    transformacion, ...
    'XData', ...
    radioMarcador_m * xMarcador + ...
        centroMarcadorFrente_m(1), ...
    'YData', ...
    radioMarcador_m * yMarcador + ...
        centroMarcadorFrente_m(2), ...
    'ZData', ...
    radioMarcador_m * zMarcador + ...
        centroMarcadorFrente_m(3), ...
    'FaceColor', ...
    [0.90, 0.12, 0.10], ...
    'EdgeColor', ...
    'none', ...
    'FaceLighting', ...
    'gouraud', ...
    'BackFaceLighting', ...
    'reverselit', ...
    'HitTest', ...
    'off' ...
);

    %% ============================================================
    % ILUMINACIÓN
    % =============================================================

    luzPrincipal = camlight( ...
        ejes, ...
        'headlight' ...
    );

    set( ...
        luzPrincipal, ...
        'Style', ...
        'infinite' ...
    );

    luzSecundaria = light( ...
        ejes, ...
        'Position', ...
        [-2, -2, 5], ...
        'Style', ...
        'local' ...
    );

    lighting( ...
        ejes, ...
        'gouraud' ...
    );

    %% ============================================================
    % PANELES DE TEXTO
    % =============================================================

    colorFondoPanel = ...
        [1.0, 1.0, 1.0];

    colorTextoPanel = ...
        [0.0, 0.0, 0.0];

    colorBordePanel = ...
        [0.78, 0.80, 0.83];

    %% Panel de estado

    panelEstado = uipanel( ...
        'Parent', ...
        figura, ...
        'Units', ...
        'normalized', ...
        'Position', ...
        [0.720, 0.515, 0.265, 0.455], ...
        'BackgroundColor', ...
        colorFondoPanel, ...
        'ForegroundColor', ...
        colorTextoPanel, ...
        'BorderType', ...
        'line', ...
        'HighlightColor', ...
        colorBordePanel, ...
        'Title', ...
        'Estado y controles', ...
        'FontWeight', ...
        'bold' ...
    );

    textoEstado = uicontrol( ...
        'Parent', ...
        panelEstado, ...
        'Style', ...
        'text', ...
        'Units', ...
        'normalized', ...
        'Position', ...
        [0.025, 0.025, 0.95, 0.95], ...
        'BackgroundColor', ...
        colorFondoPanel, ...
        'ForegroundColor', ...
        colorTextoPanel, ...
        'HorizontalAlignment', ...
        'left', ...
        'FontName', ...
        'Consolas', ...
        'FontSize', ...
        8.5, ...
        'String', ...
        sprintf([ ...
            'ESTADO DEL DRON\n' ...
            '-----------------------------\n' ...
            'Preparando simulación...\n\n' ...
            'Haz clic dentro de la figura.\n' ...
        ]), ...
        'Enable', ...
        'inactive', ...
        'HitTest', ...
        'off' ...
    );

    %% Panel de maniobras

    panelManiobra = uipanel( ...
        'Parent', ...
        figura, ...
        'Units', ...
        'normalized', ...
        'Position', ...
        [0.720, 0.195, 0.265, 0.300], ...
        'BackgroundColor', ...
        colorFondoPanel, ...
        'ForegroundColor', ...
        colorTextoPanel, ...
        'BorderType', ...
        'line', ...
        'HighlightColor', ...
        colorBordePanel, ...
        'Title', ...
        'Maniobras automáticas', ...
        'FontWeight', ...
        'bold' ...
    );

    textoManiobra = uicontrol( ...
        'Parent', ...
        panelManiobra, ...
        'Style', ...
        'text', ...
        'Units', ...
        'normalized', ...
        'Position', ...
        [0.025, 0.025, 0.95, 0.95], ...
        'BackgroundColor', ...
        colorFondoPanel, ...
        'ForegroundColor', ...
        colorTextoPanel, ...
        'HorizontalAlignment', ...
        'left', ...
        'FontName', ...
        'Consolas', ...
        'FontSize', ...
        8.2, ...
        'String', ...
        sprintf([ ...
            'MANIOBRAS AUTOMÁTICAS\n' ...
            '-----------------------------\n' ...
            'Maniobra actual: NINGUNA\n\n' ...
            'Shift: subir un metro\n' ...
            'Espacio: bajar un metro\n' ...
        ]), ...
        'Enable', ...
        'inactive', ...
        'HitTest', ...
        'off' ...
    );

    %% Panel de motores

    panelMotores = uipanel( ...
        'Parent', ...
        figura, ...
        'Units', ...
        'normalized', ...
        'Position', ...
        [0.720, 0.025, 0.265, 0.150], ...
        'BackgroundColor', ...
        colorFondoPanel, ...
        'ForegroundColor', ...
        colorTextoPanel, ...
        'BorderType', ...
        'line', ...
        'HighlightColor', ...
        colorBordePanel, ...
        'Title', ...
        'Motores', ...
        'FontWeight', ...
        'bold' ...
    );

    textoMotores = uicontrol( ...
        'Parent', ...
        panelMotores, ...
        'Style', ...
        'text', ...
        'Units', ...
        'normalized', ...
        'Position', ...
        [0.025, 0.025, 0.95, 0.95], ...
        'BackgroundColor', ...
        colorFondoPanel, ...
        'ForegroundColor', ...
        colorTextoPanel, ...
        'HorizontalAlignment', ...
        'left', ...
        'FontName', ...
        'Consolas', ...
        'FontSize', ...
        8.5, ...
        'String', ...
        sprintf([ ...
            'FUERZA ACTUAL DE MOTORES\n' ...
            '-----------------------------\n' ...
            'Esperando simulación...\n' ...
        ]), ...
        'Enable', ...
        'inactive', ...
        'HitTest', ...
        'off' ...
    );

    %% ============================================================
    % DATOS AUXILIARES PARA ACTUALIZACIÓN OPTIMIZADA
    % =============================================================

    setappdata( ...
        figura, ...
        'trayectoriaX', ...
        [] ...
    );

    setappdata( ...
        figura, ...
        'trayectoriaY', ...
        [] ...
    );

    setappdata( ...
        figura, ...
        'trayectoriaZ', ...
        [] ...
    );

    setappdata( ...
        figura, ...
        'ultimaPosicionCamara', ...
        [NaN; NaN; NaN] ...
    );

    setappdata( ...
        figura, ...
        'ultimoCentroPiso', ...
        [0; 0] ...
    );

    %% ============================================================
    % CONSTRUIR ESTRUCTURA DE SALIDA
    % =============================================================

    visual = struct();

    visual.figura = ...
        figura;

    visual.ejes = ...
        ejes;

    visual.transformacion = ...
        transformacion;

    visual.modeloDron = ...
        modeloDron;

    visual.patchCAD = ...
        modeloDron;

    visual.marcadorFrente = ...
        marcadorFrente;

    visual.trayectoria = ...
        trayectoria;

    visual.piso = ...
        piso;

    visual.luzPrincipal = ...
        luzPrincipal;

    visual.luzSecundaria = ...
        luzSecundaria;

    visual.panelEstado = ...
        panelEstado;

    visual.panelManiobra = ...
        panelManiobra;

    visual.panelMotores = ...
        panelMotores;

    visual.textoEstado = ...
        textoEstado;

    visual.textoManiobra = ...
        textoManiobra;

    visual.textoMotores = ...
        textoMotores;

    % Compatibilidad con versiones anteriores.

    visual.texto = ...
        textoEstado;

    %% Información del CAD

    visual.CAD = ...
        CAD;

    visual.usaCADReal = ...
        true;

    visual.factorEscalaCAD = ...
        factorEscalaCAD;

    visual.dimensionesCADVisual_m = ...
        dimensionesVisuales_m;

    %% ============================================================
    % MOSTRAR FIGURA
    % =============================================================

    figure( ...
        figura ...
    );

    drawnow;

end