function graficar_rechazo_perturbacion_yaw(resultadosYaw)
%GRAFICAR_RECHAZO_PERTURBACION_YAW
% Genera las graficas de la prueba automatica de rechazo de
% perturbaciones externas en yaw.
%
% El controlador actual regula velocidad angular de yaw:
%
%       r_ref = 0 rad/s
%
% No regula directamente el angulo absoluto psi.
%
% Por tanto:
%
%   - La velocidad de yaw debe regresar a cero.
%   - El angulo de yaw puede quedar desplazado.
%
% Entrada:
%
%   resultadosYaw
%       Estructura generada por:
%
%           test_rechazo_perturbacion_yaw.m
%
% Graficas:
%
%   1. Momento externo aplicado.
%   2. Angulo absoluto de yaw.
%   3. Velocidad de yaw contra referencia.
%   4. Error de velocidad de yaw.
%   5. Momentos externos, solicitados y reales.
%   6. Empuje individual de los cuatro motores.

    %% ============================================================
    % VALIDAR ENTRADA
    % =============================================================

    if nargin < 1

        error( ...
            "graficar_rechazo_perturbacion_yaw:FaltaEntrada", ...
            ['Debes proporcionar la estructura resultadosYaw ' ...
             'generada por la prueba de yaw.'] ...
        );

    end

    camposNecesarios = {
        'tiempo_s'
        'yaw_deg'
        'velocidadYaw_deg_s'
        'referenciaYawRate_deg_s'
        'errorYawRate_deg_s'
        'momentoControl_B_Nm'
        'momentoExterno_B_Nm'
        'momentoYawReal_Nm'
        'empujeMotores_N'
        'configuracion'
        'metricas'
    };

    for k = 1:numel(camposNecesarios)

        nombreCampo = ...
            camposNecesarios{k};

        if ~isfield( ...
                resultadosYaw, ...
                nombreCampo ...
            )

            error( ...
                "graficar_rechazo_perturbacion_yaw:CampoFaltante", ...
                "Falta el campo resultadosYaw.%s.", ...
                nombreCampo ...
            );

        end

    end

    %% ============================================================
    % EXTRAER DATOS
    % =============================================================

    tiempo_s = ...
        resultadosYaw.tiempo_s;

    yaw_deg = ...
        resultadosYaw.yaw_deg;

    velocidadYaw_deg_s = ...
        resultadosYaw.velocidadYaw_deg_s;

    referenciaYawRate_deg_s = ...
        resultadosYaw.referenciaYawRate_deg_s;

    errorYawRate_deg_s = ...
        resultadosYaw.errorYawRate_deg_s;

    momentoControlYaw_Nm = ...
        resultadosYaw.momentoControl_B_Nm(:, 3);

    momentoExternoYaw_Nm = ...
        resultadosYaw.momentoExterno_B_Nm(:, 3);

    momentoYawReal_Nm = ...
        resultadosYaw.momentoYawReal_Nm;

    momentoResultanteYaw_Nm = ...
        momentoExternoYaw_Nm + ...
        momentoYawReal_Nm;

    empujeMotores_N = ...
        resultadosYaw.empujeMotores_N;

    inicioPerturbacion_s = ...
        resultadosYaw.configuracion.inicioPerturbacion_s;

    finPerturbacion_s = ...
        resultadosYaw.configuracion.finPerturbacion_s;

    velocidadYawMaxima_deg_s = ...
        resultadosYaw.metricas.velocidadYawMaxima_deg_s;

    tiempoEstablecimiento_s = ...
        resultadosYaw.metricas.tiempoEstablecimiento_s;

    limiteVelocidadYawEstable_deg_s = ...
        resultadosYaw.metricas.limiteVelocidadYawEstable_deg_s;

    yawFinal_deg = ...
        resultadosYaw.metricas.yawFinal_deg;

    velocidadYawFinal_deg_s = ...
        resultadosYaw.metricas.velocidadYawFinal_deg_s;

    %% ============================================================
    % VALIDAR DIMENSIONES
    % =============================================================

    numeroMuestras = ...
        numel(tiempo_s);

    if numel(yaw_deg) ~= numeroMuestras || ...
            numel(velocidadYaw_deg_s) ~= numeroMuestras || ...
            numel(referenciaYawRate_deg_s) ~= numeroMuestras || ...
            numel(errorYawRate_deg_s) ~= numeroMuestras || ...
            numel(momentoControlYaw_Nm) ~= numeroMuestras || ...
            numel(momentoExternoYaw_Nm) ~= numeroMuestras || ...
            numel(momentoYawReal_Nm) ~= numeroMuestras

        error( ...
            "graficar_rechazo_perturbacion_yaw:DimensionesInvalidas", ...
            ['Los historiales no tienen la misma cantidad ' ...
             'de muestras que el vector de tiempo.'] ...
        );

    end

    if size(empujeMotores_N, 1) ~= numeroMuestras

        error( ...
            "graficar_rechazo_perturbacion_yaw:EmpujesInvalidos", ...
            ['El historial de motores no tiene la misma ' ...
             'cantidad de muestras que el tiempo.'] ...
        );

    end

    %% ============================================================
    % CREAR FIGURA
    % =============================================================

    figura = figure( ...
        'Name', ...
        'Rechazo de perturbacion externa en yaw', ...
        'NumberTitle', ...
        'off', ...
        'Color', ...
        'w' ...
    );

    figura.Position = [
        80
        50
        1450
        850
    ];

    panel = tiledlayout( ...
        figura, ...
        3, ...
        2, ...
        'TileSpacing', ...
        'compact', ...
        'Padding', ...
        'compact' ...
    );

    %% ============================================================
    % GRAFICA 1: PERTURBACION EXTERNA
    % =============================================================

    ax1 = nexttile( ...
        panel, ...
        1 ...
    );

    hPerturbacion = plot( ...
        ax1, ...
        tiempo_s, ...
        momentoExternoYaw_Nm, ...
        'LineWidth', ...
        1.8 ...
    );

    hold(ax1, 'on');

    marcar_intervalo_perturbacion_yaw( ...
        ax1, ...
        inicioPerturbacion_s, ...
        finPerturbacion_s ...
    );

    grid(ax1, 'on');

    xlabel(ax1, 'Tiempo [s]');
    ylabel(ax1, 'M_{z,ext} [N·m]');
    title(ax1, 'Perturbacion externa aplicada');

    legend( ...
        ax1, ...
        hPerturbacion, ...
        'Momento externo en yaw', ...
        'Location', ...
        'best' ...
    );

    %% ============================================================
    % GRAFICA 2: ANGULO ABSOLUTO DE YAW
    % =============================================================

    ax2 = nexttile( ...
        panel, ...
        2 ...
    );

    hYaw = plot( ...
        ax2, ...
        tiempo_s, ...
        yaw_deg, ...
        'LineWidth', ...
        1.8 ...
    );

    hold(ax2, 'on');

    hYawInicial = yline( ...
        ax2, ...
        yaw_deg(1), ...
        '--', ...
        'Orientacion inicial', ...
        'LineWidth', ...
        1.0 ...
    );

    marcar_intervalo_perturbacion_yaw( ...
        ax2, ...
        inicioPerturbacion_s, ...
        finPerturbacion_s ...
    );

    grid(ax2, 'on');

    xlabel(ax2, 'Tiempo [s]');
    ylabel(ax2, '\psi [grados]');
    title(ax2, 'Angulo absoluto de yaw');

    legend( ...
        ax2, ...
        [ ...
            hYaw
            hYawInicial
        ], ...
        { ...
            'Yaw real'
            'Yaw inicial'
        }, ...
        'Location', ...
        'best' ...
    );

    %% ============================================================
    % GRAFICA 3: VELOCIDAD DE YAW CONTRA REFERENCIA
    % =============================================================

    ax3 = nexttile( ...
        panel, ...
        3 ...
    );

    hReferenciaYawRate = plot( ...
        ax3, ...
        tiempo_s, ...
        referenciaYawRate_deg_s, ...
        '--', ...
        'LineWidth', ...
        1.5 ...
    );

    hold(ax3, 'on');

    hVelocidadYaw = plot( ...
        ax3, ...
        tiempo_s, ...
        velocidadYaw_deg_s, ...
        'LineWidth', ...
        1.8 ...
    );

    hLimiteSuperior = yline( ...
        ax3, ...
        limiteVelocidadYawEstable_deg_s, ...
        ':', ...
        'Limite superior', ...
        'LineWidth', ...
        1.0 ...
    );

    hLimiteInferior = yline( ...
        ax3, ...
        -limiteVelocidadYawEstable_deg_s, ...
        ':', ...
        'Limite inferior', ...
        'LineWidth', ...
        1.0 ...
    );

    marcar_intervalo_perturbacion_yaw( ...
        ax3, ...
        inicioPerturbacion_s, ...
        finPerturbacion_s ...
    );

    grid(ax3, 'on');

    xlabel(ax3, 'Tiempo [s]');
    ylabel(ax3, 'r [grados/s]');
    title(ax3, 'Control de velocidad angular de yaw');

    legend( ...
        ax3, ...
        [ ...
            hReferenciaYawRate
            hVelocidadYaw
            hLimiteSuperior
            hLimiteInferior
        ], ...
        { ...
            'Referencia de velocidad'
            'Velocidad real de yaw'
            'Banda estable positiva'
            'Banda estable negativa'
        }, ...
        'Location', ...
        'best' ...
    );

    %% ============================================================
    % GRAFICA 4: ERROR DE VELOCIDAD DE YAW
    % =============================================================

    ax4 = nexttile( ...
        panel, ...
        4 ...
    );

    hError = plot( ...
        ax4, ...
        tiempo_s, ...
        errorYawRate_deg_s, ...
        'LineWidth', ...
        1.8 ...
    );

    hold(ax4, 'on');

    hErrorCero = yline( ...
        ax4, ...
        0, ...
        '--', ...
        'Error cero', ...
        'LineWidth', ...
        1.0 ...
    );

    marcar_intervalo_perturbacion_yaw( ...
        ax4, ...
        inicioPerturbacion_s, ...
        finPerturbacion_s ...
    );

    grid(ax4, 'on');

    xlabel(ax4, 'Tiempo [s]');
    ylabel(ax4, 'Error [grados/s]');
    title(ax4, 'Error de velocidad de yaw');

    legend( ...
        ax4, ...
        [ ...
            hError
            hErrorCero
        ], ...
        { ...
            'e_r = r_{ref} - r'
            'Error cero'
        }, ...
        'Location', ...
        'best' ...
    );

    %% ============================================================
    % GRAFICA 5: MOMENTOS EN YAW
    % =============================================================

    ax5 = nexttile( ...
        panel, ...
        5 ...
    );

    hMomentoExterno = plot( ...
        ax5, ...
        tiempo_s, ...
        momentoExternoYaw_Nm, ...
        'LineWidth', ...
        1.6 ...
    );

    hold(ax5, 'on');

    hMomentoSolicitado = plot( ...
        ax5, ...
        tiempo_s, ...
        momentoControlYaw_Nm, ...
        '--', ...
        'LineWidth', ...
        1.6 ...
    );

    hMomentoReal = plot( ...
        ax5, ...
        tiempo_s, ...
        momentoYawReal_Nm, ...
        'LineWidth', ...
        1.8 ...
    );

    hMomentoResultante = plot( ...
        ax5, ...
        tiempo_s, ...
        momentoResultanteYaw_Nm, ...
        ':', ...
        'LineWidth', ...
        1.5 ...
    );

    marcar_intervalo_perturbacion_yaw( ...
        ax5, ...
        inicioPerturbacion_s, ...
        finPerturbacion_s ...
    );

    grid(ax5, 'on');

    xlabel(ax5, 'Tiempo [s]');
    ylabel(ax5, 'Momento [N·m]');
    title(ax5, 'Perturbacion contra correccion de yaw');

    legend( ...
        ax5, ...
        [ ...
            hMomentoExterno
            hMomentoSolicitado
            hMomentoReal
            hMomentoResultante
        ], ...
        { ...
            'Momento externo'
            'Momento solicitado por PID'
            'Momento real de rotores'
            'Momento externo + real'
        }, ...
        'Location', ...
        'best' ...
    );

    %% ============================================================
    % GRAFICA 6: EMPUJE DE LOS MOTORES
    % =============================================================

    ax6 = nexttile( ...
        panel, ...
        6 ...
    );

    hold(ax6, 'on');

    numeroMotores = ...
        size(empujeMotores_N, 2);

    manejadoresMotores = gobjects( ...
        numeroMotores, ...
        1 ...
    );

    nombresMotores = cell( ...
        numeroMotores, ...
        1 ...
    );

    for motor = 1:numeroMotores

        manejadoresMotores(motor) = plot( ...
            ax6, ...
            tiempo_s, ...
            empujeMotores_N(:, motor), ...
            'LineWidth', ...
            1.5 ...
        );

        nombresMotores{motor} = ...
            sprintf('Motor %d', motor);

    end

    marcar_intervalo_perturbacion_yaw( ...
        ax6, ...
        inicioPerturbacion_s, ...
        finPerturbacion_s ...
    );

    grid(ax6, 'on');

    xlabel(ax6, 'Tiempo [s]');
    ylabel(ax6, 'Empuje [N]');
    title(ax6, 'Respuesta individual de los motores');

    legend( ...
        ax6, ...
        manejadoresMotores, ...
        nombresMotores, ...
        'Location', ...
        'best' ...
    );

    %% ============================================================
    % TITULO GENERAL
    % =============================================================

    tituloGeneral = sprintf( ...
        ['Rechazo de perturbacion en yaw | ' ...
         'Velocidad maxima: %.2f grados/s | ' ...
         'Establecimiento: %.3f s | ' ...
         'Yaw final: %.2f grados | ' ...
         'Velocidad final: %.3f grados/s'], ...
        velocidadYawMaxima_deg_s, ...
        tiempoEstablecimiento_s, ...
        yawFinal_deg, ...
        velocidadYawFinal_deg_s ...
    );

    title( ...
        panel, ...
        tituloGeneral, ...
        'FontWeight', ...
        'bold', ...
        'FontSize', ...
        13 ...
    );

    %% ============================================================
    % VINCULAR EJES DE TIEMPO
    % =============================================================

    linkaxes( ...
        [ ...
            ax1
            ax2
            ax3
            ax4
            ax5
            ax6
        ], ...
        'x' ...
    );

    xlim( ...
        ax1, ...
        [ ...
            tiempo_s(1)
            tiempo_s(end)
        ] ...
    );

end


function marcar_intervalo_perturbacion_yaw( ...
    ejeGrafica, ...
    inicioPerturbacion_s, ...
    finPerturbacion_s ...
)
%MARCAR_INTERVALO_PERTURBACION_YAW
% Marca el inicio y el final de la perturbacion sin agregarlos
% a las leyendas de las graficas.

    xline( ...
        ejeGrafica, ...
        inicioPerturbacion_s, ...
        '--', ...
        'Inicio', ...
        'LineWidth', ...
        1.0, ...
        'LabelVerticalAlignment', ...
        'bottom', ...
        'HandleVisibility', ...
        'off' ...
    );

    xline( ...
        ejeGrafica, ...
        finPerturbacion_s, ...
        '--', ...
        'Fin', ...
        'LineWidth', ...
        1.0, ...
        'LabelVerticalAlignment', ...
        'bottom', ...
        'HandleVisibility', ...
        'off' ...
    );

end