function graficar_rechazo_perturbacion(resultados)
%GRAFICAR_RECHAZO_PERTURBACION
% Genera las gráficas de la prueba automática de rechazo de
% perturbaciones externas en roll.
%
% Entrada:
%
%   resultados
%       Estructura generada por:
%
%           test_rechazo_perturbacion_roll.m
%
% Gráficas mostradas:
%
%   1. Momento externo aplicado.
%   2. Roll real contra referencia.
%   3. Error de roll.
%   4. Velocidad angular de roll.
%   5. Momento del PID, momento externo y momento resultante.
%   6. Empuje individual de los cuatro motores.

    %% ============================================================
    % VALIDAR ENTRADA
    % =============================================================

    if nargin < 1

        error( ...
            "graficar_rechazo_perturbacion:FaltaEntrada", ...
            ['Debes proporcionar la estructura resultados ' ...
             'generada por la prueba.'] ...
        );

    end

    camposNecesarios = {
        'tiempo_s'
        'roll_deg'
        'referenciaRoll_deg'
        'errorRoll_deg'
        'velocidadRoll_deg_s'
        'momentoControl_B_Nm'
        'momentoExterno_B_Nm'
        'empujeMotores_N'
        'configuracion'
        'metricas'
    };

    for k = 1:numel(camposNecesarios)

        nombreCampo = camposNecesarios{k};

        if ~isfield(resultados, nombreCampo)

            error( ...
                "graficar_rechazo_perturbacion:CampoFaltante", ...
                "Falta el campo resultados.%s.", ...
                nombreCampo ...
            );

        end

    end

    %% ============================================================
    % EXTRAER DATOS
    % =============================================================

    tiempo_s = ...
        resultados.tiempo_s;

    roll_deg = ...
        resultados.roll_deg;

    referenciaRoll_deg = ...
        resultados.referenciaRoll_deg;

    errorRoll_deg = ...
        resultados.errorRoll_deg;

    velocidadRoll_deg_s = ...
        resultados.velocidadRoll_deg_s;

    momentoControlRoll_Nm = ...
        resultados.momentoControl_B_Nm(:, 1);

    momentoExternoRoll_Nm = ...
        resultados.momentoExterno_B_Nm(:, 1);

    momentoResultanteRoll_Nm = ...
        momentoControlRoll_Nm + ...
        momentoExternoRoll_Nm;

    empujeMotores_N = ...
        resultados.empujeMotores_N;

    inicioPerturbacion_s = ...
        resultados.configuracion.inicioPerturbacion_s;

    finPerturbacion_s = ...
        resultados.configuracion.finPerturbacion_s;

    desviacionMaxima_deg = ...
        resultados.metricas.desviacionMaxima_deg;

    tiempoEstablecimiento_s = ...
        resultados.metricas.tiempoEstablecimiento_s;

    limiteRollEstable_deg = ...
        resultados.metricas.limiteRollEstable_deg;

    rollFinal_deg = ...
        resultados.metricas.rollFinal_deg;

    %% ============================================================
    % VALIDAR DIMENSIONES
    % =============================================================

    numeroMuestras = ...
        numel(tiempo_s);

    if numel(roll_deg) ~= numeroMuestras || ...
            numel(referenciaRoll_deg) ~= numeroMuestras || ...
            numel(errorRoll_deg) ~= numeroMuestras || ...
            numel(velocidadRoll_deg_s) ~= numeroMuestras

        error( ...
            "graficar_rechazo_perturbacion:DimensionesInvalidas", ...
            ['Los historiales no tienen la misma cantidad ' ...
             'de muestras que el vector de tiempo.'] ...
        );

    end

    if size(empujeMotores_N, 1) ~= numeroMuestras

        error( ...
            "graficar_rechazo_perturbacion:EmpujesInvalidos", ...
            ['El historial de motores no tiene la misma ' ...
             'cantidad de muestras que el tiempo.'] ...
        );

    end

    %% ============================================================
    % CREAR FIGURA
    % =============================================================

    figura = figure( ...
        'Name', ...
        'Rechazo de perturbacion externa en roll', ...
        'NumberTitle', ...
        'off', ...
        'Color', ...
        'w' ...
    );

    figura.Position = [
        80
        50
        1450
        850
    ];

    panel = tiledlayout( ...
        figura, ...
        3, ...
        2, ...
        'TileSpacing', ...
        'compact', ...
        'Padding', ...
        'compact' ...
    );

    %% ============================================================
    % GRAFICA 1: PERTURBACION EXTERNA
    % =============================================================

    ax1 = nexttile(panel, 1);

    plot( ...
        ax1, ...
        tiempo_s, ...
        momentoExternoRoll_Nm, ...
        'LineWidth', ...
        1.8 ...
    );

    grid(ax1, 'on');
    hold(ax1, 'on');

    marcar_intervalo_perturbacion( ...
        ax1, ...
        inicioPerturbacion_s, ...
        finPerturbacion_s ...
    );

    xlabel(ax1, 'Tiempo [s]');
    ylabel(ax1, 'M_{x,ext} [N·m]');
    title(ax1, 'Perturbacion externa aplicada');

    legend( ...
        ax1, ...
        'Momento externo en roll', ...
        'Inicio del pulso', ...
        'Fin del pulso', ...
        'Location', ...
        'best' ...
    );

    %% ============================================================
    % GRAFICA 2: ROLL CONTRA REFERENCIA
    % =============================================================

    ax2 = nexttile(panel, 2);

    plot( ...
        ax2, ...
        tiempo_s, ...
        referenciaRoll_deg, ...
        '--', ...
        'LineWidth', ...
        1.5 ...
    );

    hold(ax2, 'on');

    plot( ...
        ax2, ...
        tiempo_s, ...
        roll_deg, ...
        'LineWidth', ...
        1.8 ...
    );

    yline( ...
        ax2, ...
        limiteRollEstable_deg, ...
        ':', ...
        'Limite superior', ...
        'LineWidth', ...
        1.0 ...
    );

    yline( ...
        ax2, ...
        -limiteRollEstable_deg, ...
        ':', ...
        'Limite inferior', ...
        'LineWidth', ...
        1.0 ...
    );

    marcar_intervalo_perturbacion( ...
        ax2, ...
        inicioPerturbacion_s, ...
        finPerturbacion_s ...
    );

    grid(ax2, 'on');

    xlabel(ax2, 'Tiempo [s]');
    ylabel(ax2, 'Roll [grados]');
    title(ax2, 'Respuesta angular del dron');

    legend( ...
        ax2, ...
        'Referencia', ...
        'Roll real', ...
        'Banda estable positiva', ...
        'Banda estable negativa', ...
        'Inicio del pulso', ...
        'Fin del pulso', ...
        'Location', ...
        'best' ...
    );

    %% ============================================================
    % GRAFICA 3: ERROR DE ROLL
    % =============================================================

    ax3 = nexttile(panel, 3);

    plot( ...
        ax3, ...
        tiempo_s, ...
        errorRoll_deg, ...
        'LineWidth', ...
        1.8 ...
    );

    hold(ax3, 'on');

    yline( ...
        ax3, ...
        0, ...
        '--', ...
        'Error cero', ...
        'LineWidth', ...
        1.0 ...
    );

    marcar_intervalo_perturbacion( ...
        ax3, ...
        inicioPerturbacion_s, ...
        finPerturbacion_s ...
    );

    grid(ax3, 'on');

    xlabel(ax3, 'Tiempo [s]');
    ylabel(ax3, 'Error [grados]');
    title(ax3, 'Error de seguimiento en roll');

    legend( ...
        ax3, ...
        'e_\phi = \phi_{ref} - \phi', ...
        'Error cero', ...
        'Inicio del pulso', ...
        'Fin del pulso', ...
        'Location', ...
        'best' ...
    );

    %% ============================================================
    % GRAFICA 4: VELOCIDAD ANGULAR DE ROLL
    % =============================================================

    ax4 = nexttile(panel, 4);

    plot( ...
        ax4, ...
        tiempo_s, ...
        velocidadRoll_deg_s, ...
        'LineWidth', ...
        1.8 ...
    );

    hold(ax4, 'on');

    yline( ...
        ax4, ...
        0, ...
        '--', ...
        'Velocidad cero', ...
        'LineWidth', ...
        1.0 ...
    );

    marcar_intervalo_perturbacion( ...
        ax4, ...
        inicioPerturbacion_s, ...
        finPerturbacion_s ...
    );

    grid(ax4, 'on');

    xlabel(ax4, 'Tiempo [s]');
    ylabel(ax4, 'p [grados/s]');
    title(ax4, 'Velocidad angular alrededor de X_B');

    legend( ...
        ax4, ...
        'Velocidad angular de roll', ...
        'Velocidad cero', ...
        'Inicio del pulso', ...
        'Fin del pulso', ...
        'Location', ...
        'best' ...
    );

    %% ============================================================
    % GRAFICA 5: MOMENTOS EN ROLL
    % =============================================================

    ax5 = nexttile(panel, 5);

    plot( ...
        ax5, ...
        tiempo_s, ...
        momentoExternoRoll_Nm, ...
        'LineWidth', ...
        1.6 ...
    );

    hold(ax5, 'on');

    plot( ...
        ax5, ...
        tiempo_s, ...
        momentoControlRoll_Nm, ...
        'LineWidth', ...
        1.8 ...
    );

    plot( ...
        ax5, ...
        tiempo_s, ...
        momentoResultanteRoll_Nm, ...
        '--', ...
        'LineWidth', ...
        1.5 ...
    );

    yline( ...
        ax5, ...
        0, ...
        ':', ...
        'LineWidth', ...
        1.0 ...
    );

    marcar_intervalo_perturbacion( ...
        ax5, ...
        inicioPerturbacion_s, ...
        finPerturbacion_s ...
    );

    grid(ax5, 'on');

    xlabel(ax5, 'Tiempo [s]');
    ylabel(ax5, 'Momento [N·m]');
    title(ax5, 'Perturbacion contra correccion del PID');

    legend( ...
        ax5, ...
        'Momento externo', ...
        'Momento solicitado por PID', ...
        'Suma externa + PID', ...
        'Momento cero', ...
        'Inicio del pulso', ...
        'Fin del pulso', ...
        'Location', ...
        'best' ...
    );

    %% ============================================================
    % GRAFICA 6: EMPUJE DE LOS MOTORES
    % =============================================================

    ax6 = nexttile(panel, 6);

    hold(ax6, 'on');

    numeroMotores = ...
        size(empujeMotores_N, 2);

    for motor = 1:numeroMotores

        plot( ...
            ax6, ...
            tiempo_s, ...
            empujeMotores_N(:, motor), ...
            'LineWidth', ...
            1.5, ...
            'DisplayName', ...
            sprintf('Motor %d', motor) ...
        );

    end

    marcar_intervalo_perturbacion( ...
        ax6, ...
        inicioPerturbacion_s, ...
        finPerturbacion_s ...
    );

    grid(ax6, 'on');

    xlabel(ax6, 'Tiempo [s]');
    ylabel(ax6, 'Empuje [N]');
    title(ax6, 'Respuesta individual de los motores');

    legend( ...
        ax6, ...
        'Location', ...
        'best' ...
    );

    %% ============================================================
    % TITULO GENERAL
    % =============================================================

    tituloGeneral = sprintf( ...
        ['Rechazo de perturbacion en roll | ' ...
         'Desviacion maxima: %.2f grados | ' ...
         'Establecimiento: %.3f s | ' ...
         'Roll final: %.3f grados'], ...
        desviacionMaxima_deg, ...
        tiempoEstablecimiento_s, ...
        rollFinal_deg ...
    );

    title( ...
        panel, ...
        tituloGeneral, ...
        'FontWeight', ...
        'bold', ...
        'FontSize', ...
        13 ...
    );

    %% ============================================================
    % VINCULAR EJES DE TIEMPO
    % =============================================================

    linkaxes( ...
        [
            ax1
            ax2
            ax3
            ax4
            ax5
            ax6
        ], ...
        'x' ...
    );

    xlim( ...
        ax1, ...
        [
            tiempo_s(1)
            tiempo_s(end)
        ] ...
    );

end


function marcar_intervalo_perturbacion( ...
    ejeGrafica, ...
    inicioPerturbacion_s, ...
    finPerturbacion_s ...
)
%MARCAR_INTERVALO_PERTURBACION
% Dibuja líneas verticales en el inicio y final del pulso.

    xline( ...
        ejeGrafica, ...
        inicioPerturbacion_s, ...
        '--', ...
        'Inicio', ...
        'LineWidth', ...
        1.0, ...
        'LabelVerticalAlignment', ...
        'bottom' ...
    );

    xline( ...
        ejeGrafica, ...
        finPerturbacion_s, ...
        '--', ...
        'Fin', ...
        'LineWidth', ...
        1.0, ...
        'LabelVerticalAlignment', ...
        'bottom' ...
    );

end