function graficar_rechazo_perturbacion_pitch(resultadosPitch)
%GRAFICAR_RECHAZO_PERTURBACION_PITCH
% Genera las graficas de la prueba automatica de rechazo de
% perturbaciones externas en pitch.
%
% Entrada:
%
%   resultadosPitch
%       Estructura generada por:
%
%           test_rechazo_perturbacion_pitch.m
%
% Graficas:
%
%   1. Momento externo aplicado en pitch.
%   2. Pitch real contra referencia.
%   3. Error de pitch.
%   4. Velocidad angular de pitch.
%   5. Perturbacion contra correccion del PID.
%   6. Empuje individual de los cuatro motores.

    %% ============================================================
    % VALIDAR ENTRADA
    % =============================================================

    if nargin < 1

        error( ...
            "graficar_rechazo_perturbacion_pitch:FaltaEntrada", ...
            ['Debes proporcionar la estructura resultadosPitch ' ...
             'generada por la prueba de pitch.'] ...
        );

    end

    camposNecesarios = {
        'tiempo_s'
        'pitch_deg'
        'referenciaPitch_deg'
        'errorPitch_deg'
        'velocidadPitch_deg_s'
        'momentoControl_B_Nm'
        'momentoExterno_B_Nm'
        'empujeMotores_N'
        'configuracion'
        'metricas'
    };

    for k = 1:numel(camposNecesarios)

        nombreCampo = camposNecesarios{k};

        if ~isfield(resultadosPitch, nombreCampo)

            error( ...
                "graficar_rechazo_perturbacion_pitch:CampoFaltante", ...
                "Falta el campo resultadosPitch.%s.", ...
                nombreCampo ...
            );

        end

    end

    %% ============================================================
    % EXTRAER DATOS
    % =============================================================

    tiempo_s = ...
        resultadosPitch.tiempo_s;

    pitch_deg = ...
        resultadosPitch.pitch_deg;

    referenciaPitch_deg = ...
        resultadosPitch.referenciaPitch_deg;

    errorPitch_deg = ...
        resultadosPitch.errorPitch_deg;

    velocidadPitch_deg_s = ...
        resultadosPitch.velocidadPitch_deg_s;

    momentoControlPitch_Nm = ...
        resultadosPitch.momentoControl_B_Nm(:, 2);

    momentoExternoPitch_Nm = ...
        resultadosPitch.momentoExterno_B_Nm(:, 2);

    momentoResultantePitch_Nm = ...
        momentoControlPitch_Nm + ...
        momentoExternoPitch_Nm;

    empujeMotores_N = ...
        resultadosPitch.empujeMotores_N;

    inicioPerturbacion_s = ...
        resultadosPitch.configuracion.inicioPerturbacion_s;

    finPerturbacion_s = ...
        resultadosPitch.configuracion.finPerturbacion_s;

    desviacionMaxima_deg = ...
        resultadosPitch.metricas.desviacionMaxima_deg;

    tiempoEstablecimiento_s = ...
        resultadosPitch.metricas.tiempoEstablecimiento_s;

    limitePitchEstable_deg = ...
        resultadosPitch.metricas.limitePitchEstable_deg;

    pitchFinal_deg = ...
        resultadosPitch.metricas.pitchFinal_deg;

    %% ============================================================
    % VALIDAR DIMENSIONES
    % =============================================================

    numeroMuestras = ...
        numel(tiempo_s);

    if numel(pitch_deg) ~= numeroMuestras || ...
            numel(referenciaPitch_deg) ~= numeroMuestras || ...
            numel(errorPitch_deg) ~= numeroMuestras || ...
            numel(velocidadPitch_deg_s) ~= numeroMuestras

        error( ...
            "graficar_rechazo_perturbacion_pitch:DimensionesInvalidas", ...
            ['Los historiales no tienen la misma cantidad ' ...
             'de muestras que el vector de tiempo.'] ...
        );

    end

    if size(empujeMotores_N, 1) ~= numeroMuestras

        error( ...
            "graficar_rechazo_perturbacion_pitch:EmpujesInvalidos", ...
            ['El historial de motores no tiene la misma cantidad ' ...
             'de muestras que el vector de tiempo.'] ...
        );

    end

    %% ============================================================
    % CREAR FIGURA
    % =============================================================

    figura = figure( ...
        'Name', ...
        'Rechazo de perturbacion externa en pitch', ...
        'NumberTitle', ...
        'off', ...
        'Color', ...
        'w' ...
    );

    figura.Position = [
        80
        50
        1450
        850
    ];

    panel = tiledlayout( ...
        figura, ...
        3, ...
        2, ...
        'TileSpacing', ...
        'compact', ...
        'Padding', ...
        'compact' ...
    );

    %% ============================================================
    % GRAFICA 1: PERTURBACION EXTERNA
    % =============================================================

    ax1 = nexttile(panel, 1);

    hPerturbacion = plot( ...
        ax1, ...
        tiempo_s, ...
        momentoExternoPitch_Nm, ...
        'LineWidth', ...
        1.8 ...
    );

    hold(ax1, 'on');

    marcar_intervalo_perturbacion_pitch( ...
        ax1, ...
        inicioPerturbacion_s, ...
        finPerturbacion_s ...
    );

    grid(ax1, 'on');

    xlabel(ax1, 'Tiempo [s]');
    ylabel(ax1, 'M_{y,ext} [N·m]');
    title(ax1, 'Perturbacion externa aplicada');

    legend( ...
        ax1, ...
        hPerturbacion, ...
        'Momento externo en pitch', ...
        'Location', ...
        'best' ...
    );

    %% ============================================================
    % GRAFICA 2: PITCH CONTRA REFERENCIA
    % =============================================================

    ax2 = nexttile(panel, 2);

    hReferencia = plot( ...
        ax2, ...
        tiempo_s, ...
        referenciaPitch_deg, ...
        '--', ...
        'LineWidth', ...
        1.5 ...
    );

    hold(ax2, 'on');

    hPitch = plot( ...
        ax2, ...
        tiempo_s, ...
        pitch_deg, ...
        'LineWidth', ...
        1.8 ...
    );

    hLimiteSuperior = yline( ...
        ax2, ...
        limitePitchEstable_deg, ...
        ':', ...
        'LineWidth', ...
        1.0 ...
    );

    hLimiteInferior = yline( ...
        ax2, ...
        -limitePitchEstable_deg, ...
        ':', ...
        'LineWidth', ...
        1.0 ...
    );

    marcar_intervalo_perturbacion_pitch( ...
        ax2, ...
        inicioPerturbacion_s, ...
        finPerturbacion_s ...
    );

    grid(ax2, 'on');

    xlabel(ax2, 'Tiempo [s]');
    ylabel(ax2, 'Pitch [grados]');
    title(ax2, 'Respuesta angular del dron');

    legend( ...
        ax2, ...
        [ ...
            hReferencia
            hPitch
            hLimiteSuperior
            hLimiteInferior
        ], ...
        { ...
            'Referencia'
            'Pitch real'
            'Banda estable positiva'
            'Banda estable negativa'
        }, ...
        'Location', ...
        'best' ...
    );

    %% ============================================================
    % GRAFICA 3: ERROR DE PITCH
    % =============================================================

    ax3 = nexttile(panel, 3);

    hError = plot( ...
        ax3, ...
        tiempo_s, ...
        errorPitch_deg, ...
        'LineWidth', ...
        1.8 ...
    );

    hold(ax3, 'on');

    hErrorCero = yline( ...
        ax3, ...
        0, ...
        '--', ...
        'LineWidth', ...
        1.0 ...
    );

    marcar_intervalo_perturbacion_pitch( ...
        ax3, ...
        inicioPerturbacion_s, ...
        finPerturbacion_s ...
    );

    grid(ax3, 'on');

    xlabel(ax3, 'Tiempo [s]');
    ylabel(ax3, 'Error [grados]');
    title(ax3, 'Error de seguimiento en pitch');

    legend( ...
        ax3, ...
        [hError, hErrorCero], ...
        { ...
            'e_\theta = \theta_{ref} - \theta'
            'Error cero'
        }, ...
        'Location', ...
        'best' ...
    );

    %% ============================================================
    % GRAFICA 4: VELOCIDAD ANGULAR DE PITCH
    % =============================================================

    ax4 = nexttile(panel, 4);

    hVelocidad = plot( ...
        ax4, ...
        tiempo_s, ...
        velocidadPitch_deg_s, ...
        'LineWidth', ...
        1.8 ...
    );

    hold(ax4, 'on');

    hVelocidadCero = yline( ...
        ax4, ...
        0, ...
        '--', ...
        'LineWidth', ...
        1.0 ...
    );

    marcar_intervalo_perturbacion_pitch( ...
        ax4, ...
        inicioPerturbacion_s, ...
        finPerturbacion_s ...
    );

    grid(ax4, 'on');

    xlabel(ax4, 'Tiempo [s]');
    ylabel(ax4, 'q [grados/s]');
    title(ax4, 'Velocidad angular alrededor de Y_B');

    legend( ...
        ax4, ...
        [hVelocidad, hVelocidadCero], ...
        { ...
            'Velocidad angular de pitch'
            'Velocidad cero'
        }, ...
        'Location', ...
        'best' ...
    );

    %% ============================================================
    % GRAFICA 5: MOMENTOS EN PITCH
    % =============================================================

    ax5 = nexttile(panel, 5);

    hMomentoExterno = plot( ...
        ax5, ...
        tiempo_s, ...
        momentoExternoPitch_Nm, ...
        'LineWidth', ...
        1.6 ...
    );

    hold(ax5, 'on');

    hMomentoPID = plot( ...
        ax5, ...
        tiempo_s, ...
        momentoControlPitch_Nm, ...
        'LineWidth', ...
        1.8 ...
    );

    hMomentoResultante = plot( ...
        ax5, ...
        tiempo_s, ...
        momentoResultantePitch_Nm, ...
        '--', ...
        'LineWidth', ...
        1.5 ...
    );

    hMomentoCero = yline( ...
        ax5, ...
        0, ...
        ':', ...
        'LineWidth', ...
        1.0 ...
    );

    marcar_intervalo_perturbacion_pitch( ...
        ax5, ...
        inicioPerturbacion_s, ...
        finPerturbacion_s ...
    );

    grid(ax5, 'on');

    xlabel(ax5, 'Tiempo [s]');
    ylabel(ax5, 'Momento [N·m]');
    title(ax5, 'Perturbacion contra correccion del PID');

    legend( ...
        ax5, ...
        [ ...
            hMomentoExterno
            hMomentoPID
            hMomentoResultante
            hMomentoCero
        ], ...
        { ...
            'Momento externo'
            'Momento solicitado por PID'
            'Suma externa + PID'
            'Momento cero'
        }, ...
        'Location', ...
        'best' ...
    );

    %% ============================================================
    % GRAFICA 6: EMPUJE DE LOS MOTORES
    % =============================================================

    ax6 = nexttile(panel, 6);

    hold(ax6, 'on');

    numeroMotores = ...
        size(empujeMotores_N, 2);

    manejadoresMotores = gobjects( ...
        numeroMotores, ...
        1 ...
    );

    nombresMotores = cell( ...
        numeroMotores, ...
        1 ...
    );

    for motor = 1:numeroMotores

        manejadoresMotores(motor) = plot( ...
            ax6, ...
            tiempo_s, ...
            empujeMotores_N(:, motor), ...
            'LineWidth', ...
            1.5 ...
        );

        nombresMotores{motor} = ...
            sprintf('Motor %d', motor);

    end

    marcar_intervalo_perturbacion_pitch( ...
        ax6, ...
        inicioPerturbacion_s, ...
        finPerturbacion_s ...
    );

    grid(ax6, 'on');

    xlabel(ax6, 'Tiempo [s]');
    ylabel(ax6, 'Empuje [N]');
    title(ax6, 'Respuesta individual de los motores');

    legend( ...
        ax6, ...
        manejadoresMotores, ...
        nombresMotores, ...
        'Location', ...
        'best' ...
    );

    %% ============================================================
    % TITULO GENERAL
    % =============================================================

    tituloGeneral = sprintf( ...
        ['Rechazo de perturbacion en pitch | ' ...
         'Desviacion maxima: %.2f grados | ' ...
         'Establecimiento: %.3f s | ' ...
         'Pitch final: %.3f grados'], ...
        desviacionMaxima_deg, ...
        tiempoEstablecimiento_s, ...
        pitchFinal_deg ...
    );

    title( ...
        panel, ...
        tituloGeneral, ...
        'FontWeight', ...
        'bold', ...
        'FontSize', ...
        13 ...
    );

    %% ============================================================
    % VINCULAR EJES DE TIEMPO
    % =============================================================

    linkaxes( ...
        [
            ax1
            ax2
            ax3
            ax4
            ax5
            ax6
        ], ...
        'x' ...
    );

    xlim( ...
        ax1, ...
        [
            tiempo_s(1)
            tiempo_s(end)
        ] ...
    );

end


function marcar_intervalo_perturbacion_pitch( ...
    ejeGrafica, ...
    inicioPerturbacion_s, ...
    finPerturbacion_s ...
)
%MARCAR_INTERVALO_PERTURBACION_PITCH
% Marca el inicio y final de la perturbacion sin agregarlos
% a las leyendas.

    xline( ...
        ejeGrafica, ...
        inicioPerturbacion_s, ...
        '--', ...
        'Inicio', ...
        'LineWidth', ...
        1.0, ...
        'LabelVerticalAlignment', ...
        'bottom', ...
        'HandleVisibility', ...
        'off' ...
    );

    xline( ...
        ejeGrafica, ...
        finPerturbacion_s, ...
        '--', ...
        'Fin', ...
        'LineWidth', ...
        1.0, ...
        'LabelVerticalAlignment', ...
        'bottom', ...
        'HandleVisibility', ...
        'off' ...
    );

end