function D = dinamica_rotacional( ...
    x, ...
    empujeMotores_N, ...
    torqueReaccionMotores_Nm, ...
    momentoExterno_B_Nm, ...
    P, ...
    modelo)
%DINAMICA_ROTACIONAL Calcula las aceleraciones angulares del dron.
%
% Convención corporal FRD:
%   +X_B: frente
%   +Y_B: derecha
%   +Z_B: abajo
%
% Entradas:
%   x
%       Vector de 12 estados.
%
%   empujeMotores_N
%       Empuje individual de cada motor en newtons.
%       Los valores deben ser no negativos.
%
%   torqueReaccionMotores_Nm
%       Magnitud positiva del torque aerodinámico de cada rotor.
%       El signo sobre yaw se obtiene de:
%       P.motores.signoTorqueYawCuerpo
%
%   momentoExterno_B_Nm
%       Momento externo expresado en el marco corporal:
%       [Mx; My; Mz], en N*m.
%
%   P
%       Parámetros físicos.
%
%   modelo
%       Definición del vector de estados.
%
% Salida:
%   D
%       Estructura con momentos y aceleraciones angulares.

    %% Validación del vector de estados

    if numel(x) ~= modelo.numeroEstados

        error( ...
            "dinamica_rotacional:NumeroEstadosInvalido", ...
            "El vector x debe contener exactamente %d estados.", ...
            modelo.numeroEstados ...
        );

    end

    x = x(:);

    if any(~isfinite(x))

        error( ...
            "dinamica_rotacional:EstadosNoFinitos", ...
            "El vector de estados contiene NaN o valores infinitos." ...
        );

    end

    %% Número de motores

    numeroMotores = P.motores.numero;

    %% Validación de empujes

    empujeMotores_N = empujeMotores_N(:);

    if numel(empujeMotores_N) ~= numeroMotores

        error( ...
            "dinamica_rotacional:NumeroEmpujesInvalido", ...
            "Se esperaban %d valores de empuje.", ...
            numeroMotores ...
        );

    end

    if any(~isfinite(empujeMotores_N)) || ...
            any(empujeMotores_N < 0)

        error( ...
            "dinamica_rotacional:EmpujesInvalidos", ...
            [ ...
                "Los empujes deben ser valores finitos " ...
                "y no negativos." ...
            ] ...
        );

    end

    %% Validación de torques de reacción

    torqueReaccionMotores_Nm = ...
        torqueReaccionMotores_Nm(:);

    if numel(torqueReaccionMotores_Nm) ~= numeroMotores

        error( ...
            "dinamica_rotacional:NumeroTorquesInvalido", ...
            "Se esperaban %d torques de reacción.", ...
            numeroMotores ...
        );

    end

    if any(~isfinite(torqueReaccionMotores_Nm)) || ...
            any(torqueReaccionMotores_Nm < 0)

        error( ...
            "dinamica_rotacional:TorquesInvalidos", ...
            [ ...
                "Las magnitudes de torque deben ser " ...
                "finitas y no negativas." ...
            ] ...
        );

    end

    %% Validación de momento externo

    momentoExterno_B_Nm = momentoExterno_B_Nm(:);

    if numel(momentoExterno_B_Nm) ~= 3 || ...
            any(~isfinite(momentoExterno_B_Nm))

        error( ...
            "dinamica_rotacional:MomentoExternoInvalido", ...
            [ ...
                "El momento externo debe ser un vector " ...
                "finito de tres elementos." ...
            ] ...
        );

    end

    %% Tensor de inercia

    inercia_B = P.cuerpo.inercia_B;

    if ~isequal(size(inercia_B), [3, 3]) || ...
            any(~isfinite(inercia_B), "all")

        error( ...
            "dinamica_rotacional:InerciaInvalida", ...
            "El tensor de inercia debe ser una matriz 3x3 finita." ...
        );

    end

    toleranciaSimetria = 1e-12;

    if norm(inercia_B - inercia_B.', "fro") > ...
            toleranciaSimetria

        error( ...
            "dinamica_rotacional:InerciaNoSimetrica", ...
            "El tensor de inercia debe ser simétrico." ...
        );

    end

    if any(eig(inercia_B) <= 0)

        error( ...
            "dinamica_rotacional:InerciaNoPositiva", ...
            "El tensor de inercia debe ser definido positivo." ...
        );

    end

    %% Posiciones de motores

    posicionMotores_B = P.motores.posicion_B;

    if ~isequal( ...
            size(posicionMotores_B), ...
            [3, numeroMotores]) || ...
            any(~isfinite(posicionMotores_B), "all")

        error( ...
            "dinamica_rotacional:PosicionesInvalidas", ...
            "Las posiciones de motores no están correctamente definidas." ...
        );

    end

    %% Signos de torque de yaw

    signoTorqueYaw = ...
        P.motores.signoTorqueYawCuerpo(:);

    if numel(signoTorqueYaw) ~= numeroMotores || ...
            any(~ismember(signoTorqueYaw, [-1, 1]))

        error( ...
            "dinamica_rotacional:SignosYawInvalidos", ...
            [ ...
                "Los signos del torque de yaw deben contener " ...
                "exclusivamente +1 o -1." ...
            ] ...
        );

    end

    %% Velocidad angular del cuerpo

    velocidadAngular_B = [
        x(modelo.idx.p)
        x(modelo.idx.q)
        x(modelo.idx.r)
    ];

    %% Momento producido por los empujes

    momentoEmpuje_B_Nm = zeros(3, 1);

    fuerzaEmpujeMotores_B_N = ...
        zeros(3, numeroMotores);

    momentoEmpujeIndividual_B_Nm = ...
        zeros(3, numeroMotores);

    for i = 1:numeroMotores

        % El empuje actúa en dirección -Z_B.

        fuerzaRotor_B = [
            0
            0
            -empujeMotores_N(i)
        ];

        posicionRotor_B = ...
            posicionMotores_B(:, i);

        momentoRotor_B = ...
            cross(posicionRotor_B, fuerzaRotor_B);

        fuerzaEmpujeMotores_B_N(:, i) = ...
            fuerzaRotor_B;

        momentoEmpujeIndividual_B_Nm(:, i) = ...
            momentoRotor_B;

        momentoEmpuje_B_Nm = ...
            momentoEmpuje_B_Nm + momentoRotor_B;

    end

    %% Momento de reacción de yaw

    torqueYawFirmado_Nm = ...
        signoTorqueYaw .* torqueReaccionMotores_Nm;

    momentoReaccionYaw_B_Nm = [
        0
        0
        sum(torqueYawFirmado_Nm)
    ];

    %% Arrastre angular

    coefArrastreAngular = ...
        P.aerodinamica.arrastreAngular_B(:);

    if numel(coefArrastreAngular) ~= 3 || ...
            any(~isfinite(coefArrastreAngular)) || ...
            any(coefArrastreAngular < 0)

        error( ...
            "dinamica_rotacional:ArrastreAngularInvalido", ...
            [ ...
                "Los coeficientes de arrastre angular deben ser " ...
                "tres valores finitos y no negativos." ...
            ] ...
        );

    end

    momentoArrastre_B_Nm = ...
        -coefArrastreAngular .* velocidadAngular_B;

    %% Momento total

    momentoTotal_B_Nm = ...
        momentoEmpuje_B_Nm + ...
        momentoReaccionYaw_B_Nm + ...
        momentoArrastre_B_Nm + ...
        momentoExterno_B_Nm;

    %% Acoplamiento giroscópico del cuerpo rígido

    momentoAngular_B = ...
        inercia_B * velocidadAngular_B;

    terminoGiroscopico_B_Nm = ...
        cross(velocidadAngular_B, momentoAngular_B);

    %% Aceleración angular

    velocidadAngularDot_B = ...
        inercia_B \ ...
        (momentoTotal_B_Nm - terminoGiroscopico_B_Nm);

    %% Salidas

    D.velocidadAngularDot_B = ...
        velocidadAngularDot_B;

    D.momentoTotal_B_Nm = ...
        momentoTotal_B_Nm;

    D.momentoEmpuje_B_Nm = ...
        momentoEmpuje_B_Nm;

    D.momentoEmpujeIndividual_B_Nm = ...
        momentoEmpujeIndividual_B_Nm;

    D.momentoReaccionYaw_B_Nm = ...
        momentoReaccionYaw_B_Nm;

    D.momentoArrastre_B_Nm = ...
        momentoArrastre_B_Nm;

    D.momentoExterno_B_Nm = ...
        momentoExterno_B_Nm;

    D.terminoGiroscopico_B_Nm = ...
        terminoGiroscopico_B_Nm;

    D.momentoAngular_B = ...
        momentoAngular_B;

    D.fuerzaEmpujeMotores_B_N = ...
        fuerzaEmpujeMotores_B_N;

    D.torqueYawFirmado_Nm = ...
        torqueYawFirmado_Nm;

    D.velocidadAngular_B = ...
        velocidadAngular_B;

end