function [salida, memoria, D] = controlador_traslacional( ...
    referencia, ...
    x, ...
    dt, ...
    P, ...
    C, ...
    Cactitud, ...
    memoria, ...
    modelo ...
)
%CONTROLADOR_TRASLACIONAL
% Controlador exterior de movimiento del dron.
%
% Controla:
%
%   - Velocidad horizontal durante el manejo manual.
%   - Frenado horizontal al soltar los controles.
%   - Mantenimiento de posición horizontal.
%   - Referencias externas de posición.
%   - Altura absoluta.
%   - Modificación manual de altura.
%   - Velocidad vertical.
%
% Arquitectura:
%
%   Posición / velocidad / altura
%               ↓
%   CONTROLADOR_TRASLACIONAL
%               ↓
%   Roll deseado
%   Pitch deseado
%   Empuje colectivo
%               ↓
%   CONTROLADOR_ACTITUD
%               ↓
%   Mezclador
%               ↓
%   Motores
%
% La función no conoce directamente el teclado, una interfaz gráfica
% ni el ESP32. Todos ellos deben generar la misma estructura
% "referencia".
%
% ENTRADAS
%
% referencia.armado
% referencia.mandoAdelante
% referencia.mandoDerecha
% referencia.mandoAltura
% referencia.mandoYaw
%
% referencia.fijarAltura
% referencia.alturaObjetivo_m
%
% referencia.fijarPosicion
% referencia.xObjetivo_m
% referencia.yObjetivo_m
%
% x
%   Vector de 12 estados.
%
% dt
%   Paso temporal en segundos.
%
% P
%   Parámetros físicos.
%
% C
%   Parámetros del controlador traslacional.
%
% Cactitud
%   Parámetros del controlador de actitud.
%
% memoria
%   Estados internos del controlador.
%
% modelo
%   Definición e índices del modelo.
%
% SALIDAS
%
% salida.empujeTotal_N
% salida.comandoActitud
% salida.alturaObjetivo_m
% salida.posicionObjetivo_NE_m
% salida.modoHorizontal
%
% memoria
%   Memoria actualizada.
%
% D
%   Diagnóstico detallado.

    %% ============================================================
    % VALIDAR ENTRADAS
    % =============================================================

    if nargin < 8

        error( ...
            'controlador_traslacional:FaltanEntradas', ...
            ['Debes proporcionar referencia, x, dt, P, C, ' ...
             'Cactitud, memoria y modelo.'] ...
        );

    end

    if ~isstruct(referencia)

        error( ...
            'controlador_traslacional:ReferenciaInvalida', ...
            'La referencia debe ser una estructura.' ...
        );

    end

    if ~isscalar(dt) || ...
            ~isfinite(dt) || ...
            dt <= 0

        error( ...
            'controlador_traslacional:PasoInvalido', ...
            'dt debe ser positivo y finito.' ...
        );

    end

    x = x(:);

    if numel(x) ~= modelo.numeroEstados || ...
            any(~isfinite(x))

        error( ...
            'controlador_traslacional:EstadoInvalido', ...
            ['El vector de estados debe contener valores finitos ' ...
             'y tener la dimensión correcta.'] ...
        );

    end

    %% ============================================================
    % COMPLETAR REFERENCIA
    % =============================================================

    referencia.armado = obtener_campo( ...
        referencia, ...
        'armado', ...
        true ...
    );

    referencia.mandoAdelante = obtener_campo( ...
        referencia, ...
        'mandoAdelante', ...
        0 ...
    );

    referencia.mandoDerecha = obtener_campo( ...
        referencia, ...
        'mandoDerecha', ...
        0 ...
    );

    referencia.mandoAltura = obtener_campo( ...
        referencia, ...
        'mandoAltura', ...
        0 ...
    );

    referencia.mandoYaw = obtener_campo( ...
        referencia, ...
        'mandoYaw', ...
        0 ...
    );

    referencia.fijarAltura = obtener_campo( ...
        referencia, ...
        'fijarAltura', ...
        false ...
    );

    referencia.alturaObjetivo_m = obtener_campo( ...
        referencia, ...
        'alturaObjetivo_m', ...
        NaN ...
    );

    referencia.fijarPosicion = obtener_campo( ...
        referencia, ...
        'fijarPosicion', ...
        false ...
    );

    referencia.xObjetivo_m = obtener_campo( ...
        referencia, ...
        'xObjetivo_m', ...
        NaN ...
    );

    referencia.yObjetivo_m = obtener_campo( ...
        referencia, ...
        'yObjetivo_m', ...
        NaN ...
    );

    referencia.origen = obtener_campo( ...
        referencia, ...
        'origen', ...
        "REFERENCIA GENERICA" ...
    );

    %% Limitar mandos

    referencia.mandoAdelante = saturar( ...
        referencia.mandoAdelante, ...
        -1, ...
        1 ...
    );

    referencia.mandoDerecha = saturar( ...
        referencia.mandoDerecha, ...
        -1, ...
        1 ...
    );

    referencia.mandoAltura = saturar( ...
        referencia.mandoAltura, ...
        -1, ...
        1 ...
    );

    referencia.mandoYaw = saturar( ...
        referencia.mandoYaw, ...
        -1, ...
        1 ...
    );

    %% ============================================================
    % ESTADOS ACTUALES
    % =============================================================

    xN_m = ...
        x(modelo.idx.xN);

    yE_m = ...
        x(modelo.idx.yE);

    zD_m = ...
        x(modelo.idx.zD);

    alturaActual_m = ...
        -zD_m;

    phi_rad = ...
        x(modelo.idx.phi);

    theta_rad = ...
        x(modelo.idx.theta);

    psi_rad = ...
        x(modelo.idx.psi);

    K = cinematica_6dof( ...
        x, ...
        modelo ...
    );

    velocidadNED_m_s = ...
        K.posicionDot_N;

    velocidadN_m_s = ...
        velocidadNED_m_s(1);

    velocidadE_m_s = ...
        velocidadNED_m_s(2);

    velocidadDown_m_s = ...
        velocidadNED_m_s(3);

    % Positiva hacia arriba.

    velocidadUp_m_s = ...
        -velocidadDown_m_s;

    posicionActual_NE_m = [
        xN_m
        yE_m
    ];

    velocidadActual_NE_m_s = [
        velocidadN_m_s
        velocidadE_m_s
    ];

    %% ============================================================
    % INICIALIZAR MEMORIA
    % =============================================================

    memoriaInvalida = ...
        isempty(memoria) || ...
        ~isstruct(memoria) || ...
        ~isfield(memoria, 'inicializada') || ...
        ~memoria.inicializada;

    if memoriaInvalida

        memoria = struct();

        memoria.inicializada = true;

        memoria.posicionObjetivo_NE_m = ...
            posicionActual_NE_m;

        memoria.alturaObjetivo_m = saturar( ...
            alturaActual_m, ...
            C.altura.limites.alturaMinima_m, ...
            C.altura.limites.alturaMaxima_m ...
        );

        memoria.integralVelocidad_N = 0;
        memoria.integralVelocidad_E = 0;
        memoria.integralVelocidadUp = 0;

        memoria.mandoHorizontalActivoAnterior = false;

        % Esta bandera es la corrección importante.
        %
        % Solo puede volverse true cuando se detecta que un mando
        % horizontal estaba activo y acaba de soltarse.

        memoria.frenadoPendiente = false;

        memoria.tiempoFrenado_s = 0;

        memoria.posicionObjetivoExternaActiva = false;

    else

        % Compatibilidad con memorias creadas por versiones anteriores.

        if ~isfield( ...
                memoria, ...
                'mandoHorizontalActivoAnterior' ...
            )

            memoria.mandoHorizontalActivoAnterior = false;

        end

        if ~isfield( ...
                memoria, ...
                'frenadoPendiente' ...
            )

            memoria.frenadoPendiente = false;

        end

        if ~isfield( ...
                memoria, ...
                'tiempoFrenado_s' ...
            )

            memoria.tiempoFrenado_s = 0;

        end

        if ~isfield( ...
                memoria, ...
                'posicionObjetivoExternaActiva' ...
            )

            memoria.posicionObjetivoExternaActiva = false;

        end

        if ~isfield( ...
                memoria, ...
                'integralVelocidad_N' ...
            )

            memoria.integralVelocidad_N = 0;

        end

        if ~isfield( ...
                memoria, ...
                'integralVelocidad_E' ...
            )

            memoria.integralVelocidad_E = 0;

        end

        if ~isfield( ...
                memoria, ...
                'integralVelocidadUp' ...
            )

            memoria.integralVelocidadUp = 0;

        end

    end

    %% ============================================================
    % DRON DESARMADO
    % =============================================================

    if ~referencia.armado

        memoria.integralVelocidad_N = 0;
        memoria.integralVelocidad_E = 0;
        memoria.integralVelocidadUp = 0;

        memoria.posicionObjetivo_NE_m = ...
            posicionActual_NE_m;

        memoria.alturaObjetivo_m = saturar( ...
            alturaActual_m, ...
            C.altura.limites.alturaMinima_m, ...
            C.altura.limites.alturaMaxima_m ...
        );

        memoria.mandoHorizontalActivoAnterior = false;
        memoria.frenadoPendiente = false;
        memoria.tiempoFrenado_s = 0;
        memoria.posicionObjetivoExternaActiva = false;

        salida.empujeTotal_N = 0;

        salida.comandoActitud.roll = 0;
        salida.comandoActitud.pitch = 0;
        salida.comandoActitud.yaw = 0;
        salida.comandoActitud.throttle = 0;
        salida.comandoActitud.armado = false;

        salida.alturaObjetivo_m = ...
            memoria.alturaObjetivo_m;

        salida.posicionObjetivo_NE_m = ...
            memoria.posicionObjetivo_NE_m;

        salida.modoHorizontal = ...
            "DESARMADO";

        D = crear_diagnostico_desarmado( ...
            referencia, ...
            memoria, ...
            xN_m, ...
            yE_m, ...
            alturaActual_m, ...
            velocidadN_m_s, ...
            velocidadE_m_s, ...
            velocidadUp_m_s ...
        );

        return;

    end

    %% ============================================================
    % ACTUALIZAR ALTURA OBJETIVO
    % =============================================================

    if referencia.fijarAltura

        if ~isscalar(referencia.alturaObjetivo_m) || ...
                ~isfinite(referencia.alturaObjetivo_m)

            error( ...
                'controlador_traslacional:AlturaObjetivoInvalida', ...
                ['Cuando fijarAltura es true debes proporcionar ' ...
                 'una alturaObjetivo_m finita.'] ...
            );

        end

        memoria.alturaObjetivo_m = ...
            referencia.alturaObjetivo_m;

    end

    % W y S modificarán progresivamente esta referencia.

    memoria.alturaObjetivo_m = ...
        memoria.alturaObjetivo_m + ...
        referencia.mandoAltura * ...
        C.altura.mando.velocidadCambioReferencia_m_s * ...
        dt;

    memoria.alturaObjetivo_m = saturar( ...
        memoria.alturaObjetivo_m, ...
        C.altura.limites.alturaMinima_m, ...
        C.altura.limites.alturaMaxima_m ...
    );

    %% ============================================================
    % ACTUALIZAR POSICIÓN OBJETIVO EXTERNA
    % =============================================================

    if referencia.fijarPosicion

        posicionObjetivoExterna_NE_m = [
            referencia.xObjetivo_m
            referencia.yObjetivo_m
        ];

        if any(~isfinite(posicionObjetivoExterna_NE_m))

            error( ...
                'controlador_traslacional:PosicionObjetivoInvalida', ...
                ['Cuando fijarPosicion es true debes proporcionar ' ...
                 'xObjetivo_m y yObjetivo_m finitos.'] ...
            );

        end

        memoria.posicionObjetivo_NE_m = ...
            posicionObjetivoExterna_NE_m;

        memoria.posicionObjetivoExternaActiva = true;

        memoria.frenadoPendiente = false;
        memoria.tiempoFrenado_s = 0;

        memoria.integralVelocidad_N = 0;
        memoria.integralVelocidad_E = 0;

    end

    %% ============================================================
    % DETERMINAR SI EXISTE MANDO HORIZONTAL
    % =============================================================

    mandoHorizontal = [
        referencia.mandoAdelante
        referencia.mandoDerecha
    ];

    mandoHorizontalActivo = ...
        norm(mandoHorizontal) > 1e-4;

    % Detectar específicamente el instante en que se suelta.
    %
    % Primera ejecución:
    %
    %   anterior = false
    %   actual   = false
    %   acabaDeSoltar = false
    %
    % Por lo tanto, inicia correctamente en MANTENER POSICION.

    acabaDeSoltarMandoHorizontal = ...
        memoria.mandoHorizontalActivoAnterior && ...
        ~mandoHorizontalActivo;

    %% ============================================================
    % MÁQUINA DE ESTADOS DEL CONTROL HORIZONTAL
    % =============================================================

    if mandoHorizontalActivo

        %% --------------------------------------------------------
        % MODO: VELOCIDAD MANUAL
        % ---------------------------------------------------------

        modoHorizontal = ...
            "VELOCIDAD MANUAL";

        memoria.posicionObjetivoExternaActiva = false;

        memoria.frenadoPendiente = false;
        memoria.tiempoFrenado_s = 0;

        % Mientras se maneja, el punto de mantenimiento sigue
        % la posición actual.

        memoria.posicionObjetivo_NE_m = ...
            posicionActual_NE_m;

        velocidadAdelanteDeseada_m_s = ...
            referencia.mandoAdelante * ...
            C.horizontal.limites.velocidadManualMax_m_s;

        velocidadDerechaDeseada_m_s = ...
            referencia.mandoDerecha * ...
            C.horizontal.limites.velocidadManualMax_m_s;

        % Transformar referencia horizontal del cuerpo a NED.

        rotacionYaw_BodyANED = [
             cos(psi_rad), -sin(psi_rad)
             sin(psi_rad),  cos(psi_rad)
        ];

        velocidadReferencia_NE_m_s = ...
            rotacionYaw_BodyANED * [
                velocidadAdelanteDeseada_m_s
                velocidadDerechaDeseada_m_s
            ];

    else

        % Registrar una transición real de movimiento a reposo.

        if acabaDeSoltarMandoHorizontal && ...
                ~memoria.posicionObjetivoExternaActiva

            memoria.frenadoPendiente = true;
            memoria.tiempoFrenado_s = 0;

            memoria.posicionObjetivo_NE_m = ...
                posicionActual_NE_m;

        end

        if memoria.posicionObjetivoExternaActiva

            %% ----------------------------------------------------
            % MODO: POSICIÓN EXTERNA
            % -----------------------------------------------------

            modoHorizontal = ...
                "POSICION EXTERNA";

            memoria.frenadoPendiente = false;
            memoria.tiempoFrenado_s = 0;

            errorPosicion_NE_m = ...
                memoria.posicionObjetivo_NE_m - ...
                posicionActual_NE_m;

            errorPosicion_NE_m = aplicar_zona_muerta_vector( ...
                errorPosicion_NE_m, ...
                C.horizontal.mantenimiento.zonaMuertaPosicion_m ...
            );

            velocidadReferencia_NE_m_s = [
                C.horizontal.posicion.Kp_N * errorPosicion_NE_m(1)
                C.horizontal.posicion.Kp_E * errorPosicion_NE_m(2)
            ];

            velocidadReferencia_NE_m_s = limitar_norma( ...
                velocidadReferencia_NE_m_s, ...
                C.horizontal.limites.velocidadCorreccionMax_m_s ...
            );

        elseif memoria.frenadoPendiente

            %% ----------------------------------------------------
            % MODO: FRENADO
            % -----------------------------------------------------

            modoHorizontal = ...
                "FRENADO";

            % Ordenar velocidad horizontal cero.

            velocidadReferencia_NE_m_s = [
                0
                0
            ];

            % Durante el periodo breve de frenado, el punto de
            % posición acompaña al dron.
            %
            % Al terminar, queda congelado en la posición alcanzada.

            memoria.posicionObjetivo_NE_m = ...
                posicionActual_NE_m;

            memoria.tiempoFrenado_s = ...
                memoria.tiempoFrenado_s + dt;

            if memoria.tiempoFrenado_s >= ...
                    C.horizontal.mantenimiento.retardoCaptura_s

                memoria.frenadoPendiente = false;

                memoria.tiempoFrenado_s = ...
                    C.horizontal.mantenimiento.retardoCaptura_s;

                memoria.posicionObjetivo_NE_m = ...
                    posicionActual_NE_m;

            end

        else

            %% ----------------------------------------------------
            % MODO: MANTENER POSICIÓN
            % -----------------------------------------------------

            modoHorizontal = ...
                "MANTENER POSICION";

            errorPosicion_NE_m = ...
                memoria.posicionObjetivo_NE_m - ...
                posicionActual_NE_m;

            errorPosicion_NE_m = aplicar_zona_muerta_vector( ...
                errorPosicion_NE_m, ...
                C.horizontal.mantenimiento.zonaMuertaPosicion_m ...
            );

            velocidadReferencia_NE_m_s = [
                C.horizontal.posicion.Kp_N * errorPosicion_NE_m(1)
                C.horizontal.posicion.Kp_E * errorPosicion_NE_m(2)
            ];

            velocidadReferencia_NE_m_s = limitar_norma( ...
                velocidadReferencia_NE_m_s, ...
                C.horizontal.limites.velocidadCorreccionMax_m_s ...
            );

        end

    end

    % Guardar el estado para detectar una liberación en el
    % siguiente paso.

    memoria.mandoHorizontalActivoAnterior = ...
        mandoHorizontalActivo;

    %% ============================================================
    % CONTROL HORIZONTAL DE VELOCIDAD
    % =============================================================

    errorVelocidad_NE_m_s = ...
        velocidadReferencia_NE_m_s - ...
        velocidadActual_NE_m_s;

    errorVelocidad_NE_m_s = aplicar_zona_muerta_vector( ...
        errorVelocidad_NE_m_s, ...
        C.horizontal.mantenimiento.zonaMuertaVelocidad_m_s ...
    );

    integralAnterior_NE = [
        memoria.integralVelocidad_N
        memoria.integralVelocidad_E
    ];

    integralCandidata_NE = ...
        integralAnterior_NE + ...
        errorVelocidad_NE_m_s * dt;

    integralCandidata_NE(1) = saturar( ...
        integralCandidata_NE(1), ...
        -C.horizontal.limites.integralVelocidad_N_max, ...
         C.horizontal.limites.integralVelocidad_N_max ...
    );

    integralCandidata_NE(2) = saturar( ...
        integralCandidata_NE(2), ...
        -C.horizontal.limites.integralVelocidad_E_max, ...
         C.horizontal.limites.integralVelocidad_E_max ...
    );

    aceleracionHorizontalSinSaturar_NE_m_s2 = [
        C.horizontal.velocidad.Kp_N * errorVelocidad_NE_m_s(1) + ...
        C.horizontal.velocidad.Ki_N * integralCandidata_NE(1)

        C.horizontal.velocidad.Kp_E * errorVelocidad_NE_m_s(2) + ...
        C.horizontal.velocidad.Ki_E * integralCandidata_NE(2)
    ];

    aceleracionHorizontalDeseada_NE_m_s2 = limitar_norma( ...
        aceleracionHorizontalSinSaturar_NE_m_s2, ...
        C.horizontal.limites.aceleracionMax_m_s2 ...
    );

    saturacionHorizontal = ...
        norm( ...
            aceleracionHorizontalDeseada_NE_m_s2 - ...
            aceleracionHorizontalSinSaturar_NE_m_s2 ...
        ) > 1e-12;

    if saturacionHorizontal

        % Anti-windup.

        integralNueva_NE = ...
            integralAnterior_NE;

        aceleracionHorizontalSinSaturar_NE_m_s2 = [
            C.horizontal.velocidad.Kp_N * errorVelocidad_NE_m_s(1) + ...
            C.horizontal.velocidad.Ki_N * integralNueva_NE(1)

            C.horizontal.velocidad.Kp_E * errorVelocidad_NE_m_s(2) + ...
            C.horizontal.velocidad.Ki_E * integralNueva_NE(2)
        ];

        aceleracionHorizontalDeseada_NE_m_s2 = limitar_norma( ...
            aceleracionHorizontalSinSaturar_NE_m_s2, ...
            C.horizontal.limites.aceleracionMax_m_s2 ...
        );

    else

        integralNueva_NE = ...
            integralCandidata_NE;

    end

    memoria.integralVelocidad_N = ...
        integralNueva_NE(1);

    memoria.integralVelocidad_E = ...
        integralNueva_NE(2);

    %% ============================================================
    % CONVERTIR ACELERACIÓN EN ROLL Y PITCH
    % =============================================================

    aceleracionN_m_s2 = ...
        aceleracionHorizontalDeseada_NE_m_s2(1);

    aceleracionE_m_s2 = ...
        aceleracionHorizontalDeseada_NE_m_s2(2);

    % NED horizontal a adelante/derecha del dron.

    aceleracionAdelante_m_s2 = ...
        cos(psi_rad) * aceleracionN_m_s2 + ...
        sin(psi_rad) * aceleracionE_m_s2;

    aceleracionDerecha_m_s2 = ...
        -sin(psi_rad) * aceleracionN_m_s2 + ...
         cos(psi_rad) * aceleracionE_m_s2;

    gravedad_m_s2 = ...
        P.entorno.g;

    % Convenciones FRD/NED:
    %
    % pitch negativo -> acelera hacia adelante
    % roll positivo  -> acelera hacia la derecha

    thetaReferencia_rad = ...
        -atan2( ...
            aceleracionAdelante_m_s2, ...
            gravedad_m_s2 ...
        );

    phiReferencia_rad = ...
        atan2( ...
            aceleracionDerecha_m_s2, ...
            gravedad_m_s2 ...
        );

    phiReferencia_rad = saturar( ...
        phiReferencia_rad, ...
        -C.limites.anguloHorizontalMax_rad, ...
         C.limites.anguloHorizontalMax_rad ...
    );

    thetaReferencia_rad = saturar( ...
        thetaReferencia_rad, ...
        -C.limites.anguloHorizontalMax_rad, ...
         C.limites.anguloHorizontalMax_rad ...
    );

    %% Comandos normalizados para controlador_actitud

    comandoRollNormalizado = ...
        phiReferencia_rad / ...
        Cactitud.limites.anguloRollMax_rad;

    % controlador_actitud usa:
    %
    % thetaReferencia =
    %     -comando.pitch * anguloPitchMax

    comandoPitchNormalizado = ...
        -thetaReferencia_rad / ...
        Cactitud.limites.anguloPitchMax_rad;

    comandoRollNormalizado = saturar( ...
        comandoRollNormalizado, ...
        -1, ...
        1 ...
    );

    comandoPitchNormalizado = saturar( ...
        comandoPitchNormalizado, ...
        -1, ...
        1 ...
    );

    %% ============================================================
    % CONTROL DE ALTURA
    % =============================================================

    errorAltura_m = ...
        memoria.alturaObjetivo_m - ...
        alturaActual_m;

    if abs(errorAltura_m) < ...
            C.altura.limites.toleranciaAltura_m

        errorAlturaParaControl_m = 0;

    else

        errorAlturaParaControl_m = ...
            errorAltura_m;

    end

    velocidadUpReferencia_m_s = ...
        C.altura.posicion.Kp * ...
        errorAlturaParaControl_m;

    velocidadUpReferencia_m_s = saturar( ...
        velocidadUpReferencia_m_s, ...
        -C.altura.limites.velocidadBajadaMax_m_s, ...
         C.altura.limites.velocidadSubidaMax_m_s ...
    );

    errorVelocidadUp_m_s = ...
        velocidadUpReferencia_m_s - ...
        velocidadUp_m_s;

    if abs(errorVelocidadUp_m_s) < ...
            C.altura.limites.toleranciaVelocidad_m_s

        errorVelocidadUpParaControl_m_s = 0;

    else

        errorVelocidadUpParaControl_m_s = ...
            errorVelocidadUp_m_s;

    end

    integralVelocidadUpAnterior = ...
        memoria.integralVelocidadUp;

    integralVelocidadUpCandidata = ...
        integralVelocidadUpAnterior + ...
        errorVelocidadUpParaControl_m_s * dt;

    integralVelocidadUpCandidata = saturar( ...
        integralVelocidadUpCandidata, ...
        -C.altura.limites.integralVelocidadMax, ...
         C.altura.limites.integralVelocidadMax ...
    );

    aceleracionUpSinSaturar_m_s2 = ...
        C.altura.velocidad.Kp * ...
        errorVelocidadUpParaControl_m_s + ...
        C.altura.velocidad.Ki * ...
        integralVelocidadUpCandidata;

    aceleracionUpDeseada_m_s2 = saturar( ...
        aceleracionUpSinSaturar_m_s2, ...
        -C.altura.limites.aceleracionBajadaMax_m_s2, ...
         C.altura.limites.aceleracionSubidaMax_m_s2 ...
    );

    saturacionAceleracionVertical = ...
        abs( ...
            aceleracionUpDeseada_m_s2 - ...
            aceleracionUpSinSaturar_m_s2 ...
        ) > 1e-12;

    if saturacionAceleracionVertical

        integralVelocidadUpNueva = ...
            integralVelocidadUpAnterior;

        aceleracionUpSinSaturar_m_s2 = ...
            C.altura.velocidad.Kp * ...
            errorVelocidadUpParaControl_m_s + ...
            C.altura.velocidad.Ki * ...
            integralVelocidadUpNueva;

        aceleracionUpDeseada_m_s2 = saturar( ...
            aceleracionUpSinSaturar_m_s2, ...
            -C.altura.limites.aceleracionBajadaMax_m_s2, ...
             C.altura.limites.aceleracionSubidaMax_m_s2 ...
        );

    else

        integralVelocidadUpNueva = ...
            integralVelocidadUpCandidata;

    end

    %% Empuje vertical requerido

    masa_kg = ...
        P.cuerpo.masa;

    empujeVerticalDeseado_N = ...
        masa_kg * ...
        (gravedad_m_s2 + aceleracionUpDeseada_m_s2);

    empujeVerticalDeseado_N = max( ...
        0, ...
        empujeVerticalDeseado_N ...
    );

    %% Compensar la inclinación actual

    factorVertical = ...
        cos(phi_rad) * ...
        cos(theta_rad);

    factorVertical = max( ...
        factorVertical, ...
        0.35 ...
    );

    empujeTotalSinSaturar_N = ...
        empujeVerticalDeseado_N / ...
        factorVertical;

    empujeTotal_N = saturar( ...
        empujeTotalSinSaturar_N, ...
        C.empuje.minimoTotal_N, ...
        C.empuje.maximoControl_N ...
    );

    saturacionEmpuje = ...
        abs( ...
            empujeTotal_N - ...
            empujeTotalSinSaturar_N ...
        ) > 1e-12;

    if saturacionEmpuje

        memoria.integralVelocidadUp = ...
            integralVelocidadUpAnterior;

    else

        memoria.integralVelocidadUp = ...
            integralVelocidadUpNueva;

    end

    %% ============================================================
    % SALIDA HACIA EL CONTROLADOR DE ACTITUD
    % =============================================================

    salida.comandoActitud.roll = ...
        comandoRollNormalizado;

    salida.comandoActitud.pitch = ...
        comandoPitchNormalizado;

    salida.comandoActitud.yaw = ...
        referencia.mandoYaw;

    salida.comandoActitud.throttle = ...
        empujeTotal_N / ...
        C.empuje.maximoTotal_N;

    salida.comandoActitud.armado = ...
        true;

    salida.empujeTotal_N = ...
        empujeTotal_N;

    salida.alturaObjetivo_m = ...
        memoria.alturaObjetivo_m;

    salida.posicionObjetivo_NE_m = ...
        memoria.posicionObjetivo_NE_m;

    salida.modoHorizontal = ...
        modoHorizontal;

    %% ============================================================
    % DIAGNÓSTICO
    % =============================================================

    D.origen = ...
        string(referencia.origen);

    D.modoHorizontal = ...
        modoHorizontal;

    D.estado.posicion_NE_m = ...
        posicionActual_NE_m;

    D.estado.altura_m = ...
        alturaActual_m;

    D.estado.velocidad_NE_m_s = ...
        velocidadActual_NE_m_s;

    D.estado.velocidadUp_m_s = ...
        velocidadUp_m_s;

    D.referencia.posicion_NE_m = ...
        memoria.posicionObjetivo_NE_m;

    D.referencia.altura_m = ...
        memoria.alturaObjetivo_m;

    D.referencia.velocidad_NE_m_s = ...
        velocidadReferencia_NE_m_s;

    D.referencia.velocidadUp_m_s = ...
        velocidadUpReferencia_m_s;

    D.error.posicion_NE_m = ...
        memoria.posicionObjetivo_NE_m - ...
        posicionActual_NE_m;

    D.error.altura_m = ...
        errorAltura_m;

    D.error.velocidad_NE_m_s = ...
        errorVelocidad_NE_m_s;

    D.error.velocidadUp_m_s = ...
        errorVelocidadUp_m_s;

    D.salida.aceleracionHorizontal_NE_m_s2 = ...
        aceleracionHorizontalDeseada_NE_m_s2;

    D.salida.aceleracionUp_m_s2 = ...
        aceleracionUpDeseada_m_s2;

    D.salida.phiReferencia_rad = ...
        phiReferencia_rad;

    D.salida.thetaReferencia_rad = ...
        thetaReferencia_rad;

    D.salida.empujeVerticalDeseado_N = ...
        empujeVerticalDeseado_N;

    D.salida.empujeTotalSinSaturar_N = ...
        empujeTotalSinSaturar_N;

    D.salida.empujeTotal_N = ...
        empujeTotal_N;

    D.integrales.velocidad_N = ...
        memoria.integralVelocidad_N;

    D.integrales.velocidad_E = ...
        memoria.integralVelocidad_E;

    D.integrales.velocidadUp = ...
        memoria.integralVelocidadUp;

    D.saturacion.horizontal = ...
        saturacionHorizontal;

    D.saturacion.aceleracionVertical = ...
        saturacionAceleracionVertical;

    D.saturacion.empuje = ...
        saturacionEmpuje;

    D.estadoInterno.mandoHorizontalActivo = ...
        mandoHorizontalActivo;

    D.estadoInterno.mandoHorizontalActivoAnterior = ...
        memoria.mandoHorizontalActivoAnterior;

    D.estadoInterno.acabaDeSoltarMandoHorizontal = ...
        acabaDeSoltarMandoHorizontal;

    D.estadoInterno.frenadoPendiente = ...
        memoria.frenadoPendiente;

    D.estadoInterno.tiempoFrenado_s = ...
        memoria.tiempoFrenado_s;

end


function valor = obtener_campo( ...
    estructura, ...
    nombreCampo, ...
    valorPredeterminado ...
)
%OBTENER_CAMPO Devuelve un campo o un valor predeterminado.

    if isfield(estructura, nombreCampo)

        valor = ...
            estructura.(nombreCampo);

    else

        valor = ...
            valorPredeterminado;

    end

end


function valorSaturado = saturar( ...
    valor, ...
    limiteInferior, ...
    limiteSuperior ...
)
%SATURAR Limita un escalar.

    if ~isscalar(valor) || ...
            ~isfinite(valor)

        error( ...
            'controlador_traslacional:ValorNoFinito', ...
            'El valor que se desea saturar debe ser escalar y finito.' ...
        );

    end

    valorSaturado = max( ...
        limiteInferior, ...
        min(limiteSuperior, valor) ...
    );

end


function vectorLimitado = limitar_norma( ...
    vector, ...
    normaMaxima ...
)
%LIMITAR_NORMA Limita la magnitud sin modificar la dirección.

    vector = ...
        vector(:);

    magnitud = ...
        norm(vector);

    if magnitud > normaMaxima && ...
            magnitud > 0

        vectorLimitado = ...
            vector * ...
            (normaMaxima / magnitud);

    else

        vectorLimitado = ...
            vector;

    end

end


function vectorSalida = aplicar_zona_muerta_vector( ...
    vectorEntrada, ...
    limite ...
)
%APLICAR_ZONA_MUERTA_VECTOR
% Convierte en cero los componentes pequeños.

    vectorSalida = ...
        vectorEntrada(:);

    vectorSalida( ...
        abs(vectorSalida) < limite ...
    ) = 0;

end


function D = crear_diagnostico_desarmado( ...
    referencia, ...
    memoria, ...
    xN_m, ...
    yE_m, ...
    alturaActual_m, ...
    velocidadN_m_s, ...
    velocidadE_m_s, ...
    velocidadUp_m_s ...
)
%CREAR_DIAGNOSTICO_DESARMADO

    D.origen = ...
        string(referencia.origen);

    D.modoHorizontal = ...
        "DESARMADO";

    D.estado.posicion_NE_m = [
        xN_m
        yE_m
    ];

    D.estado.altura_m = ...
        alturaActual_m;

    D.estado.velocidad_NE_m_s = [
        velocidadN_m_s
        velocidadE_m_s
    ];

    D.estado.velocidadUp_m_s = ...
        velocidadUp_m_s;

    D.referencia.posicion_NE_m = ...
        memoria.posicionObjetivo_NE_m;

    D.referencia.altura_m = ...
        memoria.alturaObjetivo_m;

    D.referencia.velocidad_NE_m_s = ...
        zeros(2, 1);

    D.referencia.velocidadUp_m_s = ...
        0;

    D.error.posicion_NE_m = ...
        zeros(2, 1);

    D.error.altura_m = ...
        0;

    D.error.velocidad_NE_m_s = ...
        zeros(2, 1);

    D.error.velocidadUp_m_s = ...
        0;

    D.salida.aceleracionHorizontal_NE_m_s2 = ...
        zeros(2, 1);

    D.salida.aceleracionUp_m_s2 = ...
        0;

    D.salida.phiReferencia_rad = ...
        0;

    D.salida.thetaReferencia_rad = ...
        0;

    D.salida.empujeVerticalDeseado_N = ...
        0;

    D.salida.empujeTotalSinSaturar_N = ...
        0;

    D.salida.empujeTotal_N = ...
        0;

    D.integrales.velocidad_N = ...
        0;

    D.integrales.velocidad_E = ...
        0;

    D.integrales.velocidadUp = ...
        0;

    D.saturacion.horizontal = ...
        false;

    D.saturacion.aceleracionVertical = ...
        false;

    D.saturacion.empuje = ...
        false;

    D.estadoInterno.mandoHorizontalActivo = ...
        false;

    D.estadoInterno.mandoHorizontalActivoAnterior = ...
        false;

    D.estadoInterno.acabaDeSoltarMandoHorizontal = ...
        false;

    D.estadoInterno.frenadoPendiente = ...
        false;

    D.estadoInterno.tiempoFrenado_s = ...
        0;

end