function C = parametros_control_actitud(P)
%PARAMETROS_CONTROL_ACTITUD Genera los parámetros del controlador.
%
% Las ganancias se calculan con las inercias del caso cargado:
%
%   Kp = I * wn^2
%   Kd = 2*zeta*I*wn
%
% Para roll y pitch se controla el ángulo.
% Para yaw se controla la velocidad angular.
%
% Cuando están disponibles los límites reales de empuje, los
% momentos máximos se calculan a partir de la autoridad física
% disponible alrededor del empuje de hover.
%
% Por tanto, esta función funciona tanto con:
%
%   - caso_base_teorico
%   - caso_real_dron

    %% ============================================================
    % VALIDAR PARÁMETROS
    % =============================================================

    if ~isfield(P, 'cuerpo') || ...
            ~isfield(P.cuerpo, 'inercia_B') || ...
            ~isfield(P.cuerpo, 'masa')

        error( ...
            'parametros_control_actitud:ParametrosInvalidos', ...
            'P debe contener masa e inercia del cuerpo.' ...
        );

    end

    if ~isfield(P, 'entorno') || ...
            ~isfield(P.entorno, 'g')

        error( ...
            'parametros_control_actitud:FaltaGravedad', ...
            'P debe contener P.entorno.g.' ...
        );

    end

    if ~isfield(P, 'motores') || ...
            ~isfield(P.motores, 'posicion_B') || ...
            ~isfield(P.motores, 'numero')

        error( ...
            'parametros_control_actitud:FaltaGeometria', ...
            'P debe contener la geometria de los motores.' ...
        );

    end

    inercia = ...
        P.cuerpo.inercia_B;

    masa = ...
        P.cuerpo.masa;

    g = ...
        P.entorno.g;

    Ixx = ...
        inercia(1, 1);

    Iyy = ...
        inercia(2, 2);

    Izz = ...
        inercia(3, 3);

    valoresFisicos = [
        masa
        g
        Ixx
        Iyy
        Izz
    ];

    if any(~isfinite(valoresFisicos)) || ...
            any(valoresFisicos <= 0)

        error( ...
            'parametros_control_actitud:ValoresInvalidos', ...
            ['La masa, gravedad e inercias principales deben ' ...
             'ser positivas y finitas.'] ...
        );

    end

    %% ============================================================
    % INFORMACIÓN
    % =============================================================

    C.meta.nombre = ...
        "Controlador de actitud escalado al modelo fisico";

    C.meta.version = ...
        "1.0";

    C.meta.estado = ...
        "PARAMETRIZADO";

    %% ============================================================
    % LÍMITES DE REFERENCIAS
    % =============================================================

    C.limites.anguloRollMax_rad = ...
        deg2rad(25);

    C.limites.anguloPitchMax_rad = ...
        deg2rad(25);

    C.limites.velocidadYawMax_rad_s = ...
        deg2rad(90);

    %% ============================================================
    % DISEÑO DE ROLL Y PITCH
    % =============================================================

    frecuenciaNaturalRollPitch_rad_s = ...
        4.5;

    amortiguamientoRollPitch = ...
        0.90;

    %% Roll

    C.roll.Kp = ...
        Ixx * ...
        frecuenciaNaturalRollPitch_rad_s^2;

    C.roll.Kd = ...
        2 * ...
        amortiguamientoRollPitch * ...
        Ixx * ...
        frecuenciaNaturalRollPitch_rad_s;

    % Integral pequeña para eliminar errores persistentes sin
    % dominar la respuesta transitoria.

    C.roll.Ki = ...
        0.10 * C.roll.Kp;

    %% Pitch

    C.pitch.Kp = ...
        Iyy * ...
        frecuenciaNaturalRollPitch_rad_s^2;

    C.pitch.Kd = ...
        2 * ...
        amortiguamientoRollPitch * ...
        Iyy * ...
        frecuenciaNaturalRollPitch_rad_s;

    C.pitch.Ki = ...
        0.10 * C.pitch.Kp;

    %% ============================================================
    % CONTROL DE VELOCIDAD DE YAW
    % =============================================================

    frecuenciaNaturalYaw_rad_s = ...
        3.5;

    amortiguamientoYaw = ...
        1.0;

    % El lazo de yaw actual controla velocidad angular.
    %
    % Por eso su estructura se comporta como un PI sobre r.

    C.yaw.Kp = ...
        2 * ...
        amortiguamientoYaw * ...
        Izz * ...
        frecuenciaNaturalYaw_rad_s;

    C.yaw.Ki = ...
        Izz * ...
        frecuenciaNaturalYaw_rad_s^2;

    C.yaw.Kd = ...
        0;

    %% ============================================================
    % LÍMITES DE INTEGRADORES
    % =============================================================

    C.limites.integralRollMax = ...
        0.35;

    C.limites.integralPitchMax = ...
        0.35;

    C.limites.integralYawMax = ...
        0.50;

    %% ============================================================
    % CALCULAR AUTORIDAD FÍSICA DE LOS MOTORES
    % =============================================================

    posicionesMotores_B = ...
        P.motores.posicion_B;

    numeroMotores = ...
        P.motores.numero;

    empujeHoverTotal_N = ...
        masa * g;

    empujeHoverPorMotor_N = ...
        empujeHoverTotal_N / numeroMotores;

    usarLimitesFisicos = ...
        isfield(P.motores, 'empujeMinimo') && ...
        isfield(P.motores, 'empujeMaximo') && ...
        all(isfinite(P.motores.empujeMinimo)) && ...
        all(isfinite(P.motores.empujeMaximo));

    if usarLimitesFisicos

        empujeMinimo_N = ...
            expandir_vector_motor( ...
                P.motores.empujeMinimo, ...
                numeroMotores ...
            );

        empujeMaximo_N = ...
            expandir_vector_motor( ...
                P.motores.empujeMaximo, ...
                numeroMotores ...
            );

        if any(empujeMaximo_N <= empujeMinimo_N)

            error( ...
                'parametros_control_actitud:LimitesMotorInvalidos', ...
                ['Cada empuje maximo debe ser mayor que su ' ...
                 'correspondiente empuje minimo.'] ...
            );

        end

        if any( ...
                empujeHoverPorMotor_N < empujeMinimo_N | ...
                empujeHoverPorMotor_N > empujeMaximo_N ...
            )

            error( ...
                'parametros_control_actitud:HoverImposible', ...
                ['El empuje necesario para hover queda fuera ' ...
                 'de los limites definidos de los motores.'] ...
            );

        end

        % Para mantener aproximadamente el mismo empuje total:
        %
        % unos motores aumentan deltaT y otros disminuyen deltaT.
        %
        % deltaT debe respetar tanto el margen superior como el
        % margen inferior de cada motor.

        margenSubida_N = ...
            empujeMaximo_N - ...
            empujeHoverPorMotor_N;

        margenBajada_N = ...
            empujeHoverPorMotor_N - ...
            empujeMinimo_N;

        variacionSimetricaMaxima_N = ...
            min( ...
                margenSubida_N, ...
                margenBajada_N ...
            );

        variacionSimetricaMaxima_N = ...
            max( ...
                0, ...
                variacionSimetricaMaxima_N ...
            );

        xMotores_m = ...
            posicionesMotores_B(1, :).';

        yMotores_m = ...
            posicionesMotores_B(2, :).';

        % Autoridad aproximada:
        %
        % Mx = sum(-y_i * deltaT_i)
        % My = sum( x_i * deltaT_i)

        autoridadRoll_Nm = sum( ...
            abs(yMotores_m) .* ...
            variacionSimetricaMaxima_N ...
        );

        autoridadPitch_Nm = sum( ...
            abs(xMotores_m) .* ...
            variacionSimetricaMaxima_N ...
        );

        % Se utiliza solamente el 85 % para dejar un margen y evitar
        % que el controlador trabaje pegado a la saturación.

        factorSeguridadAutoridad = ...
            0.85;

        C.limites.momentoRollMax_Nm = ...
            factorSeguridadAutoridad * ...
            autoridadRoll_Nm;

        C.limites.momentoPitchMax_Nm = ...
            factorSeguridadAutoridad * ...
            autoridadPitch_Nm;

        %% Autoridad aproximada de yaw

        puedeCalcularYawFisico = ...
            isfield(P, 'helices') && ...
            isfield(P.helices, 'kT') && ...
            isfield(P.helices, 'kQ') && ...
            isfield(P.motores, 'signoTorqueYawCuerpo') && ...
            all(isfinite(P.helices.kT)) && ...
            all(isfinite(P.helices.kQ)) && ...
            all(P.helices.kT > 0) && ...
            all(P.helices.kQ > 0) && ...
            all(isfinite(P.motores.signoTorqueYawCuerpo));

        if puedeCalcularYawFisico

            kT = ...
                expandir_vector_motor( ...
                    P.helices.kT, ...
                    numeroMotores ...
                );

            kQ = ...
                expandir_vector_motor( ...
                    P.helices.kQ, ...
                    numeroMotores ...
                );

            signoYaw = ...
                expandir_vector_motor( ...
                    P.motores.signoTorqueYawCuerpo, ...
                    numeroMotores ...
                );

            % Como:
            %
            % T = kT*w^2
            % Q = kQ*w^2
            %
            % entonces:
            %
            % Q = (kQ/kT)*T

            relacionTorqueEmpuje_m = ...
                kQ ./ kT;

            coeficienteYaw_m = ...
                signoYaw .* ...
                relacionTorqueEmpuje_m;

            autoridadYaw_Nm = sum( ...
                abs(coeficienteYaw_m) .* ...
                variacionSimetricaMaxima_N ...
            );

            C.limites.momentoYawMax_Nm = ...
                factorSeguridadAutoridad * ...
                autoridadYaw_Nm;

            metodoLimites = ...
                "AUTORIDAD FISICA DE MOTORES";

        else

            % Respaldo para casos donde todavía no se conocen kT y kQ.

            C.limites.momentoYawMax_Nm = ...
                0.08;

            autoridadYaw_Nm = ...
                NaN;

            metodoLimites = ...
                "ROLL/PITCH FISICOS, YAW PROVISIONAL";

        end

    else

        %% Respaldo para el caso teórico sin límites de motor

        brazoRoll_m = ...
            max( ...
                abs(posicionesMotores_B(2, :)) ...
            );

        brazoPitch_m = ...
            max( ...
                abs(posicionesMotores_B(1, :)) ...
            );

        C.limites.momentoRollMax_Nm = max( ...
            0.05, ...
            0.35 * ...
            masa * ...
            g * ...
            brazoRoll_m ...
        );

        C.limites.momentoPitchMax_Nm = max( ...
            0.05, ...
            0.35 * ...
            masa * ...
            g * ...
            brazoPitch_m ...
        );

        C.limites.momentoYawMax_Nm = ...
            0.08;

        empujeMinimo_N = ...
            NaN(numeroMotores, 1);

        empujeMaximo_N = ...
            NaN(numeroMotores, 1);

        margenSubida_N = ...
            NaN(numeroMotores, 1);

        margenBajada_N = ...
            NaN(numeroMotores, 1);

        variacionSimetricaMaxima_N = ...
            NaN(numeroMotores, 1);

        autoridadRoll_Nm = ...
            NaN;

        autoridadPitch_Nm = ...
            NaN;

        autoridadYaw_Nm = ...
            NaN;

        metodoLimites = ...
            "LIMITES PROVISIONALES DEL CASO TEORICO";

    end

    %% ============================================================
    % VERIFICAR LÍMITES OBTENIDOS
    % =============================================================

    momentosMaximos = [
        C.limites.momentoRollMax_Nm
        C.limites.momentoPitchMax_Nm
        C.limites.momentoYawMax_Nm
    ];

    if any(~isfinite(momentosMaximos)) || ...
            any(momentosMaximos <= 0)

        error( ...
            'parametros_control_actitud:AutoridadInvalida', ...
            ['Los limites de momento calculados deben ser ' ...
             'positivos y finitos.'] ...
        );

    end

    %% ============================================================
    % INFORMACIÓN DE DISEÑO Y DIAGNÓSTICO
    % =============================================================

    C.diseno.frecuenciaNaturalRollPitch_rad_s = ...
        frecuenciaNaturalRollPitch_rad_s;

    C.diseno.amortiguamientoRollPitch = ...
        amortiguamientoRollPitch;

    C.diseno.frecuenciaNaturalYaw_rad_s = ...
        frecuenciaNaturalYaw_rad_s;

    C.diseno.amortiguamientoYaw = ...
        amortiguamientoYaw;

    C.autoridad.metodo = ...
        metodoLimites;

    C.autoridad.empujeHoverTotal_N = ...
        empujeHoverTotal_N;

    C.autoridad.empujeHoverPorMotor_N = ...
        empujeHoverPorMotor_N;

    C.autoridad.empujeMinimo_N = ...
        empujeMinimo_N;

    C.autoridad.empujeMaximo_N = ...
        empujeMaximo_N;

    C.autoridad.margenSubida_N = ...
        margenSubida_N;

    C.autoridad.margenBajada_N = ...
        margenBajada_N;

    C.autoridad.variacionSimetricaMaxima_N = ...
        variacionSimetricaMaxima_N;

    C.autoridad.rollDisponible_Nm = ...
        autoridadRoll_Nm;

    C.autoridad.pitchDisponible_Nm = ...
        autoridadPitch_Nm;

    C.autoridad.yawDisponible_Nm = ...
        autoridadYaw_Nm;

end


function vectorExpandido = expandir_vector_motor( ...
    valor, ...
    numeroMotores ...
)
%EXPANDIR_VECTOR_MOTOR Convierte un escalar o vector a columna N×1.

    valor = ...
        valor(:);

    if isscalar(valor)

        vectorExpandido = ...
            repmat( ...
                valor, ...
                numeroMotores, ...
                1 ...
            );

    elseif numel(valor) == numeroMotores

        vectorExpandido = ...
            valor;

    else

        error( ...
            'parametros_control_actitud:DimensionMotorInvalida', ...
            ['El parametro debe ser escalar o contener un ' ...
             'valor por cada motor.'] ...
        );

    end

end