%% TEST_DINAMICA_ROTACIONAL
% Comprueba momentos de roll, pitch, yaw, momentos externos,
% acoplamiento giroscópico y arrastre angular.

clearvars;
clc;

fprintf("================================================\n");
fprintf("        PRUEBAS DE DINÁMICA ROTACIONAL\n");
fprintf("================================================\n\n");

%% Preparación del caso numérico

modelo = definicion_modelo();

P = parametros_fisicos();
R = reglas_competencia();
Dproyecto = requisitos_proyecto(R);
C = parametros_diseno();

[P, C, casoBase] = ...
    caso_base_teorico(P, C, R);

G = configuracion_motores_x( ...
    R, ...
    Dproyecto, ...
    C.geometria.distanciaCentroMotor, ...
    C.geometria.zMotor_B ...
);

P = aplicar_configuracion_motores(P, G);

tolerancia = 1e-10;

x = zeros(modelo.numeroEstados, 1);

momentoExternoCero = zeros(3, 1);
torqueReaccionCero = zeros(4, 1);

I = P.cuerpo.inercia_B;

a = G.componenteDiagonal;


%% PRUEBA 1
% Empujes iguales y torques de yaw iguales.
%
% Por simetría, el momento total debe ser cero.

empujeMotores = ones(4, 1);

torqueReaccionMotores = ...
    0.01 * ones(4, 1);

resultado = dinamica_rotacional( ...
    x, ...
    empujeMotores, ...
    torqueReaccionMotores, ...
    momentoExternoCero, ...
    P, ...
    modelo ...
);

assert( ...
    norm(resultado.momentoTotal_B_Nm) < tolerancia, ...
    "Prueba 1 falló: el momento total simétrico no es cero." ...
);

assert( ...
    norm(resultado.velocidadAngularDot_B) < tolerancia, ...
    "Prueba 1 falló: existe aceleración angular en equilibrio." ...
);

fprintf("Prueba 1 aprobada: equilibrio rotacional simétrico.\n");


%% PRUEBA 2
% Roll positivo.
%
% Se aplica empuje en los motores izquierdos:
% M1 y M4.
%
% tau_x = 2*a*T

empujePrueba = 1.0;

empujeMotores = [
    empujePrueba
    0
    0
    empujePrueba
];

resultado = dinamica_rotacional( ...
    x, ...
    empujeMotores, ...
    torqueReaccionCero, ...
    momentoExternoCero, ...
    P, ...
    modelo ...
);

momentoEsperado = [
    2 * a * empujePrueba
    0
    0
];

aceleracionEsperada = ...
    I \ momentoEsperado;

assert( ...
    norm( ...
        resultado.momentoEmpuje_B_Nm - ...
        momentoEsperado) < tolerancia, ...
    "Prueba 2 falló: momento de roll incorrecto." ...
);

assert( ...
    norm( ...
        resultado.velocidadAngularDot_B - ...
        aceleracionEsperada) < tolerancia, ...
    "Prueba 2 falló: aceleración de roll incorrecta." ...
);

fprintf("Prueba 2 aprobada: momento positivo de roll.\n");


%% PRUEBA 3
% Pitch positivo.
%
% Se aplica empuje en los motores frontales:
% M1 y M2.
%
% tau_y = 2*a*T

empujeMotores = [
    empujePrueba
    empujePrueba
    0
    0
];

resultado = dinamica_rotacional( ...
    x, ...
    empujeMotores, ...
    torqueReaccionCero, ...
    momentoExternoCero, ...
    P, ...
    modelo ...
);

momentoEsperado = [
    0
    2 * a * empujePrueba
    0
];

aceleracionEsperada = ...
    I \ momentoEsperado;

assert( ...
    norm( ...
        resultado.momentoEmpuje_B_Nm - ...
        momentoEsperado) < tolerancia, ...
    "Prueba 3 falló: momento de pitch incorrecto." ...
);

assert( ...
    norm( ...
        resultado.velocidadAngularDot_B - ...
        aceleracionEsperada) < tolerancia, ...
    "Prueba 3 falló: aceleración de pitch incorrecta." ...
);

fprintf("Prueba 3 aprobada: momento positivo de pitch.\n");


%% PRUEBA 4
% Yaw positivo producido por M1.
%
% M1 tiene signo positivo de torque de reacción.

empujeMotores = zeros(4, 1);

torquePrueba = 0.02;

torqueReaccionMotores = [
    torquePrueba
    0
    0
    0
];

resultado = dinamica_rotacional( ...
    x, ...
    empujeMotores, ...
    torqueReaccionMotores, ...
    momentoExternoCero, ...
    P, ...
    modelo ...
);

momentoEsperado = [
    0
    0
    torquePrueba
];

aceleracionEsperada = ...
    I \ momentoEsperado;

assert( ...
    norm( ...
        resultado.momentoReaccionYaw_B_Nm - ...
        momentoEsperado) < tolerancia, ...
    "Prueba 4 falló: momento de yaw incorrecto." ...
);

assert( ...
    norm( ...
        resultado.velocidadAngularDot_B - ...
        aceleracionEsperada) < tolerancia, ...
    "Prueba 4 falló: aceleración de yaw incorrecta." ...
);

fprintf("Prueba 4 aprobada: momento positivo de yaw.\n");


%% PRUEBA 5
% Momento externo puro alrededor de X_B.

momentoExterno = [
    0.10
    0
    0
];

resultado = dinamica_rotacional( ...
    x, ...
    zeros(4, 1), ...
    torqueReaccionCero, ...
    momentoExterno, ...
    P, ...
    modelo ...
);

aceleracionEsperada = ...
    I \ momentoExterno;

assert( ...
    norm( ...
        resultado.velocidadAngularDot_B - ...
        aceleracionEsperada) < tolerancia, ...
    "Prueba 5 falló: respuesta al momento externo incorrecta." ...
);

fprintf("Prueba 5 aprobada: momento externo alrededor de roll.\n");


%% PRUEBA 6
% Acoplamiento giroscópico del cuerpo rígido.
%
% Para un tensor diagonal:
%
% p_dot = ((Iyy-Izz)/Ixx)*q*r
% q_dot = ((Izz-Ixx)/Iyy)*p*r
% r_dot = ((Ixx-Iyy)/Izz)*p*q

xGiro = zeros(modelo.numeroEstados, 1);

p = 1.0;
q = 2.0;
r = 3.0;

xGiro(modelo.idx.p) = p;
xGiro(modelo.idx.q) = q;
xGiro(modelo.idx.r) = r;

resultado = dinamica_rotacional( ...
    xGiro, ...
    zeros(4, 1), ...
    torqueReaccionCero, ...
    momentoExternoCero, ...
    P, ...
    modelo ...
);

Ixx = I(1,1);
Iyy = I(2,2);
Izz = I(3,3);

aceleracionEsperada = [
    ((Iyy - Izz) / Ixx) * q * r
    ((Izz - Ixx) / Iyy) * p * r
    ((Ixx - Iyy) / Izz) * p * q
];

assert( ...
    norm( ...
        resultado.velocidadAngularDot_B - ...
        aceleracionEsperada) < tolerancia, ...
    "Prueba 6 falló: acoplamiento giroscópico incorrecto." ...
);

fprintf("Prueba 6 aprobada: acoplamiento giroscópico.\n");


%% PRUEBA 7
% Arrastre angular alrededor de X_B.

PconArrastre = P;

coefArrastreRoll = 0.10;

PconArrastre.aerodinamica.arrastreAngular_B = [
    coefArrastreRoll
    0
    0
];

xArrastre = zeros(modelo.numeroEstados, 1);
xArrastre(modelo.idx.p) = 1.0;

resultado = dinamica_rotacional( ...
    xArrastre, ...
    zeros(4, 1), ...
    torqueReaccionCero, ...
    momentoExternoCero, ...
    PconArrastre, ...
    modelo ...
);

momentoEsperado = [
    -coefArrastreRoll
    0
    0
];

aceleracionEsperada = ...
    I \ momentoEsperado;

assert( ...
    norm( ...
        resultado.momentoArrastre_B_Nm - ...
        momentoEsperado) < tolerancia, ...
    "Prueba 7 falló: momento de arrastre incorrecto." ...
);

assert( ...
    norm( ...
        resultado.velocidadAngularDot_B - ...
        aceleracionEsperada) < tolerancia, ...
    "Prueba 7 falló: desaceleración angular incorrecta." ...
);

fprintf("Prueba 7 aprobada: arrastre angular.\n");


%% RESULTADO FINAL

fprintf("\n================================================\n");
fprintf(" TODAS LAS PRUEBAS ROTACIONALES APROBARON\n");
fprintf("================================================\n");