%% TEST_CONTROL_ACTITUD_CERRADO
% Prueba el controlador conectado con:
%
%   Controlador
%       ↓
%   Mezclador
%       ↓
%   Modelo no lineal
%       ↓
%   RK4
%
% Secuencia:
%
%   0.0 a 1.0 s  : hover
%   1.0 a 2.5 s  : roll positivo
%   3.0 a 4.5 s  : avance mediante pitch negativo
%   5.0 a 6.0 s  : yaw positivo
%   6.0 a 7.0 s  : recuperación

clearvars;
clc;
close all;

fprintf('\n');
fprintf('============================================================\n');
fprintf(' PRUEBA DE CONTROL DE ACTITUD EN LAZO CERRADO\n');
fprintf('============================================================\n\n');

%% Preparar modelo y caso base

modelo = definicion_modelo();

P = parametros_fisicos();

R = reglas_competencia();

Dproyecto = requisitos_proyecto(R);

Cdiseno = parametros_diseno();

[P, Cdiseno, ~] = caso_base_teorico( ...
    P, ...
    Cdiseno, ...
    R ...
);

G = configuracion_motores_x( ...
    R, ...
    Dproyecto, ...
    Cdiseno.geometria.distanciaCentroMotor, ...
    Cdiseno.geometria.zMotor_B ...
);

P = aplicar_configuracion_motores(P, G);

%% Parámetros del controlador

Ccontrol = parametros_control_actitud(P);

estadoControl = [];

%% Configuración temporal

dt = 0.005;

tiempoFinal = 7.0;

numeroPasos = round(tiempoFinal / dt);

tiempo = (0:numeroPasos).' * dt;

%% Estado inicial

x = zeros(modelo.numeroEstados, 1);

% Empezar un metro arriba del piso.
x(modelo.idx.zD) = -1.0;

%% Perturbación nula

E = perturbacion_nula();

%% Historiales

historialEstado = zeros( ...
    numeroPasos + 1, ...
    modelo.numeroEstados ...
);

historialEstado(1, :) = x.';

referenciaRoll = zeros(numeroPasos + 1, 1);
referenciaPitch = zeros(numeroPasos + 1, 1);
referenciaYawRate = zeros(numeroPasos + 1, 1);

historialMomentos = zeros(numeroPasos + 1, 3);

historialMotores = zeros( ...
    numeroPasos + 1, ...
    P.motores.numero ...
);

%% Simulación

for k = 1:numeroPasos

    t = tiempo(k);

    %% Comando neutral

    comando.roll = 0;
    comando.pitch = 0;
    comando.yaw = 0;

    comando.throttle = 0.5;
    comando.armado = true;

    %% Secuencia de referencias

    if t >= 1.0 && t < 2.5

        comando.roll = 0.55;

    elseif t >= 3.0 && t < 4.5

        comando.pitch = 0.55;

    elseif t >= 5.0 && t < 6.0

        comando.yaw = 0.50;

    end

    %% Controlador

    [momentoDeseado, estadoControl, Dcontrol] = ...
        controlador_actitud( ...
            comando, ...
            x, ...
            dt, ...
            Ccontrol, ...
            estadoControl, ...
            modelo ...
        );

    %% Empuje colectivo

    phi = x(modelo.idx.phi);
    theta = x(modelo.idx.theta);

    compensacionInclinacion = ...
        cos(phi) * cos(theta);

    compensacionInclinacion = max( ...
        compensacionInclinacion, ...
        0.65 ...
    );

    empujeTotal_N = ...
        P.cuerpo.masa * ...
        P.entorno.g / ...
        compensacionInclinacion;

    %% Mezclador

    [U, ~] = mezclador_motores_x( ...
        empujeTotal_N, ...
        momentoDeseado, ...
        P ...
    );

    %% Integración del modelo completo

    x = paso_rk4( ...
        @modelo_no_lineal_12_estados, ...
        t, ...
        x, ...
        dt, ...
        U, ...
        E, ...
        P, ...
        modelo ...
    );

    %% Guardar resultados

    historialEstado(k + 1, :) = x.';

    referenciaRoll(k + 1) = ...
        Dcontrol.referencia.phi_rad;

    referenciaPitch(k + 1) = ...
        Dcontrol.referencia.theta_rad;

    referenciaYawRate(k + 1) = ...
        Dcontrol.referencia.r_rad_s;

    historialMomentos(k + 1, :) = ...
        momentoDeseado.';

    historialMotores(k + 1, :) = ...
        U.empujeMotores_N.';

end

%% Conversión para gráficas

rollGrados = rad2deg( ...
    historialEstado(:, modelo.idx.phi) ...
);

pitchGrados = rad2deg( ...
    historialEstado(:, modelo.idx.theta) ...
);

yawRateGrados = rad2deg( ...
    historialEstado(:, modelo.idx.r) ...
);

rollReferenciaGrados = ...
    rad2deg(referenciaRoll);

pitchReferenciaGrados = ...
    rad2deg(referenciaPitch);

yawRateReferenciaGrados = ...
    rad2deg(referenciaYawRate);

%% Verificaciones automáticas

assert( ...
    all(isfinite(historialEstado), 'all'), ...
    'La simulación produjo NaN o valores infinitos.' ...
);

intervaloRoll = ...
    tiempo >= 1.2 & tiempo < 2.5;

intervaloPitch = ...
    tiempo >= 3.2 & tiempo < 4.5;

intervaloYaw = ...
    tiempo >= 5.2 & tiempo < 6.0;

assert( ...
    max(rollGrados(intervaloRoll)) > 5, ...
    'El dron no respondió correctamente al comando de roll.' ...
);

assert( ...
    min(pitchGrados(intervaloPitch)) < -5, ...
    'El dron no respondió correctamente al comando de avance.' ...
);

assert( ...
    max(yawRateGrados(intervaloYaw)) > 10, ...
    'El dron no respondió correctamente al comando de yaw.' ...
);

assert( ...
    abs(rollGrados(end)) < 3, ...
    'El roll no regresó cerca de cero.' ...
);

assert( ...
    abs(pitchGrados(end)) < 3, ...
    'El pitch no regresó cerca de cero.' ...
);

%% Imprimir resultados

fprintf('Ganancias calculadas:\n\n');

fprintf('Roll:\n');
fprintf('  Kp = %.6f\n', Ccontrol.roll.Kp);
fprintf('  Ki = %.6f\n', Ccontrol.roll.Ki);
fprintf('  Kd = %.6f\n\n', Ccontrol.roll.Kd);

fprintf('Pitch:\n');
fprintf('  Kp = %.6f\n', Ccontrol.pitch.Kp);
fprintf('  Ki = %.6f\n', Ccontrol.pitch.Ki);
fprintf('  Kd = %.6f\n\n', Ccontrol.pitch.Kd);

fprintf('Yaw rate:\n');
fprintf('  Kp = %.6f\n', Ccontrol.yaw.Kp);
fprintf('  Ki = %.6f\n\n', Ccontrol.yaw.Ki);

fprintf('Estado final:\n');
fprintf('  Roll:     %.3f grados\n', rollGrados(end));
fprintf('  Pitch:    %.3f grados\n', pitchGrados(end));
fprintf('  Yaw rate: %.3f grados/s\n\n', yawRateGrados(end));

fprintf('============================================================\n');
fprintf(' PRUEBA APROBADA\n');
fprintf(' EL CONTROLADOR RESPONDE EN ROLL, PITCH Y YAW\n');
fprintf('============================================================\n\n');

%% Gráficas principales

figure( ...
    'Name', 'Control de actitud en lazo cerrado', ...
    'NumberTitle', 'off', ...
    'Color', 'white' ...
);

tiledlayout(2, 2);

%% Roll

nexttile;

plot(tiempo, rollGrados, 'LineWidth', 2);

hold on;

plot( ...
    tiempo, ...
    rollReferenciaGrados, ...
    '--', ...
    'LineWidth', 1.5 ...
);

grid on;

xlabel('Tiempo [s]');
ylabel('Roll [grados]');
title('Respuesta de roll');

legend( ...
    'Roll real', ...
    'Referencia', ...
    'Location', ...
    'best' ...
);

%% Pitch

nexttile;

plot(tiempo, pitchGrados, 'LineWidth', 2);

hold on;

plot( ...
    tiempo, ...
    pitchReferenciaGrados, ...
    '--', ...
    'LineWidth', 1.5 ...
);

grid on;

xlabel('Tiempo [s]');
ylabel('Pitch [grados]');
title('Respuesta de pitch');

legend( ...
    'Pitch real', ...
    'Referencia', ...
    'Location', ...
    'best' ...
);

%% Yaw rate

nexttile;

plot(tiempo, yawRateGrados, 'LineWidth', 2);

hold on;

plot( ...
    tiempo, ...
    yawRateReferenciaGrados, ...
    '--', ...
    'LineWidth', 1.5 ...
);

grid on;

xlabel('Tiempo [s]');
ylabel('Velocidad yaw [grados/s]');
title('Control de velocidad de yaw');

legend( ...
    'Yaw rate real', ...
    'Referencia', ...
    'Location', ...
    'best' ...
);

%% Momentos

nexttile;

plot( ...
    tiempo, ...
    historialMomentos, ...
    'LineWidth', ...
    1.5 ...
);

grid on;

xlabel('Tiempo [s]');
ylabel('Momento [N m]');
title('Momentos ordenados');

legend( ...
    'Mx - Roll', ...
    'My - Pitch', ...
    'Mz - Yaw', ...
    'Location', ...
    'best' ...
);

%% Gráfica de motores

figure( ...
    'Name', 'Empuje individual de motores', ...
    'NumberTitle', 'off', ...
    'Color', 'white' ...
);

plot( ...
    tiempo, ...
    historialMotores, ...
    'LineWidth', ...
    1.5 ...
);

grid on;

xlabel('Tiempo [s]');
ylabel('Empuje [N]');

title('Distribución del empuje en los cuatro motores');

legend( ...
    'M1', ...
    'M2', ...
    'M3', ...
    'M4', ...
    'Location', ...
    'best' ...
);