%% TEST_RECHAZO_PERTURBACION_PITCH_REAL
% Valida el rechazo de una perturbacion externa en pitch usando
% los parametros fisicos del KIWO E88 real V1.
%
% Caso utilizado:
%
%   - Masa total medida: 0.081 kg.
%   - Geometria rectangular: 0.17 m x 0.14 m.
%   - Centro de masa estimado considerando la bateria.
%   - Tensor de inercia estimado.
%   - Empuje maximo provisional de 0.300 N por motor.
%   - Ganancias recalculadas con la inercia real V1.
%
% Secuencia:
%
%   0.0 a 2.0 s:
%       Hover estable.
%
%   2.0 a 2.15 s:
%       Momento externo positivo alrededor del eje Y_B.
%
%   2.15 a 8.0 s:
%       Recuperacion mediante el controlador de pitch.

clearvars;
clc;
close all;

fprintf('\n');
fprintf('============================================================\n');
fprintf(' RECHAZO DE PERTURBACION EN PITCH - KIWO E88 REAL V1\n');
fprintf('============================================================\n\n');

%% ================================================================
% CARGAR MODELO
% ================================================================

modelo = definicion_modelo();

P = parametros_fisicos();

Cdiseno = parametros_diseno();

R = reglas_competencia();

[P, Cdiseno, caso] = caso_real_dron( ...
    P, ...
    Cdiseno, ...
    R ...
);

% No se llama configuracion_motores_x porque sobrescribiria
% la geometria rectangular real del KIWO E88.

%% ================================================================
% VALIDAR PARAMETROS FISICOS
% ================================================================

reporteFisico = validar_parametros_fisicos(P);

if ~reporteFisico.completo

    fprintf('PARAMETROS FISICOS INCOMPLETOS O INVALIDOS:\n\n');

    for k = 1:numel(reporteFisico.faltantes)

        fprintf( ...
            '  Faltante: %s\n', ...
            reporteFisico.faltantes(k) ...
        );

    end

    for k = 1:numel(reporteFisico.errores)

        fprintf( ...
            '  Error: %s\n', ...
            reporteFisico.errores(k) ...
        );

    end

    error( ...
        'test_rechazo_perturbacion_pitch_real:ParametrosInvalidos', ...
        'El caso real no supero la validacion fisica.' ...
    );

end

%% ================================================================
% CONTROLADOR DEL CASO REAL
% ================================================================

Ccontrol = parametros_control_actitud(P);

estadoControl = [];

%% ================================================================
% CONFIGURACION TEMPORAL
% ================================================================

dt = 0.005;

tiempoFinal_s = 8.0;

numeroPasos = round( ...
    tiempoFinal_s / dt ...
);

tiempo_s = ...
    (0:numeroPasos).' * dt;

numeroMuestras = ...
    numeroPasos + 1;

%% ================================================================
% CONFIGURACION DE LA PERTURBACION
% ================================================================

ejePerturbacion = "pitch";

% Momento reducido para el KIWO E88 de 81 gramos.

momentoPerturbacion_Nm = 0.0010;

inicioPerturbacion_s = 2.00;

duracionPerturbacion_s = 0.15;

finPerturbacion_s = ...
    inicioPerturbacion_s + ...
    duracionPerturbacion_s;

%% ================================================================
% MOSTRAR CONFIGURACION
% ================================================================

fprintf('Caso cargado:\n');
fprintf('  %s\n\n', ...
    caso.meta.nombre);

fprintf('Parametros principales:\n');

fprintf('  Masa total:                %.4f kg\n', ...
    P.cuerpo.masa);

fprintf('  Ixx:                       %.8e kg*m^2\n', ...
    P.cuerpo.inercia_B(1, 1));

fprintf('  Iyy:                       %.8e kg*m^2\n', ...
    P.cuerpo.inercia_B(2, 2));

fprintf('  Izz:                       %.8e kg*m^2\n', ...
    P.cuerpo.inercia_B(3, 3));

fprintf('  Empuje hover por motor:    %.4f N\n', ...
    caso.empujeHoverPorMotor_N);

fprintf('  Empuje maximo por motor:   %.4f N\n', ...
    caso.empujeMaximoPorMotor_N);

fprintf('  Relacion empuje/peso:      %.3f\n\n', ...
    caso.relacionEmpujePesoMaxima);

fprintf('Ganancias de pitch:\n');

fprintf('  Kp:                        %.8f\n', ...
    Ccontrol.pitch.Kp);

fprintf('  Ki:                        %.8f\n', ...
    Ccontrol.pitch.Ki);

fprintf('  Kd:                        %.8f\n', ...
    Ccontrol.pitch.Kd);

fprintf('  Momento maximo permitido:  %.6f N*m\n', ...
    Ccontrol.limites.momentoPitchMax_Nm);

fprintf('  Metodo de limites:         %s\n\n', ...
    Ccontrol.autoridad.metodo);

fprintf('Perturbacion:\n');

fprintf('  Eje:                       %s\n', ...
    ejePerturbacion);

fprintf('  Magnitud:                  %.6f N*m\n', ...
    momentoPerturbacion_Nm);

fprintf('  Inicio:                    %.3f s\n', ...
    inicioPerturbacion_s);

fprintf('  Duracion:                  %.3f s\n', ...
    duracionPerturbacion_s);

fprintf('  Fin:                       %.3f s\n\n', ...
    finPerturbacion_s);

%% ================================================================
% ESTADO INICIAL
% ================================================================

x = zeros( ...
    modelo.numeroEstados, ...
    1 ...
);

% Marco NED:
% zD negativa representa altura positiva.

x(modelo.idx.zD) = -1.0;

%% ================================================================
% REFERENCIAS DEL CONTROLADOR
% ================================================================

% El dron debe permanecer nivelado.
% El movimiento de pitch sera producido por la perturbacion.

comando.roll = 0;
comando.pitch = 0;
comando.yaw = 0;

comando.throttle = 0.50;

comando.armado = true;

%% ================================================================
% CREAR HISTORIALES
% ================================================================

historialEstado = zeros( ...
    numeroMuestras, ...
    modelo.numeroEstados ...
);

historialEstado(1, :) = ...
    x.';

historialReferenciaPitch_rad = zeros( ...
    numeroMuestras, ...
    1 ...
);

historialErrorPitch_rad = zeros( ...
    numeroMuestras, ...
    1 ...
);

historialMomentoControl_B_Nm = zeros( ...
    numeroMuestras, ...
    3 ...
);

historialMomentoRealMotores_B_Nm = zeros( ...
    numeroMuestras, ...
    3 ...
);

historialMomentoExterno_B_Nm = zeros( ...
    numeroMuestras, ...
    3 ...
);

historialEmpujeMotores_N = zeros( ...
    numeroMuestras, ...
    P.motores.numero ...
);

historialSaturacionControlador = false( ...
    numeroMuestras, ...
    1 ...
);

historialSaturacionMezclador = false( ...
    numeroMuestras, ...
    1 ...
);

%% ================================================================
% INICIALIZAR MOTORES EN HOVER
% ================================================================

empujeHoverTotal_N = ...
    P.cuerpo.masa * ...
    P.entorno.g;

[Uhover, Dhover] = mezclador_motores_x( ...
    empujeHoverTotal_N, ...
    zeros(3, 1), ...
    P ...
);

historialEmpujeMotores_N(1, :) = ...
    Uhover.empujeMotores_N.';

historialMomentoRealMotores_B_Nm(1, :) = ...
    Dhover.momentoReal_B_Nm.';

%% ================================================================
% SIMULACION
% ================================================================

fprintf('Ejecutando simulacion del caso real...\n\n');

for k = 1:numeroPasos

    t = ...
        tiempo_s(k);

    %% Perturbacion externa

    E = perturbacion_pulso_actitud( ...
        t, ...
        ejePerturbacion, ...
        momentoPerturbacion_Nm, ...
        inicioPerturbacion_s, ...
        duracionPerturbacion_s ...
    );

    %% Controlador de actitud

    [ ...
        momentoDeseado_B_Nm, ...
        estadoControl, ...
        Dcontrol ...
    ] = controlador_actitud( ...
        comando, ...
        x, ...
        dt, ...
        Ccontrol, ...
        estadoControl, ...
        modelo ...
    );

    %% Compensacion aproximada del empuje vertical

    phi_rad = ...
        x(modelo.idx.phi);

    theta_rad = ...
        x(modelo.idx.theta);

    factorVertical = ...
        cos(phi_rad) * ...
        cos(theta_rad);

    factorVertical = max( ...
        factorVertical, ...
        0.65 ...
    );

    empujeTotal_N = ...
        P.cuerpo.masa * ...
        P.entorno.g / ...
        factorVertical;

    %% Mezclador de motores

    [U, Dmezclador] = mezclador_motores_x( ...
        empujeTotal_N, ...
        momentoDeseado_B_Nm, ...
        P ...
    );

    %% Integracion con RK4

    x = paso_rk4( ...
        @modelo_no_lineal_12_estados, ...
        t, ...
        x, ...
        dt, ...
        U, ...
        E, ...
        P, ...
        modelo ...
    );

    %% Guardar resultados

    historialEstado(k + 1, :) = ...
        x.';

    historialReferenciaPitch_rad(k + 1) = ...
        Dcontrol.referencia.theta_rad;

    historialErrorPitch_rad(k + 1) = ...
        Dcontrol.error.pitch_rad;

    historialMomentoControl_B_Nm(k + 1, :) = ...
        momentoDeseado_B_Nm.';

    historialMomentoRealMotores_B_Nm(k + 1, :) = ...
        Dmezclador.momentoReal_B_Nm.';

    historialMomentoExterno_B_Nm(k + 1, :) = ...
        E.momentoExterno_B_Nm.';

    historialEmpujeMotores_N(k + 1, :) = ...
        U.empujeMotores_N.';

    diferenciaSaturacionControl = ...
        Dcontrol.momentoSinSaturar_B_Nm - ...
        Dcontrol.momentoSaturado_B_Nm;

    historialSaturacionControlador(k + 1) = ...
        any( ...
            abs(diferenciaSaturacionControl) > 1e-12 ...
        );

    historialSaturacionMezclador(k + 1) = ...
        Dmezclador.huboSaturacion;

end

%% ================================================================
% PROCESAR RESULTADOS
% ================================================================

pitch_rad = ...
    historialEstado(:, modelo.idx.theta);

velocidadPitch_rad_s = ...
    historialEstado(:, modelo.idx.q);

pitch_deg = ...
    rad2deg(pitch_rad);

velocidadPitch_deg_s = ...
    rad2deg(velocidadPitch_rad_s);

referenciaPitch_deg = ...
    rad2deg(historialReferenciaPitch_rad);

errorPitch_deg = ...
    rad2deg(historialErrorPitch_rad);

momentoControlPitch_Nm = ...
    historialMomentoControl_B_Nm(:, 2);

momentoRealMotoresPitch_Nm = ...
    historialMomentoRealMotores_B_Nm(:, 2);

momentoExternoPitch_Nm = ...
    historialMomentoExterno_B_Nm(:, 2);

%% ================================================================
% CALCULAR INDICADORES
% ================================================================

indicesDesdePerturbacion = ...
    tiempo_s >= inicioPerturbacion_s;

indicesDespuesPulso = ...
    tiempo_s >= finPerturbacion_s;

%% Desviacion maxima

[desviacionMaxima_deg, indicePicoRelativo] = max( ...
    abs( ...
        pitch_deg(indicesDesdePerturbacion) ...
    ) ...
);

indicesGlobales = find( ...
    indicesDesdePerturbacion ...
);

indicePico = ...
    indicesGlobales(indicePicoRelativo);

tiempoPico_s = ...
    tiempo_s(indicePico);

pitchEnPico_deg = ...
    pitch_deg(indicePico);

%% Rebote contrario

if pitchEnPico_deg >= 0

    pitchContrario_deg = min( ...
        pitch_deg(indicePico:end) ...
    );

    reboteContrario_deg = max( ...
        0, ...
        -pitchContrario_deg ...
    );

else

    pitchContrario_deg = max( ...
        pitch_deg(indicePico:end) ...
    );

    reboteContrario_deg = max( ...
        0, ...
        pitchContrario_deg ...
    );

end

%% Tiempo de establecimiento

limitePitchEstable_deg = max( ...
    0.25, ...
    0.02 * desviacionMaxima_deg ...
);

limiteVelocidadEstable_deg_s = 0.50;

tiempoEstablecimiento_s = NaN;

indicesBusqueda = find( ...
    indicesDespuesPulso ...
);

for i = 1:numel(indicesBusqueda)

    indiceActual = ...
        indicesBusqueda(i);

    pitchPermaneceEstable = all( ...
        abs(pitch_deg(indiceActual:end)) <= ...
        limitePitchEstable_deg ...
    );

    velocidadPermaneceEstable = all( ...
        abs(velocidadPitch_deg_s(indiceActual:end)) <= ...
        limiteVelocidadEstable_deg_s ...
    );

    if pitchPermaneceEstable && ...
            velocidadPermaneceEstable

        tiempoEstablecimiento_s = ...
            tiempo_s(indiceActual) - ...
            finPerturbacion_s;

        break;

    end

end

%% Esfuerzo de control

momentoControlMaximo_Nm = max( ...
    abs(momentoControlPitch_Nm) ...
);

momentoRealMotoresMaximo_Nm = max( ...
    abs(momentoRealMotoresPitch_Nm) ...
);

diferenciaEmpujeMotores_N = ...
    max(historialEmpujeMotores_N, [], 2) - ...
    min(historialEmpujeMotores_N, [], 2);

diferenciaEmpujeMotoresMax_N = max( ...
    diferenciaEmpujeMotores_N ...
);

huboSaturacionControlador = any( ...
    historialSaturacionControlador ...
);

huboSaturacionMezclador = any( ...
    historialSaturacionMezclador ...
);

porcentajeMomentoUtilizado = ...
    100 * ...
    momentoControlMaximo_Nm / ...
    Ccontrol.limites.momentoPitchMax_Nm;

%% Estado final

pitchFinal_deg = ...
    pitch_deg(end);

velocidadPitchFinal_deg_s = ...
    velocidadPitch_deg_s(end);

%% ================================================================
% VERIFICACIONES AUTOMATICAS
% ================================================================

assert( ...
    all(isfinite(historialEstado), 'all'), ...
    ['La simulacion real produjo valores NaN o infinitos. ' ...
     'Revisa los parametros fisicos.'] ...
);

assert( ...
    desviacionMaxima_deg > 0.50, ...
    ['La perturbacion no produjo una desviacion apreciable ' ...
     'en pitch.'] ...
);

assert( ...
    desviacionMaxima_deg < 20.0, ...
    ['El dron real V1 alcanzo una inclinacion demasiado ' ...
     'grande en pitch.'] ...
);

assert( ...
    momentoControlMaximo_Nm > 1e-5, ...
    ['El controlador no produjo una correccion apreciable ' ...
     'en pitch.'] ...
);

assert( ...
    min(momentoControlPitch_Nm) < -1e-5, ...
    ['El controlador no genero un momento contrario a la ' ...
     'perturbacion positiva de pitch.'] ...
);

assert( ...
    min(momentoRealMotoresPitch_Nm) < -1e-5, ...
    ['Los motores no produjeron un momento real correctivo ' ...
     'negativo en pitch.'] ...
);

assert( ...
    abs(pitchFinal_deg) < 0.50, ...
    ['El pitch del caso real no regreso suficientemente ' ...
     'cerca de cero.'] ...
);

assert( ...
    abs(velocidadPitchFinal_deg_s) < 0.50, ...
    'La velocidad angular final de pitch es demasiado grande.' ...
);

assert( ...
    isfinite(tiempoEstablecimiento_s), ...
    ['El pitch no alcanzo la banda de establecimiento ' ...
     'antes de terminar la simulacion.'] ...
);

%% ================================================================
% GUARDAR RESULTADOS PARA LA GRAFICA EXISTENTE
% ================================================================

resultadosPitch.meta.nombre = ...
    "Rechazo de perturbacion en pitch - KIWO E88 real V1";

resultadosPitch.meta.caso = ...
    caso.meta.nombre;

resultadosPitch.configuracion.dt_s = ...
    dt;

resultadosPitch.configuracion.tiempoFinal_s = ...
    tiempoFinal_s;

resultadosPitch.configuracion.ejePerturbacion = ...
    ejePerturbacion;

resultadosPitch.configuracion.momentoPerturbacion_Nm = ...
    momentoPerturbacion_Nm;

resultadosPitch.configuracion.inicioPerturbacion_s = ...
    inicioPerturbacion_s;

resultadosPitch.configuracion.duracionPerturbacion_s = ...
    duracionPerturbacion_s;

resultadosPitch.configuracion.finPerturbacion_s = ...
    finPerturbacion_s;

resultadosPitch.tiempo_s = ...
    tiempo_s;

resultadosPitch.estado = ...
    historialEstado;

resultadosPitch.pitch_deg = ...
    pitch_deg;

resultadosPitch.velocidadPitch_deg_s = ...
    velocidadPitch_deg_s;

resultadosPitch.referenciaPitch_deg = ...
    referenciaPitch_deg;

resultadosPitch.errorPitch_deg = ...
    errorPitch_deg;

resultadosPitch.momentoControl_B_Nm = ...
    historialMomentoControl_B_Nm;

resultadosPitch.momentoRealMotores_B_Nm = ...
    historialMomentoRealMotores_B_Nm;

resultadosPitch.momentoExterno_B_Nm = ...
    historialMomentoExterno_B_Nm;

resultadosPitch.empujeMotores_N = ...
    historialEmpujeMotores_N;

resultadosPitch.metricas.desviacionMaxima_deg = ...
    desviacionMaxima_deg;

resultadosPitch.metricas.tiempoPico_s = ...
    tiempoPico_s;

resultadosPitch.metricas.pitchEnPico_deg = ...
    pitchEnPico_deg;

resultadosPitch.metricas.reboteContrario_deg = ...
    reboteContrario_deg;

resultadosPitch.metricas.tiempoEstablecimiento_s = ...
    tiempoEstablecimiento_s;

resultadosPitch.metricas.limitePitchEstable_deg = ...
    limitePitchEstable_deg;

resultadosPitch.metricas.momentoControlMaximo_Nm = ...
    momentoControlMaximo_Nm;

resultadosPitch.metricas.momentoRealMotoresMaximo_Nm = ...
    momentoRealMotoresMaximo_Nm;

resultadosPitch.metricas.diferenciaEmpujeMotoresMax_N = ...
    diferenciaEmpujeMotoresMax_N;

resultadosPitch.metricas.porcentajeMomentoUtilizado = ...
    porcentajeMomentoUtilizado;

resultadosPitch.metricas.pitchFinal_deg = ...
    pitchFinal_deg;

resultadosPitch.metricas.velocidadPitchFinal_deg_s = ...
    velocidadPitchFinal_deg_s;

resultadosPitch.metricas.huboSaturacionControlador = ...
    huboSaturacionControlador;

resultadosPitch.metricas.huboSaturacionMezclador = ...
    huboSaturacionMezclador;

%% ================================================================
% MOSTRAR RESULTADOS
% ================================================================

fprintf('============================================================\n');
fprintf(' RESULTADOS DEL KIWO E88 REAL V1 - PITCH\n');
fprintf('============================================================\n\n');

fprintf('Respuesta angular:\n');

fprintf('  Desviacion maxima:          %.3f grados\n', ...
    desviacionMaxima_deg);

fprintf('  Instante del pico:          %.3f s\n', ...
    tiempoPico_s);

fprintf('  Pitch en el pico:           %.3f grados\n', ...
    pitchEnPico_deg);

fprintf('  Rebote contrario:           %.3f grados\n', ...
    reboteContrario_deg);

fprintf('  Tiempo de establecimiento:  %.3f s\n', ...
    tiempoEstablecimiento_s);

fprintf('  Banda de establecimiento:   +/- %.3f grados\n', ...
    limitePitchEstable_deg);

fprintf('  Pitch final:                %.3f grados\n', ...
    pitchFinal_deg);

fprintf('  Velocidad final:            %.3f grados/s\n\n', ...
    velocidadPitchFinal_deg_s);

fprintf('Esfuerzo de control:\n');

fprintf('  Momento PID maximo:         %.6f N*m\n', ...
    momentoControlMaximo_Nm);

fprintf('  Momento real motores max:   %.6f N*m\n', ...
    momentoRealMotoresMaximo_Nm);

fprintf('  Limite disponible pitch:    %.6f N*m\n', ...
    Ccontrol.limites.momentoPitchMax_Nm);

fprintf('  Autoridad utilizada:        %.2f %%\n', ...
    porcentajeMomentoUtilizado);

fprintf('  Diferencia maxima motores:  %.6f N\n', ...
    diferenciaEmpujeMotoresMax_N);

fprintf('  Saturacion controlador:     %s\n', ...
    string(huboSaturacionControlador));

fprintf('  Saturacion mezclador:       %s\n\n', ...
    string(huboSaturacionMezclador));

fprintf('============================================================\n');
fprintf(' PRUEBA APROBADA\n');
fprintf(' EL KIWO E88 REAL V1 RECHAZA LA PERTURBACION EN PITCH\n');
fprintf('============================================================\n\n');

fprintf('NOTA:\n');
fprintf(['  Esta prueba utiliza parametros medidos y estimados.\n' ...
         '  Debera repetirse cuando se mida el empuje real y\n' ...
         '  se refine el tensor de inercia.\n\n']);

%% ================================================================
% REUTILIZAR GRAFICA DE PITCH
% ================================================================

if exist( ...
        'graficar_rechazo_perturbacion_pitch', ...
        'file' ...
    ) == 2

    graficar_rechazo_perturbacion_pitch( ...
        resultadosPitch ...
    );

else

    fprintf( ...
        ['No se encontro graficar_rechazo_perturbacion_pitch.m.\n' ...
         'La simulacion real fue ejecutada correctamente.\n\n'] ...
    );

end