%% TEST_RECHAZO_PERTURBACION_ROLL_REAL
% Valida el rechazo de una perturbacion externa en roll usando
% los parametros fisicos del KIWO E88 real V1.
%
% Diferencias respecto a la prueba teorica:
%
%   - Masa total medida: 0.081 kg.
%   - Geometria rectangular real: 0.17 m x 0.14 m.
%   - Tensor de inercia estimado para el KIWO E88.
%   - Limites de empuje provisionales de 0.300 N por motor.
%   - Ganancias recalculadas automaticamente.
%   - Perturbacion reducida para un dron de 81 gramos.
%
% Secuencia:
%
%   0.0 a 2.0 s:
%       Hover estable.
%
%   2.0 a 2.15 s:
%       Momento externo positivo en roll.
%
%   2.15 a 8.0 s:
%       Recuperacion del controlador.
%
% IMPORTANTE:
%
% Esta prueba valida la coherencia del modelo real V1.
% Todavia existen valores estimados, principalmente:
%
%   - Empuje maximo.
%   - Tensor de inercia.
%   - Posicion exacta de bateria.
%   - Dinamica de motores.

clearvars;
clc;
close all;

fprintf('\n');
fprintf('============================================================\n');
fprintf(' RECHAZO DE PERTURBACION EN ROLL - KIWO E88 REAL V1\n');
fprintf('============================================================\n\n');

%% ================================================================
% CARGAR MODELO
% ================================================================

modelo = definicion_modelo();

P = parametros_fisicos();

Cdiseno = parametros_diseno();

R = reglas_competencia();

% El caso real ya coloca directamente:
%
%   - masa;
%   - inercia;
%   - posiciones rectangulares de motores;
%   - limites de empuje;
%   - signos de yaw.
%
% Por eso NO debemos llamar despues a configuracion_motores_x,
% porque sobrescribiria la geometria real con una X cuadrada.

[P, Cdiseno, caso] = caso_real_dron( ...
    P, ...
    Cdiseno, ...
    R ...
);

%% ================================================================
% VALIDAR PARAMETROS FISICOS
% ================================================================

reporteFisico = validar_parametros_fisicos(P);

if ~reporteFisico.completo

    fprintf('PARAMETROS FISICOS INCOMPLETOS O INVALIDOS:\n\n');

    for k = 1:numel(reporteFisico.faltantes)

        fprintf( ...
            '  Faltante: %s\n', ...
            reporteFisico.faltantes(k) ...
        );

    end

    for k = 1:numel(reporteFisico.errores)

        fprintf( ...
            '  Error: %s\n', ...
            reporteFisico.errores(k) ...
        );

    end

    error( ...
        'test_rechazo_perturbacion_roll_real:ParametrosInvalidos', ...
        'El caso real no supero la validacion fisica.' ...
    );

end

%% ================================================================
% GENERAR CONTROLADOR PARA EL CASO REAL
% ================================================================

Ccontrol = parametros_control_actitud(P);

estadoControl = [];

%% ================================================================
% CONFIGURACION TEMPORAL
% ================================================================

dt = 0.005;

tiempoFinal_s = 8.0;

numeroPasos = round( ...
    tiempoFinal_s / dt ...
);

tiempo_s = ...
    (0:numeroPasos).' * dt;

numeroMuestras = ...
    numeroPasos + 1;

%% ================================================================
% CONFIGURACION DE LA PERTURBACION
% ================================================================

ejePerturbacion = "roll";

% El caso teorico utilizaba 0.08 N*m.
%
% Para un dron de solamente 81 gramos ese momento seria excesivo.
% Se utiliza un pulso de 0.001 N*m durante 0.15 segundos.

momentoPerturbacion_Nm = 0.0010;

inicioPerturbacion_s = 2.00;

duracionPerturbacion_s = 0.15;

finPerturbacion_s = ...
    inicioPerturbacion_s + ...
    duracionPerturbacion_s;

%% ================================================================
% MOSTRAR CONFIGURACION
% ================================================================

fprintf('Caso cargado:\n');
fprintf('  %s\n\n', caso.meta.nombre);

fprintf('Parametros principales:\n');
fprintf('  Masa total:                %.4f kg\n', ...
    P.cuerpo.masa);

fprintf('  Ixx:                       %.8e kg*m^2\n', ...
    P.cuerpo.inercia_B(1, 1));

fprintf('  Iyy:                       %.8e kg*m^2\n', ...
    P.cuerpo.inercia_B(2, 2));

fprintf('  Izz:                       %.8e kg*m^2\n', ...
    P.cuerpo.inercia_B(3, 3));

fprintf('  Empuje hover por motor:    %.4f N\n', ...
    caso.empujeHoverPorMotor_N);

fprintf('  Empuje maximo por motor:   %.4f N\n', ...
    caso.empujeMaximoPorMotor_N);

fprintf('  Relacion empuje/peso:      %.3f\n\n', ...
    caso.relacionEmpujePesoMaxima);

fprintf('Ganancias de roll:\n');
fprintf('  Kp:                        %.8f\n', ...
    Ccontrol.roll.Kp);

fprintf('  Ki:                        %.8f\n', ...
    Ccontrol.roll.Ki);

fprintf('  Kd:                        %.8f\n', ...
    Ccontrol.roll.Kd);

fprintf('  Momento maximo permitido:  %.6f N*m\n', ...
    Ccontrol.limites.momentoRollMax_Nm);

fprintf('  Metodo de limites:         %s\n\n', ...
    Ccontrol.autoridad.metodo);

fprintf('Perturbacion:\n');
fprintf('  Eje:                       %s\n', ...
    ejePerturbacion);

fprintf('  Magnitud:                  %.6f N*m\n', ...
    momentoPerturbacion_Nm);

fprintf('  Inicio:                    %.3f s\n', ...
    inicioPerturbacion_s);

fprintf('  Duracion:                  %.3f s\n', ...
    duracionPerturbacion_s);

fprintf('  Fin:                       %.3f s\n\n', ...
    finPerturbacion_s);

%% ================================================================
% ESTADO INICIAL
% ================================================================

x = zeros( ...
    modelo.numeroEstados, ...
    1 ...
);

% Marco NED:
% zD negativa representa altura arriba del origen.

x(modelo.idx.zD) = -1.0;

%% ================================================================
% REFERENCIAS DEL CONTROLADOR
% ================================================================

% El dron debe permanecer nivelado.
%
% La inclinacion sera provocada exclusivamente por el momento externo.

comando.roll = 0;
comando.pitch = 0;
comando.yaw = 0;

comando.throttle = 0.50;

comando.armado = true;

%% ================================================================
% CREAR HISTORIALES
% ================================================================

historialEstado = zeros( ...
    numeroMuestras, ...
    modelo.numeroEstados ...
);

historialEstado(1, :) = ...
    x.';

historialReferenciaRoll_rad = zeros( ...
    numeroMuestras, ...
    1 ...
);

historialErrorRoll_rad = zeros( ...
    numeroMuestras, ...
    1 ...
);

historialMomentoControl_B_Nm = zeros( ...
    numeroMuestras, ...
    3 ...
);

historialMomentoRealMotores_B_Nm = zeros( ...
    numeroMuestras, ...
    3 ...
);

historialMomentoExterno_B_Nm = zeros( ...
    numeroMuestras, ...
    3 ...
);

historialEmpujeMotores_N = zeros( ...
    numeroMuestras, ...
    P.motores.numero ...
);

historialSaturacionControlador = false( ...
    numeroMuestras, ...
    1 ...
);

historialSaturacionMezclador = false( ...
    numeroMuestras, ...
    1 ...
);

%% ================================================================
% INICIALIZAR MOTORES EN HOVER
% ================================================================

empujeHoverTotal_N = ...
    P.cuerpo.masa * ...
    P.entorno.g;

[Uhover, Dhover] = mezclador_motores_x( ...
    empujeHoverTotal_N, ...
    zeros(3, 1), ...
    P ...
);

historialEmpujeMotores_N(1, :) = ...
    Uhover.empujeMotores_N.';

historialMomentoRealMotores_B_Nm(1, :) = ...
    Dhover.momentoReal_B_Nm.';

%% ================================================================
% SIMULACION
% ================================================================

fprintf('Ejecutando simulacion del caso real...\n\n');

for k = 1:numeroPasos

    t = ...
        tiempo_s(k);

    %% Perturbacion externa

    E = perturbacion_pulso_actitud( ...
        t, ...
        ejePerturbacion, ...
        momentoPerturbacion_Nm, ...
        inicioPerturbacion_s, ...
        duracionPerturbacion_s ...
    );

    %% Controlador de actitud

    [ ...
        momentoDeseado_B_Nm, ...
        estadoControl, ...
        Dcontrol ...
    ] = controlador_actitud( ...
        comando, ...
        x, ...
        dt, ...
        Ccontrol, ...
        estadoControl, ...
        modelo ...
    );

    %% Compensacion aproximada del empuje vertical

    phi_rad = ...
        x(modelo.idx.phi);

    theta_rad = ...
        x(modelo.idx.theta);

    factorVertical = ...
        cos(phi_rad) * ...
        cos(theta_rad);

    factorVertical = max( ...
        factorVertical, ...
        0.65 ...
    );

    empujeTotal_N = ...
        P.cuerpo.masa * ...
        P.entorno.g / ...
        factorVertical;

    %% Mezclador real

    [U, Dmezclador] = mezclador_motores_x( ...
        empujeTotal_N, ...
        momentoDeseado_B_Nm, ...
        P ...
    );

    %% Integracion temporal con RK4

    x = paso_rk4( ...
        @modelo_no_lineal_12_estados, ...
        t, ...
        x, ...
        dt, ...
        U, ...
        E, ...
        P, ...
        modelo ...
    );

    %% Guardar resultados

    historialEstado(k + 1, :) = ...
        x.';

    historialReferenciaRoll_rad(k + 1) = ...
        Dcontrol.referencia.phi_rad;

    historialErrorRoll_rad(k + 1) = ...
        Dcontrol.error.roll_rad;

    historialMomentoControl_B_Nm(k + 1, :) = ...
        momentoDeseado_B_Nm.';

    historialMomentoRealMotores_B_Nm(k + 1, :) = ...
        Dmezclador.momentoReal_B_Nm.';

    historialMomentoExterno_B_Nm(k + 1, :) = ...
        E.momentoExterno_B_Nm.';

    historialEmpujeMotores_N(k + 1, :) = ...
        U.empujeMotores_N.';

    diferenciaSaturacionControl = ...
        Dcontrol.momentoSinSaturar_B_Nm - ...
        Dcontrol.momentoSaturado_B_Nm;

    historialSaturacionControlador(k + 1) = ...
        any( ...
            abs(diferenciaSaturacionControl) > 1e-12 ...
        );

    historialSaturacionMezclador(k + 1) = ...
        Dmezclador.huboSaturacion;

end

%% ================================================================
% PROCESAR RESULTADOS
% ================================================================

roll_rad = ...
    historialEstado(:, modelo.idx.phi);

velocidadRoll_rad_s = ...
    historialEstado(:, modelo.idx.p);

roll_deg = ...
    rad2deg(roll_rad);

velocidadRoll_deg_s = ...
    rad2deg(velocidadRoll_rad_s);

referenciaRoll_deg = ...
    rad2deg(historialReferenciaRoll_rad);

errorRoll_deg = ...
    rad2deg(historialErrorRoll_rad);

momentoControlRoll_Nm = ...
    historialMomentoControl_B_Nm(:, 1);

momentoRealMotoresRoll_Nm = ...
    historialMomentoRealMotores_B_Nm(:, 1);

momentoExternoRoll_Nm = ...
    historialMomentoExterno_B_Nm(:, 1);

%% ================================================================
% CALCULAR INDICADORES
% ================================================================

indicesDesdePerturbacion = ...
    tiempo_s >= inicioPerturbacion_s;

indicesDespuesPulso = ...
    tiempo_s >= finPerturbacion_s;

%% Desviacion maxima

[desviacionMaxima_deg, indicePicoRelativo] = max( ...
    abs( ...
        roll_deg(indicesDesdePerturbacion) ...
    ) ...
);

indicesGlobales = find( ...
    indicesDesdePerturbacion ...
);

indicePico = ...
    indicesGlobales(indicePicoRelativo);

tiempoPico_s = ...
    tiempo_s(indicePico);

rollEnPico_deg = ...
    roll_deg(indicePico);

%% Rebote contrario

if rollEnPico_deg >= 0

    rollContrario_deg = min( ...
        roll_deg(indicePico:end) ...
    );

    reboteContrario_deg = max( ...
        0, ...
        -rollContrario_deg ...
    );

else

    rollContrario_deg = max( ...
        roll_deg(indicePico:end) ...
    );

    reboteContrario_deg = max( ...
        0, ...
        rollContrario_deg ...
    );

end

%% Tiempo de establecimiento

limiteRollEstable_deg = max( ...
    0.25, ...
    0.02 * desviacionMaxima_deg ...
);

limiteVelocidadEstable_deg_s = 0.50;

tiempoEstablecimiento_s = NaN;

indicesBusqueda = find( ...
    indicesDespuesPulso ...
);

for i = 1:numel(indicesBusqueda)

    indiceActual = ...
        indicesBusqueda(i);

    rollPermaneceEstable = all( ...
        abs(roll_deg(indiceActual:end)) <= ...
        limiteRollEstable_deg ...
    );

    velocidadPermaneceEstable = all( ...
        abs(velocidadRoll_deg_s(indiceActual:end)) <= ...
        limiteVelocidadEstable_deg_s ...
    );

    if rollPermaneceEstable && ...
            velocidadPermaneceEstable

        tiempoEstablecimiento_s = ...
            tiempo_s(indiceActual) - ...
            finPerturbacion_s;

        break;

    end

end

%% Esfuerzo de control y motores

momentoControlMaximo_Nm = max( ...
    abs(momentoControlRoll_Nm) ...
);

momentoRealMotoresMaximo_Nm = max( ...
    abs(momentoRealMotoresRoll_Nm) ...
);

diferenciaEmpujeMotores_N = ...
    max(historialEmpujeMotores_N, [], 2) - ...
    min(historialEmpujeMotores_N, [], 2);

diferenciaEmpujeMotoresMax_N = max( ...
    diferenciaEmpujeMotores_N ...
);

huboSaturacionControlador = any( ...
    historialSaturacionControlador ...
);

huboSaturacionMezclador = any( ...
    historialSaturacionMezclador ...
);

porcentajeMomentoUtilizado = ...
    100 * ...
    momentoControlMaximo_Nm / ...
    Ccontrol.limites.momentoRollMax_Nm;

%% Estado final

rollFinal_deg = ...
    roll_deg(end);

velocidadRollFinal_deg_s = ...
    velocidadRoll_deg_s(end);

%% ================================================================
% VERIFICACIONES AUTOMATICAS
% ================================================================

assert( ...
    all(isfinite(historialEstado), 'all'), ...
    ['La simulacion real produjo valores NaN o infinitos. ' ...
     'Revisa los parametros fisicos.'] ...
);

assert( ...
    desviacionMaxima_deg > 0.50, ...
    ['La perturbacion real no produjo una desviacion ' ...
     'angular apreciable.'] ...
);

assert( ...
    desviacionMaxima_deg < 20.0, ...
    ['El dron real V1 alcanzo una inclinacion demasiado ' ...
     'grande para esta perturbacion.'] ...
);

assert( ...
    momentoControlMaximo_Nm > 1e-5, ...
    ['El controlador real no produjo una correccion ' ...
     'apreciable en roll.'] ...
);

assert( ...
    min(momentoControlRoll_Nm) < -1e-5, ...
    ['El controlador no genero un momento contrario a la ' ...
     'perturbacion positiva de roll.'] ...
);

assert( ...
    min(momentoRealMotoresRoll_Nm) < -1e-5, ...
    ['Los motores no produjeron realmente un momento ' ...
     'correctivo negativo en roll.'] ...
);

assert( ...
    abs(rollFinal_deg) < 0.50, ...
    ['El roll del caso real no regreso suficientemente ' ...
     'cerca de cero.'] ...
);

assert( ...
    abs(velocidadRollFinal_deg_s) < 0.50, ...
    ['La velocidad angular final del caso real es ' ...
     'demasiado grande.'] ...
);

assert( ...
    isfinite(tiempoEstablecimiento_s), ...
    ['El caso real no alcanzo la banda de establecimiento ' ...
     'antes de terminar la simulacion.'] ...
);

%% ================================================================
% GUARDAR ESTRUCTURA COMPATIBLE CON LAS GRAFICAS EXISTENTES
% ================================================================

resultados.meta.nombre = ...
    "Rechazo de perturbacion en roll - KIWO E88 real V1";

resultados.meta.caso = ...
    caso.meta.nombre;

resultados.configuracion.dt_s = ...
    dt;

resultados.configuracion.tiempoFinal_s = ...
    tiempoFinal_s;

resultados.configuracion.ejePerturbacion = ...
    ejePerturbacion;

resultados.configuracion.momentoPerturbacion_Nm = ...
    momentoPerturbacion_Nm;

resultados.configuracion.inicioPerturbacion_s = ...
    inicioPerturbacion_s;

resultados.configuracion.duracionPerturbacion_s = ...
    duracionPerturbacion_s;

resultados.configuracion.finPerturbacion_s = ...
    finPerturbacion_s;

resultados.tiempo_s = ...
    tiempo_s;

resultados.estado = ...
    historialEstado;

resultados.roll_deg = ...
    roll_deg;

resultados.velocidadRoll_deg_s = ...
    velocidadRoll_deg_s;

resultados.referenciaRoll_deg = ...
    referenciaRoll_deg;

resultados.errorRoll_deg = ...
    errorRoll_deg;

resultados.momentoControl_B_Nm = ...
    historialMomentoControl_B_Nm;

resultados.momentoRealMotores_B_Nm = ...
    historialMomentoRealMotores_B_Nm;

resultados.momentoExterno_B_Nm = ...
    historialMomentoExterno_B_Nm;

resultados.empujeMotores_N = ...
    historialEmpujeMotores_N;

resultados.metricas.desviacionMaxima_deg = ...
    desviacionMaxima_deg;

resultados.metricas.tiempoPico_s = ...
    tiempoPico_s;

resultados.metricas.rollEnPico_deg = ...
    rollEnPico_deg;

resultados.metricas.reboteContrario_deg = ...
    reboteContrario_deg;

resultados.metricas.tiempoEstablecimiento_s = ...
    tiempoEstablecimiento_s;

resultados.metricas.limiteRollEstable_deg = ...
    limiteRollEstable_deg;

resultados.metricas.momentoControlMaximo_Nm = ...
    momentoControlMaximo_Nm;

resultados.metricas.momentoRealMotoresMaximo_Nm = ...
    momentoRealMotoresMaximo_Nm;

resultados.metricas.diferenciaEmpujeMotoresMax_N = ...
    diferenciaEmpujeMotoresMax_N;

resultados.metricas.porcentajeMomentoUtilizado = ...
    porcentajeMomentoUtilizado;

resultados.metricas.rollFinal_deg = ...
    rollFinal_deg;

resultados.metricas.velocidadRollFinal_deg_s = ...
    velocidadRollFinal_deg_s;

resultados.metricas.huboSaturacionControlador = ...
    huboSaturacionControlador;

resultados.metricas.huboSaturacionMezclador = ...
    huboSaturacionMezclador;

%% ================================================================
% MOSTRAR RESULTADOS
% ================================================================

fprintf('============================================================\n');
fprintf(' RESULTADOS DEL KIWO E88 REAL V1\n');
fprintf('============================================================\n\n');

fprintf('Respuesta angular:\n');
fprintf('  Desviacion maxima:          %.3f grados\n', ...
    desviacionMaxima_deg);

fprintf('  Instante del pico:          %.3f s\n', ...
    tiempoPico_s);

fprintf('  Roll en el pico:            %.3f grados\n', ...
    rollEnPico_deg);

fprintf('  Rebote contrario:           %.3f grados\n', ...
    reboteContrario_deg);

fprintf('  Tiempo de establecimiento:  %.3f s\n', ...
    tiempoEstablecimiento_s);

fprintf('  Banda de establecimiento:   +/- %.3f grados\n', ...
    limiteRollEstable_deg);

fprintf('  Roll final:                 %.3f grados\n', ...
    rollFinal_deg);

fprintf('  Velocidad final:            %.3f grados/s\n\n', ...
    velocidadRollFinal_deg_s);

fprintf('Esfuerzo de control:\n');
fprintf('  Momento PID maximo:         %.6f N*m\n', ...
    momentoControlMaximo_Nm);

fprintf('  Momento real motores max:   %.6f N*m\n', ...
    momentoRealMotoresMaximo_Nm);

fprintf('  Limite disponible roll:     %.6f N*m\n', ...
    Ccontrol.limites.momentoRollMax_Nm);

fprintf('  Autoridad utilizada:        %.2f %%\n', ...
    porcentajeMomentoUtilizado);

fprintf('  Diferencia maxima motores:  %.6f N\n', ...
    diferenciaEmpujeMotoresMax_N);

fprintf('  Saturacion controlador:     %s\n', ...
    string(huboSaturacionControlador));

fprintf('  Saturacion mezclador:       %s\n\n', ...
    string(huboSaturacionMezclador));

fprintf('============================================================\n');
fprintf(' PRUEBA APROBADA\n');
fprintf(' EL KIWO E88 REAL V1 RECHAZA LA PERTURBACION EN ROLL\n');
fprintf('============================================================\n\n');

fprintf('NOTA:\n');
fprintf(['  Esta prueba utiliza parametros medidos y estimados.\n' ...
         '  Se debera repetir cuando se mida el empuje real y\n' ...
         '  se refine el tensor de inercia.\n\n']);

%% ================================================================
% USAR LA GRAFICA DE ROLL QUE YA TENEMOS
% ================================================================

if exist( ...
        'graficar_rechazo_perturbacion', ...
        'file' ...
    ) == 2

    graficar_rechazo_perturbacion( ...
        resultados ...
    );

else

    fprintf( ...
        ['No se encontro graficar_rechazo_perturbacion.m.\n' ...
         'La simulacion real fue ejecutada correctamente.\n\n'] ...
    );

end