%% TEST_CONTROL_TRASLACIONAL_CERRADO_REAL
% Prueba cerrada del controlador traslacional usando el modelo
% físico del KIWO E88 real V1.
%
% Secuencia:
%
%   0 a 2 s:
%       Hover a 1 metro.
%
%   2 a 4 s:
%       Movimiento manual hacia adelante.
%
%   4 s:
%       Se libera el mando horizontal.
%
%   4 a 7 s:
%       Frenado y mantenimiento de la posición alcanzada.
%
%   7 s:
%       Se ordena una altura absoluta de 2 metros.
%
%   7 a 15 s:
%       Ascenso y mantenimiento de altura.
%
% Esta prueba valida la integración de:
%
%   controlador_traslacional
%           ↓
%   controlador_actitud
%           ↓
%   mezclador_motores_x
%           ↓
%   modelo_no_lineal_12_estados
%           ↓
%   paso_rk4

clearvars;
clc;
close all;

fprintf('\n');
fprintf('============================================================\n');
fprintf(' CONTROL TRASLACIONAL CERRADO - KIWO E88 REAL V1\n');
fprintf('============================================================\n\n');

%% ================================================================
% CARGAR MODELO Y PARÁMETROS
% ================================================================

modelo = definicion_modelo();

P = parametros_fisicos();

Cdiseno = parametros_diseno();

R = reglas_competencia();

[P, Cdiseno, casoReal] = caso_real_dron( ...
    P, ...
    Cdiseno, ...
    R ...
);

reporteFisico = validar_parametros_fisicos(P);

if ~reporteFisico.completo

    error( ...
        'test_control_traslacional_cerrado_real:ParametrosInvalidos', ...
        'Los parámetros físicos del caso real no son válidos.' ...
    );

end

Cactitud = parametros_control_actitud(P);

Ctraslacional = parametros_control_traslacional( ...
    P, ...
    Cactitud ...
);

%% ================================================================
% CONFIGURACIÓN TEMPORAL
% ================================================================

dt = 0.005;

tiempoFinal_s = 15.0;

numeroPasos = round( ...
    tiempoFinal_s / dt ...
);

tiempo_s = ...
    (0:numeroPasos).' * dt;

numeroMuestras = ...
    numeroPasos + 1;

%% ================================================================
% SECUENCIA DE PRUEBA
% ================================================================

inicioMovimientoManual_s = ...
    2.0;

finMovimientoManual_s = ...
    4.0;

instanteOrdenAltura_s = ...
    7.0;

alturaInicial_m = ...
    1.0;

alturaObjetivo_m = ...
    2.0;

mandoAdelantePrueba = ...
    0.80;

fprintf('Caso físico:\n');
fprintf('  %s\n\n', casoReal.meta.nombre);

fprintf('Secuencia:\n');
fprintf('  Hover inicial:          %.2f m\n', ...
    alturaInicial_m);

fprintf('  Movimiento manual:      %.2f a %.2f s\n', ...
    inicioMovimientoManual_s, ...
    finMovimientoManual_s);

fprintf('  Mando hacia adelante:   %.2f\n', ...
    mandoAdelantePrueba);

fprintf('  Orden de altura:        %.2f m en t = %.2f s\n\n', ...
    alturaObjetivo_m, ...
    instanteOrdenAltura_s);

%% ================================================================
% ESTADO INICIAL
% ================================================================

x = zeros( ...
    modelo.numeroEstados, ...
    1 ...
);

x(modelo.idx.zD) = ...
    -alturaInicial_m;

%% ================================================================
% MEMORIAS DE LOS CONTROLADORES
% ================================================================

memoriaTraslacional = [];

memoriaActitud = [];

ordenAlturaEnviada = false;

%% ================================================================
% CREAR HISTORIALES
% ================================================================

historialEstado = zeros( ...
    numeroMuestras, ...
    modelo.numeroEstados ...
);

historialEstado(1, :) = ...
    x.';

historialPosicionObjetivo_NE_m = zeros( ...
    numeroMuestras, ...
    2 ...
);

historialAlturaObjetivo_m = zeros( ...
    numeroMuestras, ...
    1 ...
);

historialVelocidadReferencia_NE_m_s = zeros( ...
    numeroMuestras, ...
    2 ...
);

historialVelocidadUpReferencia_m_s = zeros( ...
    numeroMuestras, ...
    1 ...
);

historialAngulosReferencia_rad = zeros( ...
    numeroMuestras, ...
    2 ...
);

historialEmpujeTotal_N = zeros( ...
    numeroMuestras, ...
    1 ...
);

historialEmpujeMotores_N = zeros( ...
    numeroMuestras, ...
    P.motores.numero ...
);

historialMomentoDeseado_B_Nm = zeros( ...
    numeroMuestras, ...
    3 ...
);

historialMomentoReal_B_Nm = zeros( ...
    numeroMuestras, ...
    3 ...
);

historialModoHorizontal = strings( ...
    numeroMuestras, ...
    1 ...
);

historialModoHorizontal(1) = ...
    "INICIAL";

historialSaturacionHorizontal = false( ...
    numeroMuestras, ...
    1 ...
);

historialSaturacionVertical = false( ...
    numeroMuestras, ...
    1 ...
);

historialSaturacionEmpuje = false( ...
    numeroMuestras, ...
    1 ...
);

historialSaturacionMezclador = false( ...
    numeroMuestras, ...
    1 ...
);

%% ================================================================
% SIMULACIÓN CERRADA
% ================================================================

fprintf('Ejecutando simulación cerrada...\n\n');

for k = 1:numeroPasos

    t = ...
        tiempo_s(k);

    %% ------------------------------------------------------------
    % GENERAR REFERENCIA UNIVERSAL
    % -------------------------------------------------------------

    referencia = struct();

    referencia.armado = true;

    referencia.mandoAdelante = 0;
    referencia.mandoDerecha = 0;
    referencia.mandoAltura = 0;
    referencia.mandoYaw = 0;

    referencia.fijarAltura = false;
    referencia.alturaObjetivo_m = NaN;

    referencia.fijarPosicion = false;
    referencia.xObjetivo_m = NaN;
    referencia.yObjetivo_m = NaN;

    referencia.origen = ...
        "TEST CONTROL TRASLACIONAL CERRADO";

    %% Movimiento manual hacia adelante

    if t >= inicioMovimientoManual_s && ...
            t < finMovimientoManual_s

        referencia.mandoAdelante = ...
            mandoAdelantePrueba;

    end

    %% Orden absoluta de altura

    if ~ordenAlturaEnviada && ...
            t >= instanteOrdenAltura_s

        referencia.fijarAltura = true;

        referencia.alturaObjetivo_m = ...
            alturaObjetivo_m;

        ordenAlturaEnviada = true;

    end

    %% ------------------------------------------------------------
    % CONTROL TRASLACIONAL
    % -------------------------------------------------------------

    [ ...
        salidaTraslacional, ...
        memoriaTraslacional, ...
        Dtraslacional ...
    ] = controlador_traslacional( ...
        referencia, ...
        x, ...
        dt, ...
        P, ...
        Ctraslacional, ...
        Cactitud, ...
        memoriaTraslacional, ...
        modelo ...
    );

    %% ------------------------------------------------------------
    % CONTROL DE ACTITUD
    % -------------------------------------------------------------

    [ ...
        momentoDeseado_B_Nm, ...
        memoriaActitud, ...
        ~ ...
    ] = controlador_actitud( ...
        salidaTraslacional.comandoActitud, ...
        x, ...
        dt, ...
        Cactitud, ...
        memoriaActitud, ...
        modelo ...
    );

    %% ------------------------------------------------------------
    % MEZCLADOR
    % -------------------------------------------------------------

    [U, Dmezclador] = mezclador_motores_x( ...
        salidaTraslacional.empujeTotal_N, ...
        momentoDeseado_B_Nm, ...
        P ...
    );

    %% ------------------------------------------------------------
    % SIN PERTURBACIÓN EXTERNA
    % -------------------------------------------------------------

    E = perturbacion_nula();

    %% ------------------------------------------------------------
    % INTEGRACIÓN RK4
    % -------------------------------------------------------------

    x = paso_rk4( ...
        @modelo_no_lineal_12_estados, ...
        t, ...
        x, ...
        dt, ...
        U, ...
        E, ...
        P, ...
        modelo ...
    );

    %% ------------------------------------------------------------
    % GUARDAR RESULTADOS
    % -------------------------------------------------------------

    historialEstado(k + 1, :) = ...
        x.';

    historialPosicionObjetivo_NE_m(k + 1, :) = ...
        salidaTraslacional.posicionObjetivo_NE_m.';

    historialAlturaObjetivo_m(k + 1) = ...
        salidaTraslacional.alturaObjetivo_m;

    historialVelocidadReferencia_NE_m_s(k + 1, :) = ...
        Dtraslacional.referencia.velocidad_NE_m_s.';

    historialVelocidadUpReferencia_m_s(k + 1) = ...
        Dtraslacional.referencia.velocidadUp_m_s;

    historialAngulosReferencia_rad(k + 1, :) = [
        Dtraslacional.salida.phiReferencia_rad
        Dtraslacional.salida.thetaReferencia_rad
    ];

    historialEmpujeTotal_N(k + 1) = ...
        salidaTraslacional.empujeTotal_N;

    historialEmpujeMotores_N(k + 1, :) = ...
        U.empujeMotores_N.';

    historialMomentoDeseado_B_Nm(k + 1, :) = ...
        momentoDeseado_B_Nm.';

    historialMomentoReal_B_Nm(k + 1, :) = ...
        Dmezclador.momentoReal_B_Nm.';

    historialModoHorizontal(k + 1) = ...
        Dtraslacional.modoHorizontal;

    historialSaturacionHorizontal(k + 1) = ...
        Dtraslacional.saturacion.horizontal;

    historialSaturacionVertical(k + 1) = ...
        Dtraslacional.saturacion.aceleracionVertical;

    historialSaturacionEmpuje(k + 1) = ...
        Dtraslacional.saturacion.empuje;

    historialSaturacionMezclador(k + 1) = ...
        Dmezclador.huboSaturacion;

end

%% ================================================================
% CALCULAR VELOCIDADES EN NED
% ================================================================

historialVelocidadNED_m_s = zeros( ...
    numeroMuestras, ...
    3 ...
);

for k = 1:numeroMuestras

    estadoActual = ...
        historialEstado(k, :).';

    Kactual = cinematica_6dof( ...
        estadoActual, ...
        modelo ...
    );

    historialVelocidadNED_m_s(k, :) = ...
        Kactual.posicionDot_N.';

end

%% ================================================================
% PROCESAR VARIABLES
% ================================================================

posicionN_m = ...
    historialEstado(:, modelo.idx.xN);

posicionE_m = ...
    historialEstado(:, modelo.idx.yE);

altura_m = ...
    -historialEstado(:, modelo.idx.zD);

velocidadN_m_s = ...
    historialVelocidadNED_m_s(:, 1);

velocidadE_m_s = ...
    historialVelocidadNED_m_s(:, 2);

velocidadDown_m_s = ...
    historialVelocidadNED_m_s(:, 3);

velocidadUp_m_s = ...
    -velocidadDown_m_s;

velocidadHorizontal_m_s = sqrt( ...
    velocidadN_m_s.^2 + ...
    velocidadE_m_s.^2 ...
);

velocidadHorizontalReferencia_m_s = sqrt( ...
    historialVelocidadReferencia_NE_m_s(:, 1).^2 + ...
    historialVelocidadReferencia_NE_m_s(:, 2).^2 ...
);

roll_deg = rad2deg( ...
    historialEstado(:, modelo.idx.phi) ...
);

pitch_deg = rad2deg( ...
    historialEstado(:, modelo.idx.theta) ...
);

rollReferencia_deg = rad2deg( ...
    historialAngulosReferencia_rad(:, 1) ...
);

pitchReferencia_deg = rad2deg( ...
    historialAngulosReferencia_rad(:, 2) ...
);

%% ================================================================
% MÉTRICAS HORIZONTALES
% ================================================================

indicesMovimientoManual = ...
    tiempo_s >= inicioMovimientoManual_s & ...
    tiempo_s < finMovimientoManual_s;

indicesDespuesDeFrenado = ...
    tiempo_s >= finMovimientoManual_s + 2.0;

velocidadHorizontalMax_m_s = max( ...
    velocidadHorizontal_m_s(indicesMovimientoManual) ...
);

velocidadHorizontalFinal_m_s = ...
    velocidadHorizontal_m_s(end);

posicionFinal_NE_m = [
    posicionN_m(end)
    posicionE_m(end)
];

posicionObjetivoFinal_NE_m = ...
    historialPosicionObjetivo_NE_m(end, :).';

errorPosicionFinal_NE_m = ...
    posicionObjetivoFinal_NE_m - ...
    posicionFinal_NE_m;

normaErrorPosicionFinal_m = ...
    norm(errorPosicionFinal_NE_m);

velocidadMaxDespuesFrenado_m_s = max( ...
    velocidadHorizontal_m_s(indicesDespuesDeFrenado) ...
);

%% ================================================================
% MÉTRICAS DE ALTURA
% ================================================================

alturaFinal_m = ...
    altura_m(end);

errorAlturaFinal_m = ...
    alturaObjetivo_m - ...
    alturaFinal_m;

velocidadVerticalFinal_m_s = ...
    velocidadUp_m_s(end);

alturaMaxima_m = ...
    max(altura_m);

%% ================================================================
% MÉTRICAS DE SATURACIÓN
% ================================================================

porcentajeSaturacionHorizontal = ...
    100 * mean(historialSaturacionHorizontal);

porcentajeSaturacionVertical = ...
    100 * mean(historialSaturacionVertical);

porcentajeSaturacionEmpuje = ...
    100 * mean(historialSaturacionEmpuje);

porcentajeSaturacionMezclador = ...
    100 * mean(historialSaturacionMezclador);

%% ================================================================
% VERIFICACIONES AUTOMÁTICAS
% ================================================================

assert( ...
    all(isfinite(historialEstado), 'all'), ...
    'La simulación produjo valores NaN o infinitos.' ...
);

assert( ...
    any(historialModoHorizontal == "VELOCIDAD MANUAL"), ...
    'Nunca se activó el modo VELOCIDAD MANUAL.' ...
);

assert( ...
    any(historialModoHorizontal == "FRENADO"), ...
    'Nunca se activó el modo FRENADO.' ...
);

assert( ...
    any(historialModoHorizontal == "MANTENER POSICION"), ...
    'Nunca se activó el modo MANTENER POSICION.' ...
);

assert( ...
    velocidadHorizontalMax_m_s > 0.20, ...
    ['El dron no alcanzó una velocidad horizontal ' ...
     'apreciable durante el mando manual.'] ...
);

assert( ...
    velocidadHorizontalFinal_m_s < 0.10, ...
    ['El dron no se detuvo suficientemente después de ' ...
     'liberar el mando horizontal.'] ...
);

assert( ...
    normaErrorPosicionFinal_m < 0.15, ...
    ['El dron no mantuvo correctamente la posición ' ...
     'horizontal capturada.'] ...
);

assert( ...
    alturaMaxima_m > 1.70, ...
    'El dron no respondió correctamente a la orden de altura.' ...
);

assert( ...
    abs(errorAlturaFinal_m) < 0.10, ...
    'La altura final quedó demasiado lejos de la referencia.' ...
);

assert( ...
    abs(velocidadVerticalFinal_m_s) < 0.10, ...
    'La velocidad vertical final es demasiado grande.' ...
);

assert( ...
    max(abs(roll_deg)) < 30, ...
    'El roll superó un límite razonable durante la prueba.' ...
);

assert( ...
    max(abs(pitch_deg)) < 30, ...
    'El pitch superó un límite razonable durante la prueba.' ...
);

%% ================================================================
% MOSTRAR RESULTADOS
% ================================================================

fprintf('============================================================\n');
fprintf(' RESULTADOS DEL CONTROL TRASLACIONAL\n');
fprintf('============================================================\n\n');

fprintf('Movimiento horizontal:\n');

fprintf('  Velocidad horizontal máxima:      %.3f m/s\n', ...
    velocidadHorizontalMax_m_s);

fprintf('  Velocidad horizontal final:       %.4f m/s\n', ...
    velocidadHorizontalFinal_m_s);

fprintf('  Posición final Norte:              %.3f m\n', ...
    posicionFinal_NE_m(1));

fprintf('  Posición final Este:               %.3f m\n', ...
    posicionFinal_NE_m(2));

fprintf('  Objetivo final Norte:              %.3f m\n', ...
    posicionObjetivoFinal_NE_m(1));

fprintf('  Objetivo final Este:               %.3f m\n', ...
    posicionObjetivoFinal_NE_m(2));

fprintf('  Error horizontal final:            %.4f m\n\n', ...
    normaErrorPosicionFinal_m);

fprintf('Control de altura:\n');

fprintf('  Altura inicial:                    %.3f m\n', ...
    alturaInicial_m);

fprintf('  Altura ordenada:                   %.3f m\n', ...
    alturaObjetivo_m);

fprintf('  Altura máxima:                     %.3f m\n', ...
    alturaMaxima_m);

fprintf('  Altura final:                      %.3f m\n', ...
    alturaFinal_m);

fprintf('  Error de altura final:             %.4f m\n', ...
    errorAlturaFinal_m);

fprintf('  Velocidad vertical final:          %.4f m/s\n\n', ...
    velocidadVerticalFinal_m_s);

fprintf('Saturaciones:\n');

fprintf('  Control horizontal:                %.2f %%\n', ...
    porcentajeSaturacionHorizontal);

fprintf('  Aceleración vertical:              %.2f %%\n', ...
    porcentajeSaturacionVertical);

fprintf('  Empuje colectivo:                  %.2f %%\n', ...
    porcentajeSaturacionEmpuje);

fprintf('  Mezclador de motores:              %.2f %%\n\n', ...
    porcentajeSaturacionMezclador);

fprintf('============================================================\n');
fprintf(' PRUEBA APROBADA\n');
fprintf(' EL DRON FRENA, MANTIENE POSICIÓN Y CONTROLA ALTURA\n');
fprintf('============================================================\n\n');

%% ================================================================
% GRÁFICAS
% ================================================================

% Se utiliza SUBPLOT en lugar de TILEDLAYOUT para mantener
% compatibilidad con versiones anteriores de MATLAB.

figura = figure( ...
    'Name', ...
    'Control traslacional cerrado - KIWO E88 real V1', ...
    'NumberTitle', ...
    'off', ...
    'Color', ...
    'w', ...
    'Visible', ...
    'on', ...
    'WindowStyle', ...
    'normal' ...
);

clf(figura);

%% ================================================================
% 1. POSICIÓN HORIZONTAL NORTE
% ================================================================

ax1 = subplot(3, 2, 1, ...
    'Parent', figura);

plot( ...
    ax1, ...
    tiempo_s, ...
    posicionN_m, ...
    'LineWidth', ...
    1.5 ...
);

hold(ax1, 'on');

plot( ...
    ax1, ...
    tiempo_s, ...
    historialPosicionObjetivo_NE_m(:, 1), ...
    '--', ...
    'LineWidth', ...
    1.2 ...
);

grid(ax1, 'on');
box(ax1, 'on');

xlabel(ax1, 'Tiempo [s]');
ylabel(ax1, 'Norte [m]');
title(ax1, 'Posición horizontal Norte');

legend( ...
    ax1, ...
    'Posición real', ...
    'Posición objetivo', ...
    'Location', ...
    'best' ...
);

%% ================================================================
% 2. VELOCIDAD HORIZONTAL
% ================================================================

ax2 = subplot(3, 2, 2, ...
    'Parent', figura);

plot( ...
    ax2, ...
    tiempo_s, ...
    velocidadHorizontal_m_s, ...
    'LineWidth', ...
    1.5 ...
);

hold(ax2, 'on');

plot( ...
    ax2, ...
    tiempo_s, ...
    velocidadHorizontalReferencia_m_s, ...
    '--', ...
    'LineWidth', ...
    1.2 ...
);

grid(ax2, 'on');
box(ax2, 'on');

xlabel(ax2, 'Tiempo [s]');
ylabel(ax2, 'Velocidad [m/s]');
title(ax2, 'Frenado horizontal');

legend( ...
    ax2, ...
    'Velocidad real', ...
    'Velocidad objetivo', ...
    'Location', ...
    'best' ...
);

%% ================================================================
% 3. ALTURA
% ================================================================

ax3 = subplot(3, 2, 3, ...
    'Parent', figura);

plot( ...
    ax3, ...
    tiempo_s, ...
    altura_m, ...
    'LineWidth', ...
    1.5 ...
);

hold(ax3, 'on');

plot( ...
    ax3, ...
    tiempo_s, ...
    historialAlturaObjetivo_m, ...
    '--', ...
    'LineWidth', ...
    1.2 ...
);

grid(ax3, 'on');
box(ax3, 'on');

xlabel(ax3, 'Tiempo [s]');
ylabel(ax3, 'Altura [m]');
title(ax3, 'Control de altura');

legend( ...
    ax3, ...
    'Altura real', ...
    'Altura objetivo', ...
    'Location', ...
    'best' ...
);

%% ================================================================
% 4. VELOCIDAD VERTICAL
% ================================================================

ax4 = subplot(3, 2, 4, ...
    'Parent', figura);

plot( ...
    ax4, ...
    tiempo_s, ...
    velocidadUp_m_s, ...
    'LineWidth', ...
    1.5 ...
);

hold(ax4, 'on');

plot( ...
    ax4, ...
    tiempo_s, ...
    historialVelocidadUpReferencia_m_s, ...
    '--', ...
    'LineWidth', ...
    1.2 ...
);

grid(ax4, 'on');
box(ax4, 'on');

xlabel(ax4, 'Tiempo [s]');
ylabel(ax4, 'Velocidad arriba [m/s]');
title(ax4, 'Velocidad vertical');

legend( ...
    ax4, ...
    'Velocidad real', ...
    'Velocidad objetivo', ...
    'Location', ...
    'best' ...
);

%% ================================================================
% 5. PITCH REAL Y DESEADO
% ================================================================

ax5 = subplot(3, 2, 5, ...
    'Parent', figura);

plot( ...
    ax5, ...
    tiempo_s, ...
    pitch_deg, ...
    'LineWidth', ...
    1.5 ...
);

hold(ax5, 'on');

plot( ...
    ax5, ...
    tiempo_s, ...
    pitchReferencia_deg, ...
    '--', ...
    'LineWidth', ...
    1.2 ...
);

grid(ax5, 'on');
box(ax5, 'on');

xlabel(ax5, 'Tiempo [s]');
ylabel(ax5, 'Pitch [grados]');
title(ax5, 'Pitch para avanzar y frenar');

legend( ...
    ax5, ...
    'Pitch real', ...
    'Pitch objetivo', ...
    'Location', ...
    'best' ...
);

%% ================================================================
% 6. EMPUJES INDIVIDUALES
% ================================================================

ax6 = subplot(3, 2, 6, ...
    'Parent', figura);

hold(ax6, 'on');

numeroMotores = size( ...
    historialEmpujeMotores_N, ...
    2 ...
);

for indiceMotor = 1:numeroMotores

    plot( ...
        ax6, ...
        tiempo_s, ...
        historialEmpujeMotores_N(:, indiceMotor), ...
        'LineWidth', ...
        1.1 ...
    );

end

grid(ax6, 'on');
box(ax6, 'on');

xlabel(ax6, 'Tiempo [s]');
ylabel(ax6, 'Empuje [N]');
title(ax6, 'Empuje individual de motores');

legend( ...
    ax6, ...
    'Motor 1', ...
    'Motor 2', ...
    'Motor 3', ...
    'Motor 4', ...
    'Location', ...
    'best' ...
);

%% ================================================================
% AJUSTES FINALES
% ================================================================

set( ...
    [ax1, ax2, ax3, ax4, ax5, ax6], ...
    'FontSize', ...
    9 ...
);

set( ...
    figura, ...
    'Position', ...
    [80, 60, 1300, 780] ...
);

drawnow;

figure(figura);

shg;

fprintf( ...
    'Se crearon %d ejes y %d líneas en la figura.\n', ...
    numel(findall(figura, 'Type', 'axes')), ...
    numel(findall(figura, 'Type', 'line')) ...
);