%% TEST_ENTRADA_TECLADO
% Comprueba la lectura simultánea y normalizada del teclado.

clearvars;
clc;
close all;

%% Crear ventana

figura = figure( ...
    'Name', 'Prueba de entrada por teclado', ...
    'NumberTitle', 'off', ...
    'Color', 'white', ...
    'Position', [400, 200, 620, 500], ...
    'WindowKeyPressFcn', @tecla_presionada, ...
    'WindowKeyReleaseFcn', @tecla_liberada, ...
    'CloseRequestFcn', @cerrar_ventana ...
);

setappdata(figura, ...
    "estadoTeclado", crear_estado_teclado());

%% Texto dinámico

panelTexto = uicontrol( ...
    figura, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.05, 0.05, 0.90, 0.90], ...
    'BackgroundColor', 'white', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Consolas', ...
    'FontSize', 13 ...
);

%% Ciclo de lectura

while isgraphics(figura)

    comando = leer_comando_teclado(figura);

    if comando.armado
    textoArmado = 'ARMADO';
    else
        textoArmado = 'DESARMADO';
    end
    
    texto = sprintf([ ...
        'PRUEBA DE ENTRADA POR TECLADO\n\n' ...
        'Haz clic dentro de esta ventana.\n\n' ...
        'W / S              Subir / bajar throttle\n' ...
        'Flecha izquierda    Roll a la izquierda\n' ...
        'Flecha derecha      Roll a la derecha\n' ...
        'Flecha arriba       Pitch hacia delante\n' ...
        'Flecha abajo        Pitch hacia atrás\n' ...
        'A / D               Yaw izquierda / derecha\n' ...
        'Espacio             Armar / desarmar\n' ...
        'R                   Solicitar reinicio\n' ...
        'Esc                 Cerrar prueba\n\n' ...
        '----------------------------------------\n\n' ...
        'Throttle : %6.2f\n' ...
        'Roll     : %6.2f\n' ...
        'Pitch    : %6.2f\n' ...
        'Yaw      : %6.2f\n\n' ...
        'Estado   : %s\n' ...
        'Reset    : %d\n' ...
        'Origen   : %s\n'], ...
        comando.throttle, ...
        comando.roll, ...
        comando.pitch, ...
        comando.yaw, ...
        textoArmado, ...
        comando.reset, ...
        char(comando.origen));

    set(panelTexto, 'String', texto);

    drawnow limitrate;

    if comando.salir
        delete(figura);
        break;
    end

    pause(0.01);

end


function cerrar_ventana(figura, ~)
%CERRAR_VENTANA Cierra la ventana de prueba.

    delete(figura);

end