%% TEST_MEZCLADOR_MOTORES_X
% Verifica la distribución de empuje y momentos para la configuración X.
%
% Pruebas:
%   1. Hover equilibrado.
%   2. Momento positivo de roll.
%   3. Momento positivo de pitch.
%   4. Momento positivo de yaw.
%   5. Comando combinado.

clearvars;
clc;
close all;

fprintf('\n');
fprintf('============================================================\n');
fprintf(' PRUEBAS DEL MEZCLADOR DE MOTORES EN X\n');
fprintf('============================================================\n\n');

%% Preparar el caso base

modelo = definicion_modelo();

P = parametros_fisicos();

R = reglas_competencia();

Dproyecto = requisitos_proyecto(R);

C = parametros_diseno();

[P, C, ~] = caso_base_teorico( ...
    P, ...
    C, ...
    R ...
);

G = configuracion_motores_x( ...
    R, ...
    Dproyecto, ...
    C.geometria.distanciaCentroMotor, ...
    C.geometria.zMotor_B ...
);

P = aplicar_configuracion_motores( ...
    P, ...
    G ...
);

%% Parámetros

masa = P.cuerpo.masa;

g = P.entorno.g;

empujeHover_N = masa * g;

tolerancia = 1e-10;

nombresMotores = [
    "M1"
    "M2"
    "M3"
    "M4"
];

ubicaciones = [
    "Frontal izquierdo"
    "Frontal derecho"
    "Trasero derecho"
    "Trasero izquierdo"
];

%% ================================================================
%  PRUEBA 1: HOVER
% ================================================================

momentoSolicitado = [
    0
    0
    0
];

[U_hover, D_hover] = mezclador_motores_x( ...
    empujeHover_N, ...
    momentoSolicitado, ...
    P ...
);

empujeEsperadoPorMotor = ...
    empujeHover_N / P.motores.numero;

assert( ...
    norm( ...
        U_hover.empujeMotores_N - ...
        empujeEsperadoPorMotor * ones(4, 1) ...
    ) < tolerancia, ...
    'Prueba 1 falló: el hover no quedó equilibrado.' ...
);

assert( ...
    norm(D_hover.momentoReal_B_Nm) < tolerancia, ...
    'Prueba 1 falló: aparecieron momentos durante hover.' ...
);

assert( ...
    ~D_hover.huboSaturacion, ...
    'Prueba 1 falló: el hover produjo saturación.' ...
);

fprintf('Prueba 1 aprobada: hover equilibrado.\n');

%% ================================================================
%  PRUEBA 2: ROLL POSITIVO
% ================================================================

momentoRoll_Nm = 0.05;

[U_roll, D_roll] = mezclador_motores_x( ...
    empujeHover_N, ...
    [momentoRoll_Nm; 0; 0], ...
    P ...
);

assert( ...
    abs( ...
        D_roll.momentoReal_B_Nm(1) - ...
        momentoRoll_Nm ...
    ) < tolerancia, ...
    'Prueba 2 falló: el momento de roll es incorrecto.' ...
);

assert( ...
    abs(D_roll.momentoReal_B_Nm(2)) < tolerancia, ...
    'Prueba 2 falló: apareció pitch no solicitado.' ...
);

assert( ...
    U_roll.empujeMotores_N(1) > ...
    U_roll.empujeMotores_N(2), ...
    'Prueba 2 falló: M1 debería superar a M2.' ...
);

assert( ...
    U_roll.empujeMotores_N(4) > ...
    U_roll.empujeMotores_N(3), ...
    'Prueba 2 falló: M4 debería superar a M3.' ...
);

fprintf('Prueba 2 aprobada: momento positivo de roll.\n');

%% ================================================================
%  PRUEBA 3: PITCH POSITIVO
% ================================================================

momentoPitch_Nm = 0.05;

[U_pitch, D_pitch] = mezclador_motores_x( ...
    empujeHover_N, ...
    [0; momentoPitch_Nm; 0], ...
    P ...
);

assert( ...
    abs( ...
        D_pitch.momentoReal_B_Nm(2) - ...
        momentoPitch_Nm ...
    ) < tolerancia, ...
    'Prueba 3 falló: el momento de pitch es incorrecto.' ...
);

assert( ...
    abs(D_pitch.momentoReal_B_Nm(1)) < tolerancia, ...
    'Prueba 3 falló: apareció roll no solicitado.' ...
);

assert( ...
    U_pitch.empujeMotores_N(1) > ...
    U_pitch.empujeMotores_N(4), ...
    'Prueba 3 falló: M1 debería superar a M4.' ...
);

assert( ...
    U_pitch.empujeMotores_N(2) > ...
    U_pitch.empujeMotores_N(3), ...
    'Prueba 3 falló: M2 debería superar a M3.' ...
);

fprintf('Prueba 3 aprobada: momento positivo de pitch.\n');

%% ================================================================
%  PRUEBA 4: YAW POSITIVO
% ================================================================

momentoYaw_Nm = 0.02;

[U_yaw, D_yaw] = mezclador_motores_x( ...
    empujeHover_N, ...
    [0; 0; momentoYaw_Nm], ...
    P ...
);

assert( ...
    abs( ...
        D_yaw.momentoReal_B_Nm(3) - ...
        momentoYaw_Nm ...
    ) < tolerancia, ...
    'Prueba 4 falló: el momento de yaw es incorrecto.' ...
);

assert( ...
    U_yaw.torqueReaccionMotores_Nm(1) > 0 && ...
    U_yaw.torqueReaccionMotores_Nm(3) > 0, ...
    'Prueba 4 falló: M1 y M3 deben producir yaw positivo.' ...
);

assert( ...
    abs(U_yaw.torqueReaccionMotores_Nm(2)) < tolerancia && ...
    abs(U_yaw.torqueReaccionMotores_Nm(4)) < tolerancia, ...
    'Prueba 4 falló: M2 y M4 no deben aportar yaw positivo.' ...
);

fprintf('Prueba 4 aprobada: momento positivo de yaw.\n');

%% ================================================================
%  PRUEBA 5: COMANDO COMBINADO
% ================================================================

momentoCombinado = [
     0.030
    -0.025
     0.015
];

[U_combinado, D_combinado] = mezclador_motores_x( ...
    empujeHover_N, ...
    momentoCombinado, ...
    P ...
);

assert( ...
    abs(D_combinado.errorEmpuje_N) < tolerancia, ...
    'Prueba 5 falló: el empuje total es incorrecto.' ...
);

assert( ...
    norm(D_combinado.errorMomento_B_Nm) < tolerancia, ...
    'Prueba 5 falló: el momento combinado es incorrecto.' ...
);

assert( ...
    ~D_combinado.huboSaturacion, ...
    'Prueba 5 falló: el comando combinado produjo saturación.' ...
);

fprintf('Prueba 5 aprobada: comando combinado.\n');

%% ================================================================
%  RESULTADOS
% ================================================================

fprintf('\n');
fprintf('------------------------------------------------------------\n');
fprintf(' RESULTADOS DEL COMANDO COMBINADO\n');
fprintf('------------------------------------------------------------\n\n');

tablaResultados = table( ...
    nombresMotores, ...
    ubicaciones, ...
    U_combinado.empujeMotores_N, ...
    U_combinado.torqueReaccionMotores_Nm, ...
    'VariableNames', { ...
        'Motor', ...
        'Ubicacion', ...
        'Empuje_N', ...
        'TorqueReaccion_Nm'} ...
);

disp(tablaResultados);

fprintf('Empuje solicitado:        %.9f N\n', ...
    empujeHover_N);

fprintf('Empuje producido:         %.9f N\n\n', ...
    D_combinado.empujeReal_N);

fprintf('Momento solicitado:\n');
fprintf('  Mx = % .9f Nm\n', momentoCombinado(1));
fprintf('  My = % .9f Nm\n', momentoCombinado(2));
fprintf('  Mz = % .9f Nm\n\n', momentoCombinado(3));

fprintf('Momento producido:\n');
fprintf('  Mx = % .9f Nm\n', ...
    D_combinado.momentoReal_B_Nm(1));

fprintf('  My = % .9f Nm\n', ...
    D_combinado.momentoReal_B_Nm(2));

fprintf('  Mz = % .9f Nm\n\n', ...
    D_combinado.momentoReal_B_Nm(3));

fprintf('============================================================\n');
fprintf(' TODAS LAS PRUEBAS DEL MEZCLADOR APROBARON\n');
fprintf('============================================================\n');