%% TEST_RECHAZO_PERTURBACION_YAW
% Comprueba que el controlador de velocidad de yaw pueda rechazar
% un momento externo aplicado alrededor del eje Z_B.
%
% IMPORTANTE:
%
% El controlador actual no mantiene un angulo absoluto de yaw.
% Controla la velocidad angular:
%
%       r_ref = 0 rad/s
%
% Por tanto, despues de la perturbacion:
%
%   - El angulo yaw puede quedar desplazado.
%   - La velocidad angular r debe regresar a cero.
%
% Secuencia:
%
%   0.0 a 2.0 s:
%       Dron en hover y sin giro de yaw.
%
%   2.0 a 2.2 s:
%       Se aplica un momento externo positivo alrededor de Z_B.
%
%   2.2 a 8.0 s:
%       Se elimina la perturbacion y el controlador debe
%       detener la rotacion.

clearvars;
clc;
close all;

fprintf('\n');
fprintf('============================================================\n');
fprintf(' PRUEBA DE RECHAZO DE PERTURBACION EN YAW\n');
fprintf('============================================================\n\n');

%% ================================================================
% PREPARAR MODELO Y CASO BASE
% ================================================================

modelo = definicion_modelo();

P = parametros_fisicos();

R = reglas_competencia();

Dproyecto = requisitos_proyecto(R);

Cdiseno = parametros_diseno();

[P, Cdiseno, caso] = caso_base_teorico( ...
    P, ...
    Cdiseno, ...
    R ...
);

G = configuracion_motores_x( ...
    R, ...
    Dproyecto, ...
    Cdiseno.geometria.distanciaCentroMotor, ...
    Cdiseno.geometria.zMotor_B ...
);

P = aplicar_configuracion_motores(P, G);

%% ================================================================
% CONTROLADOR
% ================================================================

Ccontrol = parametros_control_actitud(P);

estadoControl = [];

%% ================================================================
% CONFIGURACION TEMPORAL
% ================================================================

dt = 0.005;

tiempoFinal_s = 8.0;

numeroPasos = round( ...
    tiempoFinal_s / dt ...
);

tiempo_s = ...
    (0:numeroPasos).' * dt;

%% ================================================================
% CONFIGURACION DE LA PERTURBACION
% ================================================================

ejePerturbacion = "yaw";

% Se utiliza una perturbacion menor que en roll y pitch porque
% el momento disponible de yaw es provisional y mas limitado.

momentoPerturbacion_Nm = 0.04;

inicioPerturbacion_s = 2.0;

duracionPerturbacion_s = 0.20;

finPerturbacion_s = ...
    inicioPerturbacion_s + ...
    duracionPerturbacion_s;

fprintf('Configuracion de la perturbacion:\n');
fprintf('  Eje:                    %s\n', ...
    ejePerturbacion);

fprintf('  Momento externo:        %.4f N*m\n', ...
    momentoPerturbacion_Nm);

fprintf('  Inicio:                 %.3f s\n', ...
    inicioPerturbacion_s);

fprintf('  Duracion:               %.3f s\n', ...
    duracionPerturbacion_s);

fprintf('  Fin:                    %.3f s\n\n', ...
    finPerturbacion_s);

%% ================================================================
% ESTADO INICIAL
% ================================================================

x = zeros( ...
    modelo.numeroEstados, ...
    1 ...
);

% Marco NED:
% zD negativa representa altura positiva.

x(modelo.idx.zD) = -1.0;

%% ================================================================
% COMANDO DEL CONTROLADOR
% ================================================================

comando.roll = 0;
comando.pitch = 0;

% comando.yaw = 0 significa:
%
% velocidad de yaw deseada = 0 rad/s

comando.yaw = 0;

comando.throttle = 0.50;

comando.armado = true;

%% ================================================================
% CREAR HISTORIALES
% ================================================================

historialEstado = zeros( ...
    numeroPasos + 1, ...
    modelo.numeroEstados ...
);

historialEstado(1, :) = ...
    x.';

historialReferenciaYawRate_rad_s = zeros( ...
    numeroPasos + 1, ...
    1 ...
);

historialErrorYawRate_rad_s = zeros( ...
    numeroPasos + 1, ...
    1 ...
);

historialMomentoControl_B_Nm = zeros( ...
    numeroPasos + 1, ...
    3 ...
);

historialMomentoExterno_B_Nm = zeros( ...
    numeroPasos + 1, ...
    3 ...
);

historialMomentoYawReal_Nm = zeros( ...
    numeroPasos + 1, ...
    1 ...
);

historialEmpujeMotores_N = zeros( ...
    numeroPasos + 1, ...
    P.motores.numero ...
);

historialTorqueReaccionMotores_Nm = zeros( ...
    numeroPasos + 1, ...
    P.motores.numero ...
);

historialSaturacionMezclador = false( ...
    numeroPasos + 1, ...
    1 ...
);

historialSaturacionControlador = false( ...
    numeroPasos + 1, ...
    1 ...
);

%% ================================================================
% SIMULACION
% ================================================================

fprintf('Ejecutando simulacion...\n\n');

for k = 1:numeroPasos

    t = tiempo_s(k);

    %% Perturbacion externa

    E = perturbacion_pulso_actitud( ...
        t, ...
        ejePerturbacion, ...
        momentoPerturbacion_Nm, ...
        inicioPerturbacion_s, ...
        duracionPerturbacion_s ...
    );

    %% Controlador de actitud

    [ ...
        momentoDeseado_B_Nm, ...
        estadoControl, ...
        Dcontrol ...
    ] = controlador_actitud( ...
        comando, ...
        x, ...
        dt, ...
        Ccontrol, ...
        estadoControl, ...
        modelo ...
    );

    %% Empuje colectivo para hover

    masa_kg = ...
        P.cuerpo.masa;

    gravedad_m_s2 = ...
        P.entorno.g;

    phi_rad = ...
        x(modelo.idx.phi);

    theta_rad = ...
        x(modelo.idx.theta);

    factorVertical = ...
        cos(phi_rad) * cos(theta_rad);

    factorVertical = max( ...
        factorVertical, ...
        0.65 ...
    );

    empujeTotal_N = ...
        masa_kg * gravedad_m_s2 / ...
        factorVertical;

    %% Mezclador de motores

    [U, Dmezclador] = mezclador_motores_x( ...
        empujeTotal_N, ...
        momentoDeseado_B_Nm, ...
        P ...
    );

    %% Momento real de yaw producido por los rotores

    momentoYawReal_Nm = sum( ...
        P.motores.signoTorqueYawCuerpo(:) .* ...
        U.torqueReaccionMotores_Nm(:) ...
    );

    %% Integracion del modelo con RK4

    x = paso_rk4( ...
        @modelo_no_lineal_12_estados, ...
        t, ...
        x, ...
        dt, ...
        U, ...
        E, ...
        P, ...
        modelo ...
    );

    %% Guardar resultados

    historialEstado(k + 1, :) = ...
        x.';

    historialReferenciaYawRate_rad_s(k + 1) = ...
        Dcontrol.referencia.r_rad_s;

    historialErrorYawRate_rad_s(k + 1) = ...
        Dcontrol.error.yawRate_rad_s;

    historialMomentoControl_B_Nm(k + 1, :) = ...
        momentoDeseado_B_Nm.';

    historialMomentoExterno_B_Nm(k + 1, :) = ...
        E.momentoExterno_B_Nm.';

    historialMomentoYawReal_Nm(k + 1) = ...
        momentoYawReal_Nm;

    historialEmpujeMotores_N(k + 1, :) = ...
        U.empujeMotores_N.';

    historialTorqueReaccionMotores_Nm(k + 1, :) = ...
        U.torqueReaccionMotores_Nm.';

    historialSaturacionMezclador(k + 1) = ...
        Dmezclador.huboSaturacion;

    diferenciaSaturacionControl = ...
        Dcontrol.momentoSinSaturar_B_Nm - ...
        Dcontrol.momentoSaturado_B_Nm;

    historialSaturacionControlador(k + 1) = ...
        any( ...
            abs(diferenciaSaturacionControl) > 1e-12 ...
        );

end

%% ================================================================
% CONVERTIR RESULTADOS
% ================================================================

yaw_rad = ...
    historialEstado(:, modelo.idx.psi);

velocidadYaw_rad_s = ...
    historialEstado(:, modelo.idx.r);

yaw_deg = ...
    rad2deg(yaw_rad);

velocidadYaw_deg_s = ...
    rad2deg(velocidadYaw_rad_s);

referenciaYawRate_deg_s = ...
    rad2deg(historialReferenciaYawRate_rad_s);

errorYawRate_deg_s = ...
    rad2deg(historialErrorYawRate_rad_s);

momentoControlYaw_Nm = ...
    historialMomentoControl_B_Nm(:, 3);

momentoExternoYaw_Nm = ...
    historialMomentoExterno_B_Nm(:, 3);

%% ================================================================
% CALCULAR INDICADORES
% ================================================================

indicesDesdePerturbacion = ...
    tiempo_s >= inicioPerturbacion_s;

indicesDespuesPulso = ...
    tiempo_s >= finPerturbacion_s;

%% Velocidad maxima de yaw

[velocidadYawMaxima_deg_s, indicePicoRelativo] = max( ...
    abs( ...
        velocidadYaw_deg_s(indicesDesdePerturbacion) ...
    ) ...
);

indicesGlobales = find( ...
    indicesDesdePerturbacion ...
);

indicePico = ...
    indicesGlobales(indicePicoRelativo);

tiempoPico_s = ...
    tiempo_s(indicePico);

velocidadYawEnPico_deg_s = ...
    velocidadYaw_deg_s(indicePico);

%% Rebote de velocidad en sentido contrario

if velocidadYawEnPico_deg_s >= 0

    velocidadContraria_deg_s = min( ...
        velocidadYaw_deg_s(indicePico:end) ...
    );

    reboteContrario_deg_s = max( ...
        0, ...
        -velocidadContraria_deg_s ...
    );

else

    velocidadContraria_deg_s = max( ...
        velocidadYaw_deg_s(indicePico:end) ...
    );

    reboteContrario_deg_s = max( ...
        0, ...
        velocidadContraria_deg_s ...
    );

end

%% Tiempo de establecimiento de la velocidad de yaw

limiteVelocidadYawEstable_deg_s = max( ...
    0.50, ...
    0.02 * velocidadYawMaxima_deg_s ...
);

tiempoEstablecimiento_s = NaN;

indicesBusqueda = find( ...
    indicesDespuesPulso ...
);

for i = 1:numel(indicesBusqueda)

    indiceActual = ...
        indicesBusqueda(i);

    velocidadPermaneceEstable = all( ...
        abs(velocidadYaw_deg_s(indiceActual:end)) <= ...
        limiteVelocidadYawEstable_deg_s ...
    );

    if velocidadPermaneceEstable

        tiempoEstablecimiento_s = ...
            tiempo_s(indiceActual) - ...
            finPerturbacion_s;

        break;

    end

end

%% Esfuerzo de control

momentoControlMaximo_Nm = max( ...
    abs(momentoControlYaw_Nm) ...
);

momentoYawRealMaximo_Nm = max( ...
    abs(historialMomentoYawReal_Nm) ...
);

torqueRotorMaximo_Nm = max( ...
    historialTorqueReaccionMotores_Nm, ...
    [], ...
    'all' ...
);

huboSaturacionMezclador = any( ...
    historialSaturacionMezclador ...
);

huboSaturacionControlador = any( ...
    historialSaturacionControlador ...
);

%% Estado final

yawFinal_deg = ...
    yaw_deg(end);

velocidadYawFinal_deg_s = ...
    velocidadYaw_deg_s(end);

errorYawRateFinal_deg_s = ...
    errorYawRate_deg_s(end);

%% ================================================================
% VERIFICACIONES AUTOMATICAS
% ================================================================

assert( ...
    all(isfinite(historialEstado), 'all'), ...
    ['La simulacion produjo valores NaN o infinitos. ' ...
     'Revisa el modelo o el controlador.'] ...
);

assert( ...
    velocidadYawMaxima_deg_s > 1.0, ...
    ['La perturbacion no produjo una velocidad de yaw ' ...
     'apreciable. Revisa que el momento se este aplicando.'] ...
);

assert( ...
    velocidadYawMaxima_deg_s < 180.0, ...
    ['La velocidad de yaw crecio demasiado. El controlador ' ...
     'podria ser inestable o la perturbacion muy grande.'] ...
);

assert( ...
    max(abs(yaw_deg)) > 0.10, ...
    ['La perturbacion no produjo un cambio apreciable ' ...
     'en el angulo de yaw.'] ...
);

assert( ...
    momentoControlMaximo_Nm > 0.001, ...
    ['El controlador no genero un momento correctivo ' ...
     'apreciable en yaw.'] ...
);

assert( ...
    min(momentoControlYaw_Nm) < -0.001, ...
    ['El controlador no produjo un momento negativo para ' ...
     'oponerse a la perturbacion positiva de yaw.'] ...
);

assert( ...
    abs(velocidadYawFinal_deg_s) < 0.50, ...
    ['La velocidad angular de yaw no regreso ' ...
     'suficientemente cerca de cero.'] ...
);

assert( ...
    abs(errorYawRateFinal_deg_s) < 0.50, ...
    ['El error final de velocidad de yaw es demasiado grande.'] ...
);

assert( ...
    isfinite(tiempoEstablecimiento_s), ...
    ['La velocidad de yaw no alcanzo la banda de ' ...
     'establecimiento antes de terminar la simulacion.'] ...
);

assert( ...
    momentoYawRealMaximo_Nm > 0.001, ...
    ['Los rotores no produjeron un momento real de yaw ' ...
     'apreciable.'] ...
);

%% ================================================================
% GUARDAR RESULTADOS
% ================================================================

resultadosYaw.meta.nombre = ...
    "Rechazo de perturbacion externa en yaw";

resultadosYaw.meta.caso = ...
    caso.meta.nombre;

resultadosYaw.configuracion.dt_s = ...
    dt;

resultadosYaw.configuracion.tiempoFinal_s = ...
    tiempoFinal_s;

resultadosYaw.configuracion.ejePerturbacion = ...
    ejePerturbacion;

resultadosYaw.configuracion.momentoPerturbacion_Nm = ...
    momentoPerturbacion_Nm;

resultadosYaw.configuracion.inicioPerturbacion_s = ...
    inicioPerturbacion_s;

resultadosYaw.configuracion.duracionPerturbacion_s = ...
    duracionPerturbacion_s;

resultadosYaw.configuracion.finPerturbacion_s = ...
    finPerturbacion_s;

resultadosYaw.tiempo_s = ...
    tiempo_s;

resultadosYaw.estado = ...
    historialEstado;

resultadosYaw.yaw_deg = ...
    yaw_deg;

resultadosYaw.velocidadYaw_deg_s = ...
    velocidadYaw_deg_s;

resultadosYaw.referenciaYawRate_deg_s = ...
    referenciaYawRate_deg_s;

resultadosYaw.errorYawRate_deg_s = ...
    errorYawRate_deg_s;

resultadosYaw.momentoControl_B_Nm = ...
    historialMomentoControl_B_Nm;

resultadosYaw.momentoExterno_B_Nm = ...
    historialMomentoExterno_B_Nm;

resultadosYaw.momentoYawReal_Nm = ...
    historialMomentoYawReal_Nm;

resultadosYaw.empujeMotores_N = ...
    historialEmpujeMotores_N;

resultadosYaw.torqueReaccionMotores_Nm = ...
    historialTorqueReaccionMotores_Nm;

resultadosYaw.metricas.velocidadYawMaxima_deg_s = ...
    velocidadYawMaxima_deg_s;

resultadosYaw.metricas.tiempoPico_s = ...
    tiempoPico_s;

resultadosYaw.metricas.velocidadYawEnPico_deg_s = ...
    velocidadYawEnPico_deg_s;

resultadosYaw.metricas.reboteContrario_deg_s = ...
    reboteContrario_deg_s;

resultadosYaw.metricas.tiempoEstablecimiento_s = ...
    tiempoEstablecimiento_s;

resultadosYaw.metricas.limiteVelocidadYawEstable_deg_s = ...
    limiteVelocidadYawEstable_deg_s;

resultadosYaw.metricas.momentoControlMaximo_Nm = ...
    momentoControlMaximo_Nm;

resultadosYaw.metricas.momentoYawRealMaximo_Nm = ...
    momentoYawRealMaximo_Nm;

resultadosYaw.metricas.torqueRotorMaximo_Nm = ...
    torqueRotorMaximo_Nm;

resultadosYaw.metricas.yawFinal_deg = ...
    yawFinal_deg;

resultadosYaw.metricas.velocidadYawFinal_deg_s = ...
    velocidadYawFinal_deg_s;

resultadosYaw.metricas.errorYawRateFinal_deg_s = ...
    errorYawRateFinal_deg_s;

resultadosYaw.metricas.huboSaturacionMezclador = ...
    huboSaturacionMezclador;

resultadosYaw.metricas.huboSaturacionControlador = ...
    huboSaturacionControlador;

%% ================================================================
% MOSTRAR RESULTADOS
% ================================================================

fprintf('Ganancias utilizadas en yaw rate:\n\n');

fprintf('  Kp = %.8f\n', ...
    Ccontrol.yaw.Kp);

fprintf('  Ki = %.8f\n', ...
    Ccontrol.yaw.Ki);

fprintf('  Kd = %.8f\n\n', ...
    Ccontrol.yaw.Kd);

fprintf('Resultados de la perturbacion:\n\n');

fprintf('  Velocidad maxima de yaw:    %.3f grados/s\n', ...
    velocidadYawMaxima_deg_s);

fprintf('  Instante del pico:          %.3f s\n', ...
    tiempoPico_s);

fprintf('  Velocidad en el pico:       %.3f grados/s\n', ...
    velocidadYawEnPico_deg_s);

fprintf('  Rebote contrario:           %.3f grados/s\n', ...
    reboteContrario_deg_s);

fprintf('  Tiempo de establecimiento:  %.3f s\n', ...
    tiempoEstablecimiento_s);

fprintf('  Banda de establecimiento:   +/- %.3f grados/s\n', ...
    limiteVelocidadYawEstable_deg_s);

fprintf('  Angulo yaw final:           %.3f grados\n', ...
    yawFinal_deg);

fprintf('  Velocidad yaw final:        %.3f grados/s\n', ...
    velocidadYawFinal_deg_s);

fprintf('  Error yaw rate final:       %.3f grados/s\n', ...
    errorYawRateFinal_deg_s);

fprintf('  Momento PID maximo:         %.4f N*m\n', ...
    momentoControlMaximo_Nm);

fprintf('  Momento yaw real maximo:    %.4f N*m\n', ...
    momentoYawRealMaximo_Nm);

fprintf('  Torque maximo por rotor:    %.4f N*m\n', ...
    torqueRotorMaximo_Nm);

fprintf('  Saturacion controlador:     %s\n', ...
    string(huboSaturacionControlador));

fprintf('  Saturacion mezclador:       %s\n\n', ...
    string(huboSaturacionMezclador));

fprintf('NOTA:\n');
fprintf(['  El angulo final de yaw no tiene que regresar a cero,\n' ...
         '  porque el controlador regula velocidad de yaw, no\n' ...
         '  orientacion absoluta. Lo importante es que r vuelva\n' ...
         '  aproximadamente a cero.\n\n']);

fprintf('============================================================\n');
fprintf(' PRUEBA APROBADA\n');
fprintf(' EL CONTROLADOR DETIENE LA PERTURBACION DE YAW\n');
fprintf('============================================================\n\n');

%% ================================================================
% GRAFICAS
% ================================================================

if exist( ...
        'graficar_rechazo_perturbacion_yaw', ...
        'file' ...
    ) == 2

    graficar_rechazo_perturbacion_yaw( ...
        resultadosYaw ...
    );

else

    fprintf( ...
        ['El archivo de graficas de yaw todavia no existe.\n' ...
         'La simulacion y las verificaciones ya fueron ejecutadas.\n\n'] ...
    );

end