%% TEST_RECHAZO_PERTURBACION_PITCH
% Comprueba que el controlador de actitud pueda rechazar un
% momento externo aplicado alrededor del eje de pitch.
%
% Secuencia:
%
%   0.0 a 2.0 s:
%       Dron en hover, nivelado y sin perturbaciones.
%
%   2.0 a 2.2 s:
%       Se aplica un momento externo positivo en pitch.
%
%   2.2 a 8.0 s:
%       Se elimina la perturbacion y el controlador debe
%       regresar el dron cerca de pitch = 0 grados.

clearvars;
clc;
close all;

fprintf('\n');
fprintf('============================================================\n');
fprintf(' PRUEBA DE RECHAZO DE PERTURBACION EN PITCH\n');
fprintf('============================================================\n\n');

%% ================================================================
% PREPARAR MODELO Y CASO BASE
% ================================================================

modelo = definicion_modelo();

P = parametros_fisicos();

R = reglas_competencia();

Dproyecto = requisitos_proyecto(R);

Cdiseno = parametros_diseno();

[P, Cdiseno, caso] = caso_base_teorico( ...
    P, ...
    Cdiseno, ...
    R ...
);

G = configuracion_motores_x( ...
    R, ...
    Dproyecto, ...
    Cdiseno.geometria.distanciaCentroMotor, ...
    Cdiseno.geometria.zMotor_B ...
);

P = aplicar_configuracion_motores(P, G);

%% ================================================================
% CONTROLADOR
% ================================================================

Ccontrol = parametros_control_actitud(P);

estadoControl = [];

%% ================================================================
% CONFIGURACION DE LA SIMULACION
% ================================================================

dt = 0.005;

tiempoFinal_s = 8.0;

numeroPasos = round( ...
    tiempoFinal_s / dt ...
);

tiempo_s = ...
    (0:numeroPasos).' * dt;

%% ================================================================
% CONFIGURACION DE LA PERTURBACION
% ================================================================

ejePerturbacion = "pitch";

momentoPerturbacion_Nm = 0.08;

inicioPerturbacion_s = 2.0;

duracionPerturbacion_s = 0.20;

finPerturbacion_s = ...
    inicioPerturbacion_s + ...
    duracionPerturbacion_s;

fprintf('Configuracion de la perturbacion:\n');
fprintf('  Eje:                    %s\n', ejePerturbacion);
fprintf('  Momento externo:        %.4f N*m\n', ...
    momentoPerturbacion_Nm);
fprintf('  Inicio:                 %.3f s\n', ...
    inicioPerturbacion_s);
fprintf('  Duracion:               %.3f s\n', ...
    duracionPerturbacion_s);
fprintf('  Fin:                    %.3f s\n\n', ...
    finPerturbacion_s);

%% ================================================================
% ESTADO INICIAL
% ================================================================

x = zeros( ...
    modelo.numeroEstados, ...
    1 ...
);

% Marco NED:
% zD negativa representa una posicion arriba del origen.

x(modelo.idx.zD) = -1.0;

%% ================================================================
% COMANDO DEL CONTROLADOR
% ================================================================

% Las referencias permanecen en cero.
% La inclinacion sera causada exclusivamente por la perturbacion.

comando.roll = 0;
comando.pitch = 0;
comando.yaw = 0;

comando.throttle = 0.50;

comando.armado = true;

%% ================================================================
% CREAR HISTORIALES
% ================================================================

historialEstado = zeros( ...
    numeroPasos + 1, ...
    modelo.numeroEstados ...
);

historialEstado(1, :) = x.';

historialReferenciaPitch_rad = zeros( ...
    numeroPasos + 1, ...
    1 ...
);

historialErrorPitch_rad = zeros( ...
    numeroPasos + 1, ...
    1 ...
);

historialMomentoControl_B_Nm = zeros( ...
    numeroPasos + 1, ...
    3 ...
);

historialMomentoExterno_B_Nm = zeros( ...
    numeroPasos + 1, ...
    3 ...
);

historialEmpujeMotores_N = zeros( ...
    numeroPasos + 1, ...
    P.motores.numero ...
);

historialSaturacionMezclador = false( ...
    numeroPasos + 1, ...
    1 ...
);

historialSaturacionControlador = false( ...
    numeroPasos + 1, ...
    1 ...
);

%% ================================================================
% SIMULACION
% ================================================================

fprintf('Ejecutando simulacion...\n\n');

for k = 1:numeroPasos

    t = tiempo_s(k);

    %% Perturbacion externa

    E = perturbacion_pulso_actitud( ...
        t, ...
        ejePerturbacion, ...
        momentoPerturbacion_Nm, ...
        inicioPerturbacion_s, ...
        duracionPerturbacion_s ...
    );

    %% Controlador de actitud

    [ ...
        momentoDeseado_B_Nm, ...
        estadoControl, ...
        Dcontrol ...
    ] = controlador_actitud( ...
        comando, ...
        x, ...
        dt, ...
        Ccontrol, ...
        estadoControl, ...
        modelo ...
    );

    %% Empuje colectivo para hover

    masa_kg = P.cuerpo.masa;

    gravedad_m_s2 = P.entorno.g;

    phi_rad = x(modelo.idx.phi);

    theta_rad = x(modelo.idx.theta);

    % Cuando el dron se inclina, una parte del empuje deja de
    % apuntar verticalmente. Esta compensacion mantiene aproximadamente
    % la componente vertical necesaria para hover.

    factorVertical = ...
        cos(phi_rad) * cos(theta_rad);

    factorVertical = max( ...
        factorVertical, ...
        0.65 ...
    );

    empujeTotal_N = ...
        masa_kg * gravedad_m_s2 / factorVertical;

    %% Mezclador de motores

    [U, Dmezclador] = mezclador_motores_x( ...
        empujeTotal_N, ...
        momentoDeseado_B_Nm, ...
        P ...
    );

    %% Integracion del modelo con RK4

    x = paso_rk4( ...
        @modelo_no_lineal_12_estados, ...
        t, ...
        x, ...
        dt, ...
        U, ...
        E, ...
        P, ...
        modelo ...
    );

    %% Guardar resultados

    historialEstado(k + 1, :) = ...
        x.';

    historialReferenciaPitch_rad(k + 1) = ...
        Dcontrol.referencia.theta_rad;

    historialErrorPitch_rad(k + 1) = ...
        Dcontrol.error.pitch_rad;

    historialMomentoControl_B_Nm(k + 1, :) = ...
        momentoDeseado_B_Nm.';

    historialMomentoExterno_B_Nm(k + 1, :) = ...
        E.momentoExterno_B_Nm.';

    historialEmpujeMotores_N(k + 1, :) = ...
        U.empujeMotores_N.';

    historialSaturacionMezclador(k + 1) = ...
        Dmezclador.huboSaturacion;

    diferenciaSaturacionControl = ...
        Dcontrol.momentoSinSaturar_B_Nm - ...
        Dcontrol.momentoSaturado_B_Nm;

    historialSaturacionControlador(k + 1) = ...
        any(abs(diferenciaSaturacionControl) > 1e-12);

end

%% ================================================================
% CONVERTIR RESULTADOS
% ================================================================

pitch_rad = ...
    historialEstado(:, modelo.idx.theta);

velocidadPitch_rad_s = ...
    historialEstado(:, modelo.idx.q);

pitch_deg = ...
    rad2deg(pitch_rad);

velocidadPitch_deg_s = ...
    rad2deg(velocidadPitch_rad_s);

referenciaPitch_deg = ...
    rad2deg(historialReferenciaPitch_rad);

errorPitch_deg = ...
    rad2deg(historialErrorPitch_rad);

momentoControlPitch_Nm = ...
    historialMomentoControl_B_Nm(:, 2);

momentoExternoPitch_Nm = ...
    historialMomentoExterno_B_Nm(:, 2);

%% ================================================================
% CALCULAR INDICADORES
% ================================================================

indicesDesdePerturbacion = ...
    tiempo_s >= inicioPerturbacion_s;

indicesDespuesPulso = ...
    tiempo_s >= finPerturbacion_s;

%% Desviacion maxima

[desviacionMaxima_deg, indicePicoRelativo] = max( ...
    abs(pitch_deg(indicesDesdePerturbacion)) ...
);

indicesGlobales = find( ...
    indicesDesdePerturbacion ...
);

indicePico = ...
    indicesGlobales(indicePicoRelativo);

tiempoPico_s = ...
    tiempo_s(indicePico);

pitchEnPico_deg = ...
    pitch_deg(indicePico);

%% Rebote del lado contrario

if pitchEnPico_deg >= 0

    pitchContrario_deg = min( ...
        pitch_deg(indicePico:end) ...
    );

    reboteContrario_deg = max( ...
        0, ...
        -pitchContrario_deg ...
    );

else

    pitchContrario_deg = max( ...
        pitch_deg(indicePico:end) ...
    );

    reboteContrario_deg = max( ...
        0, ...
        pitchContrario_deg ...
    );

end

%% Tiempo de establecimiento

limitePitchEstable_deg = max( ...
    0.25, ...
    0.02 * desviacionMaxima_deg ...
);

limiteVelocidadEstable_deg_s = 0.50;

tiempoEstablecimiento_s = NaN;

indicesBusqueda = find( ...
    indicesDespuesPulso ...
);

for i = 1:numel(indicesBusqueda)

    indiceActual = ...
        indicesBusqueda(i);

    pitchPermaneceEstable = all( ...
        abs(pitch_deg(indiceActual:end)) <= ...
        limitePitchEstable_deg ...
    );

    velocidadPermaneceEstable = all( ...
        abs(velocidadPitch_deg_s(indiceActual:end)) <= ...
        limiteVelocidadEstable_deg_s ...
    );

    if pitchPermaneceEstable && ...
            velocidadPermaneceEstable

        tiempoEstablecimiento_s = ...
            tiempo_s(indiceActual) - ...
            finPerturbacion_s;

        break;

    end

end

%% Esfuerzo de control

momentoControlMaximo_Nm = max( ...
    abs(momentoControlPitch_Nm) ...
);

diferenciaEmpujeMotoresMax_N = max( ...
    max(historialEmpujeMotores_N, [], 2) - ...
    min(historialEmpujeMotores_N, [], 2) ...
);

huboSaturacionMezclador = any( ...
    historialSaturacionMezclador ...
);

huboSaturacionControlador = any( ...
    historialSaturacionControlador ...
);

%% Estado final

pitchFinal_deg = ...
    pitch_deg(end);

velocidadPitchFinal_deg_s = ...
    velocidadPitch_deg_s(end);

%% ================================================================
% VERIFICACIONES AUTOMATICAS
% ================================================================

assert( ...
    all(isfinite(historialEstado), 'all'), ...
    ['La simulacion produjo valores NaN o infinitos. ' ...
     'Revisa el modelo o el controlador.'] ...
);

assert( ...
    desviacionMaxima_deg > 0.50, ...
    ['La perturbacion no produjo una desviacion apreciable. ' ...
     'Revisa que el momento externo se este aplicando.'] ...
);

assert( ...
    desviacionMaxima_deg < 30.0, ...
    ['El dron se inclino demasiado. El controlador podria ' ...
     'ser inestable o la perturbacion demasiado grande.'] ...
);

assert( ...
    momentoControlMaximo_Nm > 0.001, ...
    ['El controlador no genero un momento correctivo ' ...
     'apreciable.'] ...
);

assert( ...
    min(momentoControlPitch_Nm) < -0.001, ...
    ['El controlador no produjo un momento contrario ' ...
     'a la perturbacion positiva de pitch.'] ...
);

assert( ...
    abs(pitchFinal_deg) < 0.50, ...
    ['El pitch no regreso suficientemente cerca de cero ' ...
     'al terminar la simulacion.'] ...
);

assert( ...
    abs(velocidadPitchFinal_deg_s) < 0.50, ...
    ['La velocidad angular de pitch no regreso ' ...
     'suficientemente cerca de cero.'] ...
);

assert( ...
    isfinite(tiempoEstablecimiento_s), ...
    ['El dron no alcanzo la banda de establecimiento ' ...
     'antes de terminar la simulacion.'] ...
);

%% ================================================================
% GUARDAR RESULTADOS
% ================================================================

resultadosPitch.meta.nombre = ...
    "Rechazo de perturbacion externa en pitch";

resultadosPitch.meta.caso = ...
    caso.meta.nombre;

resultadosPitch.configuracion.dt_s = ...
    dt;

resultadosPitch.configuracion.tiempoFinal_s = ...
    tiempoFinal_s;

resultadosPitch.configuracion.ejePerturbacion = ...
    ejePerturbacion;

resultadosPitch.configuracion.momentoPerturbacion_Nm = ...
    momentoPerturbacion_Nm;

resultadosPitch.configuracion.inicioPerturbacion_s = ...
    inicioPerturbacion_s;

resultadosPitch.configuracion.duracionPerturbacion_s = ...
    duracionPerturbacion_s;

resultadosPitch.configuracion.finPerturbacion_s = ...
    finPerturbacion_s;

resultadosPitch.tiempo_s = ...
    tiempo_s;

resultadosPitch.estado = ...
    historialEstado;

resultadosPitch.pitch_deg = ...
    pitch_deg;

resultadosPitch.velocidadPitch_deg_s = ...
    velocidadPitch_deg_s;

resultadosPitch.referenciaPitch_deg = ...
    referenciaPitch_deg;

resultadosPitch.errorPitch_deg = ...
    errorPitch_deg;

resultadosPitch.momentoControl_B_Nm = ...
    historialMomentoControl_B_Nm;

resultadosPitch.momentoExterno_B_Nm = ...
    historialMomentoExterno_B_Nm;

resultadosPitch.empujeMotores_N = ...
    historialEmpujeMotores_N;

resultadosPitch.metricas.desviacionMaxima_deg = ...
    desviacionMaxima_deg;

resultadosPitch.metricas.tiempoPico_s = ...
    tiempoPico_s;

resultadosPitch.metricas.pitchEnPico_deg = ...
    pitchEnPico_deg;

resultadosPitch.metricas.reboteContrario_deg = ...
    reboteContrario_deg;

resultadosPitch.metricas.tiempoEstablecimiento_s = ...
    tiempoEstablecimiento_s;

resultadosPitch.metricas.limitePitchEstable_deg = ...
    limitePitchEstable_deg;

resultadosPitch.metricas.momentoControlMaximo_Nm = ...
    momentoControlMaximo_Nm;

resultadosPitch.metricas.diferenciaEmpujeMotoresMax_N = ...
    diferenciaEmpujeMotoresMax_N;

resultadosPitch.metricas.pitchFinal_deg = ...
    pitchFinal_deg;

resultadosPitch.metricas.velocidadPitchFinal_deg_s = ...
    velocidadPitchFinal_deg_s;

resultadosPitch.metricas.huboSaturacionMezclador = ...
    huboSaturacionMezclador;

resultadosPitch.metricas.huboSaturacionControlador = ...
    huboSaturacionControlador;

%% ================================================================
% MOSTRAR RESULTADOS
% ================================================================

fprintf('Ganancias utilizadas en pitch:\n\n');

fprintf('  Kp = %.8f\n', ...
    Ccontrol.pitch.Kp);

fprintf('  Ki = %.8f\n', ...
    Ccontrol.pitch.Ki);

fprintf('  Kd = %.8f\n\n', ...
    Ccontrol.pitch.Kd);

fprintf('Resultados de la perturbacion:\n\n');

fprintf('  Desviacion maxima:          %.3f grados\n', ...
    desviacionMaxima_deg);

fprintf('  Instante del pico:          %.3f s\n', ...
    tiempoPico_s);

fprintf('  Pitch en el pico:           %.3f grados\n', ...
    pitchEnPico_deg);

fprintf('  Rebote contrario:           %.3f grados\n', ...
    reboteContrario_deg);

fprintf('  Tiempo de establecimiento:  %.3f s\n', ...
    tiempoEstablecimiento_s);

fprintf('  Banda de establecimiento:   +/- %.3f grados\n', ...
    limitePitchEstable_deg);

fprintf('  Pitch final:                %.3f grados\n', ...
    pitchFinal_deg);

fprintf('  Velocidad pitch final:      %.3f grados/s\n', ...
    velocidadPitchFinal_deg_s);

fprintf('  Momento PID maximo:         %.4f N*m\n', ...
    momentoControlMaximo_Nm);

fprintf('  Diferencia maxima motores:  %.4f N\n', ...
    diferenciaEmpujeMotoresMax_N);

fprintf('  Saturacion controlador:     %s\n', ...
    string(huboSaturacionControlador));

fprintf('  Saturacion mezclador:       %s\n\n', ...
    string(huboSaturacionMezclador));

fprintf('============================================================\n');
fprintf(' PRUEBA APROBADA\n');
fprintf(' EL CONTROLADOR RECHAZA LA PERTURBACION EXTERNA EN PITCH\n');
fprintf('============================================================\n\n');

%% ================================================================
% GRAFICAS
% ================================================================

if exist( ...
        'graficar_rechazo_perturbacion_pitch', ...
        'file' ...
    ) == 2

    graficar_rechazo_perturbacion_pitch( ...
        resultadosPitch ...
    );

else

    fprintf( ...
        ['El archivo de graficas de pitch todavia no existe.\n' ...
         'La simulacion y las verificaciones ya fueron ejecutadas.\n\n'] ...
    );

end