%% TEST_COMPARACION_PID_ACTIVADO_DESACTIVADO
% Compara la respuesta del mismo dron ante la misma perturbacion:
%
%   CASO A:
%       Controlador PID de actitud activado.
%
%   CASO B:
%       Controlador PID de actitud desactivado.
%
% IMPORTANTE:
%
% En el caso sin PID, los motores siguen generando el empuje
% colectivo necesario para hover.
%
% Lo unico que se elimina es el momento correctivo:
%
%       M_PID = [0; 0; 0]
%
% Por tanto, esta prueba permite observar claramente la diferencia
% entre:
%
%   - Un modelo fisico con control realimentado.
%   - El mismo modelo fisico sin estabilizacion de actitud.

clearvars;
clc;
close all;

fprintf('\n');
fprintf('============================================================\n');
fprintf(' COMPARACION: PID ACTIVADO CONTRA PID DESACTIVADO\n');
fprintf('============================================================\n\n');

%% ================================================================
% PREPARAR EL CASO BASE TEORICO
% ================================================================

modelo = definicion_modelo();

P = parametros_fisicos();

R = reglas_competencia();

Dproyecto = requisitos_proyecto(R);

Cdiseno = parametros_diseno();

[P, Cdiseno, caso] = caso_base_teorico( ...
    P, ...
    Cdiseno, ...
    R ...
);

G = configuracion_motores_x( ...
    R, ...
    Dproyecto, ...
    Cdiseno.geometria.distanciaCentroMotor, ...
    Cdiseno.geometria.zMotor_B ...
);

P = aplicar_configuracion_motores(P, G);

Ccontrol = parametros_control_actitud(P);

%% ================================================================
% CONFIGURACION DE LA SIMULACION
% ================================================================

configuracion.dt_s = 0.005;

% La prueba termina antes de que el caso sin PID complete
% una rotacion demasiado grande.
configuracion.tiempoFinal_s = 4.00;

configuracion.ejePerturbacion = "roll";

configuracion.momentoPerturbacion_Nm = 0.08;

configuracion.inicioPerturbacion_s = 2.00;

configuracion.duracionPerturbacion_s = 0.20;

configuracion.finPerturbacion_s = ...
    configuracion.inicioPerturbacion_s + ...
    configuracion.duracionPerturbacion_s;

fprintf('Caso utilizado:\n');
fprintf('  %s\n\n', caso.meta.nombre);

fprintf('Perturbacion aplicada:\n');
fprintf('  Eje:               %s\n', ...
    configuracion.ejePerturbacion);

fprintf('  Magnitud:          %.4f N*m\n', ...
    configuracion.momentoPerturbacion_Nm);

fprintf('  Inicio:            %.3f s\n', ...
    configuracion.inicioPerturbacion_s);

fprintf('  Duracion:          %.3f s\n', ...
    configuracion.duracionPerturbacion_s);

fprintf('  Final:             %.3f s\n\n', ...
    configuracion.finPerturbacion_s);

fprintf('Ejecutando caso A: PID activado...\n');

resultadoConPID = simular_caso_comparacion_roll( ...
    true, ...
    configuracion, ...
    P, ...
    Ccontrol, ...
    modelo ...
);

fprintf('Caso A terminado.\n\n');

fprintf('Ejecutando caso B: PID desactivado...\n');

resultadoSinPID = simular_caso_comparacion_roll( ...
    false, ...
    configuracion, ...
    P, ...
    Ccontrol, ...
    modelo ...
);

fprintf('Caso B terminado.\n\n');

%% ================================================================
% CALCULAR METRICAS DE COMPARACION
% ================================================================

indicesDesdePerturbacion = ...
    resultadoConPID.tiempo_s >= ...
    configuracion.inicioPerturbacion_s;

%% Caso con PID

desviacionMaximaConPID_deg = max( ...
    abs( ...
        resultadoConPID.roll_deg( ...
            indicesDesdePerturbacion ...
        ) ...
    ) ...
);

rollFinalConPID_deg = ...
    resultadoConPID.roll_deg(end);

velocidadFinalConPID_deg_s = ...
    resultadoConPID.velocidadRoll_deg_s(end);

momentoPIDMaximo_Nm = max( ...
    abs(resultadoConPID.momentoControlRoll_Nm) ...
);

diferenciaMotoresConPID_N = ...
    max( ...
        resultadoConPID.diferenciaEmpujeMotores_N ...
    );

%% Caso sin PID

desviacionMaximaSinPID_deg = max( ...
    abs( ...
        resultadoSinPID.roll_deg( ...
            indicesDesdePerturbacion ...
        ) ...
    ) ...
);

rollFinalSinPID_deg = ...
    resultadoSinPID.roll_deg(end);

velocidadFinalSinPID_deg_s = ...
    resultadoSinPID.velocidadRoll_deg_s(end);

diferenciaMotoresSinPID_N = ...
    max( ...
        resultadoSinPID.diferenciaEmpujeMotores_N ...
    );

%% Relacion entre las respuestas

if desviacionMaximaConPID_deg > 0

    relacionDesviacion = ...
        desviacionMaximaSinPID_deg / ...
        desviacionMaximaConPID_deg;

else

    relacionDesviacion = Inf;

end

%% ================================================================
% VERIFICACIONES AUTOMATICAS
% ================================================================

assert( ...
    all(isfinite(resultadoConPID.estado), 'all'), ...
    ['El caso con PID produjo valores NaN o infinitos. ' ...
     'Revisa el controlador o el modelo.'] ...
);

assert( ...
    all(isfinite(resultadoSinPID.estado), 'all'), ...
    ['El caso sin PID produjo valores NaN o infinitos. ' ...
     'Revisa el modelo fisico.'] ...
);

assert( ...
    abs(rollFinalConPID_deg) < 1.0, ...
    ['El caso con PID no regreso suficientemente cerca ' ...
     'de roll igual a cero.'] ...
);

assert( ...
    abs(velocidadFinalConPID_deg_s) < 1.0, ...
    ['El caso con PID termino con una velocidad angular ' ...
     'de roll demasiado grande.'] ...
);

assert( ...
    momentoPIDMaximo_Nm > 0.001, ...
    ['El PID no genero un momento correctivo ' ...
     'apreciable durante la prueba.'] ...
);

assert( ...
    min(resultadoConPID.momentoControlRoll_Nm) < -0.001, ...
    ['El PID no genero un momento negativo para oponerse ' ...
     'a la perturbacion positiva.'] ...
);

assert( ...
    abs(rollFinalSinPID_deg) > 20.0, ...
    ['El caso sin PID no se separo lo suficiente de cero. ' ...
     'Revisa si accidentalmente sigue activo el controlador.'] ...
);

assert( ...
    abs(velocidadFinalSinPID_deg_s) > 10.0, ...
    ['El caso sin PID no conserva una velocidad angular ' ...
     'apreciable despues del impulso externo.'] ...
);

assert( ...
    desviacionMaximaSinPID_deg > ...
        2.0 * desviacionMaximaConPID_deg, ...
    ['La diferencia entre el caso con PID y sin PID no es ' ...
     'suficientemente clara.'] ...
);

assert( ...
    diferenciaMotoresConPID_N > 0.001, ...
    ['Con el PID activado no aparecio una diferencia ' ...
     'apreciable entre los motores.'] ...
);

%% ================================================================
% GUARDAR LA COMPARACION
% ================================================================

comparacion.meta.nombre = ...
    "Comparacion PID activado contra PID desactivado";

comparacion.meta.caso = ...
    caso.meta.nombre;

comparacion.configuracion = ...
    configuracion;

comparacion.ganancias = ...
    Ccontrol;

comparacion.conPID = ...
    resultadoConPID;

comparacion.sinPID = ...
    resultadoSinPID;

comparacion.metricas.desviacionMaximaConPID_deg = ...
    desviacionMaximaConPID_deg;

comparacion.metricas.desviacionMaximaSinPID_deg = ...
    desviacionMaximaSinPID_deg;

comparacion.metricas.rollFinalConPID_deg = ...
    rollFinalConPID_deg;

comparacion.metricas.rollFinalSinPID_deg = ...
    rollFinalSinPID_deg;

comparacion.metricas.velocidadFinalConPID_deg_s = ...
    velocidadFinalConPID_deg_s;

comparacion.metricas.velocidadFinalSinPID_deg_s = ...
    velocidadFinalSinPID_deg_s;

comparacion.metricas.momentoPIDMaximo_Nm = ...
    momentoPIDMaximo_Nm;

comparacion.metricas.diferenciaMotoresConPID_N = ...
    diferenciaMotoresConPID_N;

comparacion.metricas.diferenciaMotoresSinPID_N = ...
    diferenciaMotoresSinPID_N;

comparacion.metricas.relacionDesviacion = ...
    relacionDesviacion;

%% ================================================================
% MOSTRAR RESULTADOS EN CONSOLA
% ================================================================

fprintf('============================================================\n');
fprintf(' RESULTADOS DE LA COMPARACION\n');
fprintf('============================================================\n\n');

fprintf('GANANCIAS DE ROLL:\n');
fprintf('  Kp:                         %.8f\n', ...
    Ccontrol.roll.Kp);

fprintf('  Ki:                         %.8f\n', ...
    Ccontrol.roll.Ki);

fprintf('  Kd:                         %.8f\n\n', ...
    Ccontrol.roll.Kd);

fprintf('CASO A - PID ACTIVADO:\n');
fprintf('  Desviacion maxima:          %.3f grados\n', ...
    desviacionMaximaConPID_deg);

fprintf('  Roll final:                 %.3f grados\n', ...
    rollFinalConPID_deg);

fprintf('  Velocidad final:            %.3f grados/s\n', ...
    velocidadFinalConPID_deg_s);

fprintf('  Momento PID maximo:         %.4f N*m\n', ...
    momentoPIDMaximo_Nm);

fprintf('  Diferencia maxima motores:  %.4f N\n\n', ...
    diferenciaMotoresConPID_N);

fprintf('CASO B - PID DESACTIVADO:\n');
fprintf('  Desviacion maxima:          %.3f grados\n', ...
    desviacionMaximaSinPID_deg);

fprintf('  Roll final:                 %.3f grados\n', ...
    rollFinalSinPID_deg);

fprintf('  Velocidad final:            %.3f grados/s\n', ...
    velocidadFinalSinPID_deg_s);

fprintf('  Diferencia maxima motores:  %.4f N\n\n', ...
    diferenciaMotoresSinPID_N);

fprintf('COMPARACION:\n');
fprintf('  La desviacion sin PID fue %.2f veces la desviacion con PID.\n\n', ...
    relacionDesviacion);

fprintf('============================================================\n');
fprintf(' PRUEBA APROBADA\n');
fprintf(' EL PID CAMBIA LA RESPUESTA FISICA DEL DRON\n');
fprintf('============================================================\n\n');

%% ================================================================
% GENERAR GRAFICAS
% ================================================================

figura = figure( ...
    'Name', ...
    'Comparacion PID activado contra PID desactivado', ...
    'NumberTitle', ...
    'off', ...
    'Color', ...
    'w' ...
);

figura.Position = [
    100
    80
    1400
    780
];

panel = tiledlayout( ...
    figura, ...
    2, ...
    2, ...
    'TileSpacing', ...
    'compact', ...
    'Padding', ...
    'compact' ...
);

%% GRAFICA 1: ANGULO DE ROLL

ax1 = nexttile(panel, 1);

hReferencia = plot( ...
    ax1, ...
    resultadoConPID.tiempo_s, ...
    zeros(size(resultadoConPID.tiempo_s)), ...
    '--', ...
    'LineWidth', ...
    1.3 ...
);

hold(ax1, 'on');

hConPID = plot( ...
    ax1, ...
    resultadoConPID.tiempo_s, ...
    resultadoConPID.roll_deg, ...
    'LineWidth', ...
    1.9 ...
);

hSinPID = plot( ...
    ax1, ...
    resultadoSinPID.tiempo_s, ...
    resultadoSinPID.roll_deg, ...
    'LineWidth', ...
    1.9 ...
);

marcar_pulso_comparacion( ...
    ax1, ...
    configuracion.inicioPerturbacion_s, ...
    configuracion.finPerturbacion_s ...
);

grid(ax1, 'on');

xlabel(ax1, 'Tiempo [s]');
ylabel(ax1, 'Roll [grados]');
title(ax1, 'Angulo de roll');

legend( ...
    ax1, ...
    [hReferencia, hConPID, hSinPID], ...
    { ...
        'Referencia', ...
        'Con PID', ...
        'Sin PID' ...
    }, ...
    'Location', ...
    'best' ...
);

%% GRAFICA 2: VELOCIDAD ANGULAR

ax2 = nexttile(panel, 2);

hVelocidadConPID = plot( ...
    ax2, ...
    resultadoConPID.tiempo_s, ...
    resultadoConPID.velocidadRoll_deg_s, ...
    'LineWidth', ...
    1.9 ...
);

hold(ax2, 'on');

hVelocidadSinPID = plot( ...
    ax2, ...
    resultadoSinPID.tiempo_s, ...
    resultadoSinPID.velocidadRoll_deg_s, ...
    'LineWidth', ...
    1.9 ...
);

yline( ...
    ax2, ...
    0, ...
    '--', ...
    'HandleVisibility', ...
    'off' ...
);

marcar_pulso_comparacion( ...
    ax2, ...
    configuracion.inicioPerturbacion_s, ...
    configuracion.finPerturbacion_s ...
);

grid(ax2, 'on');

xlabel(ax2, 'Tiempo [s]');
ylabel(ax2, 'p [grados/s]');
title(ax2, 'Velocidad angular de roll');

legend( ...
    ax2, ...
    [hVelocidadConPID, hVelocidadSinPID], ...
    { ...
        'Con PID', ...
        'Sin PID' ...
    }, ...
    'Location', ...
    'best' ...
);

%% GRAFICA 3: PERTURBACION Y CORRECCION

ax3 = nexttile(panel, 3);

hMomentoExterno = plot( ...
    ax3, ...
    resultadoConPID.tiempo_s, ...
    resultadoConPID.momentoExternoRoll_Nm, ...
    'LineWidth', ...
    1.7 ...
);

hold(ax3, 'on');

hMomentoPID = plot( ...
    ax3, ...
    resultadoConPID.tiempo_s, ...
    resultadoConPID.momentoControlRoll_Nm, ...
    'LineWidth', ...
    1.9 ...
);

hMomentoSinPID = plot( ...
    ax3, ...
    resultadoSinPID.tiempo_s, ...
    resultadoSinPID.momentoControlRoll_Nm, ...
    '--', ...
    'LineWidth', ...
    1.5 ...
);

yline( ...
    ax3, ...
    0, ...
    ':', ...
    'HandleVisibility', ...
    'off' ...
);

marcar_pulso_comparacion( ...
    ax3, ...
    configuracion.inicioPerturbacion_s, ...
    configuracion.finPerturbacion_s ...
);

grid(ax3, 'on');

xlabel(ax3, 'Tiempo [s]');
ylabel(ax3, 'Momento [N·m]');
title(ax3, 'Perturbacion externa y respuesta del PID');

legend( ...
    ax3, ...
    [hMomentoExterno, hMomentoPID, hMomentoSinPID], ...
    { ...
        'Momento externo', ...
        'Momento correctivo con PID', ...
        'Momento correctivo sin PID' ...
    }, ...
    'Location', ...
    'best' ...
);

%% GRAFICA 4: DIFERENCIA ENTRE MOTORES

ax4 = nexttile(panel, 4);

hDiferenciaConPID = plot( ...
    ax4, ...
    resultadoConPID.tiempo_s, ...
    resultadoConPID.diferenciaEmpujeMotores_N, ...
    'LineWidth', ...
    1.9 ...
);

hold(ax4, 'on');

hDiferenciaSinPID = plot( ...
    ax4, ...
    resultadoSinPID.tiempo_s, ...
    resultadoSinPID.diferenciaEmpujeMotores_N, ...
    '--', ...
    'LineWidth', ...
    1.7 ...
);

marcar_pulso_comparacion( ...
    ax4, ...
    configuracion.inicioPerturbacion_s, ...
    configuracion.finPerturbacion_s ...
);

grid(ax4, 'on');

xlabel(ax4, 'Tiempo [s]');
ylabel(ax4, 'T_{max} - T_{min} [N]');
title(ax4, 'Diferencia de empuje entre motores');

legend( ...
    ax4, ...
    [hDiferenciaConPID, hDiferenciaSinPID], ...
    { ...
        'Con PID', ...
        'Sin PID' ...
    }, ...
    'Location', ...
    'best' ...
);

%% TITULO GENERAL

tituloGeneral = sprintf( ...
    ['Misma perturbacion de %.3f N*m | ' ...
     'Con PID: %.2f grados | ' ...
     'Sin PID: %.2f grados'], ...
    configuracion.momentoPerturbacion_Nm, ...
    desviacionMaximaConPID_deg, ...
    desviacionMaximaSinPID_deg ...
);

title( ...
    panel, ...
    tituloGeneral, ...
    'FontWeight', ...
    'bold', ...
    'FontSize', ...
    13 ...
);

linkaxes( ...
    [
        ax1
        ax2
        ax3
        ax4
    ], ...
    'x' ...
);

xlim( ...
    ax1, ...
    [
        resultadoConPID.tiempo_s(1)
        resultadoConPID.tiempo_s(end)
    ] ...
);


%% ================================================================
% FUNCION LOCAL: EJECUTAR UN CASO
% ================================================================

function resultado = simular_caso_comparacion_roll( ...
    activarPID, ...
    configuracion, ...
    P, ...
    Ccontrol, ...
    modelo ...
)
%SIMULAR_CASO_COMPARACION_ROLL
% Ejecuta una simulacion completa con el PID activado o desactivado.

    dt = ...
        configuracion.dt_s;

    tiempoFinal_s = ...
        configuracion.tiempoFinal_s;

    tiempo_s = ...
        (0:dt:tiempoFinal_s).';

    numeroMuestras = ...
        numel(tiempo_s);

    numeroPasos = ...
        numeroMuestras - 1;

    %% Estado inicial

    x = zeros( ...
        modelo.numeroEstados, ...
        1 ...
    );

    % NED: una coordenada zD negativa representa altura positiva.
    x(modelo.idx.zD) = -1.0;

    %% Comando

    comando.roll = 0;
    comando.pitch = 0;
    comando.yaw = 0;
    comando.throttle = 0.50;
    comando.armado = true;

    %% Memoria del PID

    estadoControl = [];

    %% Crear historiales

    historialEstado = zeros( ...
        numeroMuestras, ...
        modelo.numeroEstados ...
    );

    historialMomentoControlRoll_Nm = zeros( ...
        numeroMuestras, ...
        1 ...
    );

    historialMomentoExternoRoll_Nm = zeros( ...
        numeroMuestras, ...
        1 ...
    );

    historialEmpujeMotores_N = zeros( ...
        numeroMuestras, ...
        P.motores.numero ...
    );

    historialEstado(1, :) = ...
        x.';

    %% Inicializar empuje de hover

    empujeHover_N = ...
        P.cuerpo.masa * P.entorno.g;

    [Uinicial, ~] = mezclador_motores_x( ...
        empujeHover_N, ...
        zeros(3, 1), ...
        P ...
    );

    historialEmpujeMotores_N(1, :) = ...
        Uinicial.empujeMotores_N.';

    %% Simulacion temporal

    for k = 1:numeroPasos

        t = ...
            tiempo_s(k);

        %% Crear exactamente la misma perturbacion

        E = perturbacion_pulso_actitud( ...
            t, ...
            configuracion.ejePerturbacion, ...
            configuracion.momentoPerturbacion_Nm, ...
            configuracion.inicioPerturbacion_s, ...
            configuracion.duracionPerturbacion_s ...
        );

        %% Activar o desactivar la correccion de actitud

        if activarPID

            [ ...
                momentoDeseado_B_Nm, ...
                estadoControl, ...
                ~ ...
            ] = controlador_actitud( ...
                comando, ...
                x, ...
                dt, ...
                Ccontrol, ...
                estadoControl, ...
                modelo ...
            );

        else

            % Los motores siguen encendidos.
            %
            % Solamente se elimina la correccion angular.
            momentoDeseado_B_Nm = zeros(3, 1);

        end

        %% Empuje colectivo

        phi_rad = ...
            x(modelo.idx.phi);

        theta_rad = ...
            x(modelo.idx.theta);

        factorVertical = ...
            cos(phi_rad) * cos(theta_rad);

        % Evita que la compensacion colectiva crezca sin limite
        % cuando el caso sin PID alcanza inclinaciones grandes.
        factorVertical = max( ...
            factorVertical, ...
            0.65 ...
        );

        empujeTotal_N = ...
            P.cuerpo.masa * ...
            P.entorno.g / ...
            factorVertical;

        %% Mezclador

        [U, ~] = mezclador_motores_x( ...
            empujeTotal_N, ...
            momentoDeseado_B_Nm, ...
            P ...
        );

        %% Integracion RK4

        x = paso_rk4( ...
            @modelo_no_lineal_12_estados, ...
            t, ...
            x, ...
            dt, ...
            U, ...
            E, ...
            P, ...
            modelo ...
        );

        %% Guardar datos

        historialEstado(k + 1, :) = ...
            x.';

        historialMomentoControlRoll_Nm(k + 1) = ...
            momentoDeseado_B_Nm(1);

        historialMomentoExternoRoll_Nm(k + 1) = ...
            E.momentoExterno_B_Nm(1);

        historialEmpujeMotores_N(k + 1, :) = ...
            U.empujeMotores_N.';

    end

    %% Procesar resultados

    roll_rad = ...
        historialEstado(:, modelo.idx.phi);

    velocidadRoll_rad_s = ...
        historialEstado(:, modelo.idx.p);

    diferenciaEmpujeMotores_N = ...
        max(historialEmpujeMotores_N, [], 2) - ...
        min(historialEmpujeMotores_N, [], 2);

    resultado.pidActivado = ...
        activarPID;

    resultado.tiempo_s = ...
        tiempo_s;

    resultado.estado = ...
        historialEstado;

    resultado.roll_deg = ...
        rad2deg(roll_rad);

    resultado.velocidadRoll_deg_s = ...
        rad2deg(velocidadRoll_rad_s);

    resultado.momentoControlRoll_Nm = ...
        historialMomentoControlRoll_Nm;

    resultado.momentoExternoRoll_Nm = ...
        historialMomentoExternoRoll_Nm;

    resultado.empujeMotores_N = ...
        historialEmpujeMotores_N;

    resultado.diferenciaEmpujeMotores_N = ...
        diferenciaEmpujeMotores_N;

end


%% ================================================================
% FUNCION LOCAL: MARCAR EL PULSO
% ================================================================

function marcar_pulso_comparacion( ...
    ejeGrafica, ...
    inicioPerturbacion_s, ...
    finPerturbacion_s ...
)
%MARCAR_PULSO_COMPARACION
% Marca el inicio y el final de la perturbacion sin agregarlos
% a las leyendas de las graficas.

    xline( ...
        ejeGrafica, ...
        inicioPerturbacion_s, ...
        '--', ...
        'Inicio', ...
        'LineWidth', ...
        1.0, ...
        'LabelVerticalAlignment', ...
        'bottom', ...
        'HandleVisibility', ...
        'off' ...
    );

    xline( ...
        ejeGrafica, ...
        finPerturbacion_s, ...
        '--', ...
        'Fin', ...
        'LineWidth', ...
        1.0, ...
        'LabelVerticalAlignment', ...
        'bottom', ...
        'HandleVisibility', ...
        'off' ...
    );

end