%% TEST_RECHAZO_PERTURBACION_ROLL
% Comprueba que el controlador de actitud pueda rechazar un
% momento externo aplicado alrededor del eje de roll.
%
% Secuencia:
%
%   0.0 a 2.0 s:
%       Dron en hover, nivelado y sin perturbaciones.
%
%   2.0 a 2.2 s:
%       Se aplica un momento externo positivo en roll.
%
%   2.2 a 8.0 s:
%       Se elimina la perturbación y el controlador debe
%       regresar el dron cerca de roll = 0 grados.
%
% Esta prueba utiliza:
%
%   caso_base_teorico
%   controlador_actitud
%   mezclador_motores_x
%   modelo_no_lineal_12_estados
%   paso_rk4
%   perturbacion_pulso_actitud

clearvars;
clc;
close all;

fprintf('\n');
fprintf('============================================================\n');
fprintf(' PRUEBA DE RECHAZO DE PERTURBACION EN ROLL\n');
fprintf('============================================================\n\n');

%% ================================================================
% PREPARAR MODELO Y CASO BASE
% ================================================================

modelo = definicion_modelo();

P = parametros_fisicos();

R = reglas_competencia();

Dproyecto = requisitos_proyecto(R);

Cdiseno = parametros_diseno();

[P, Cdiseno, caso] = caso_base_teorico( ...
    P, ...
    Cdiseno, ...
    R ...
);

G = configuracion_motores_x( ...
    R, ...
    Dproyecto, ...
    Cdiseno.geometria.distanciaCentroMotor, ...
    Cdiseno.geometria.zMotor_B ...
);

P = aplicar_configuracion_motores(P, G);

%% ================================================================
% CONTROLADOR
% ================================================================

Ccontrol = parametros_control_actitud(P);

estadoControl = [];

%% ================================================================
% CONFIGURACION DE LA SIMULACION
% ================================================================

dt = 0.005;

tiempoFinal_s = 8.0;

numeroPasos = round( ...
    tiempoFinal_s / dt ...
);

tiempo_s = ...
    (0:numeroPasos).' * dt;

%% ================================================================
% CONFIGURACION DE LA PERTURBACION
% ================================================================

ejePerturbacion = "roll";

momentoPerturbacion_Nm = 0.08;

inicioPerturbacion_s = 2.0;

duracionPerturbacion_s = 0.20;

finPerturbacion_s = ...
    inicioPerturbacion_s + ...
    duracionPerturbacion_s;

fprintf('Configuracion de la perturbacion:\n');
fprintf('  Eje:                    %s\n', ejePerturbacion);
fprintf('  Momento externo:        %.4f N*m\n', ...
    momentoPerturbacion_Nm);
fprintf('  Inicio:                 %.3f s\n', ...
    inicioPerturbacion_s);
fprintf('  Duracion:               %.3f s\n', ...
    duracionPerturbacion_s);
fprintf('  Fin:                    %.3f s\n\n', ...
    finPerturbacion_s);

%% ================================================================
% ESTADO INICIAL
% ================================================================

x = zeros( ...
    modelo.numeroEstados, ...
    1 ...
);

% El marco inercial es NED:
%
% zD positiva significa hacia abajo.
%
% Por tanto, zD = -1 m representa un metro arriba del origen.

x(modelo.idx.zD) = -1.0;

%% ================================================================
% COMANDO DEL CONTROLADOR
% ================================================================

% La referencia siempre será nivelada.
%
% No estamos ordenando al dron que se incline.
% La inclinación será provocada solamente por la perturbación.

comando.roll = 0;
comando.pitch = 0;
comando.yaw = 0;

comando.throttle = 0.50;

comando.armado = true;

%% ================================================================
% CREAR HISTORIALES
% ================================================================

historialEstado = zeros( ...
    numeroPasos + 1, ...
    modelo.numeroEstados ...
);

historialEstado(1, :) = x.';

historialReferenciaRoll_rad = zeros( ...
    numeroPasos + 1, ...
    1 ...
);

historialErrorRoll_rad = zeros( ...
    numeroPasos + 1, ...
    1 ...
);

historialMomentoControl_B_Nm = zeros( ...
    numeroPasos + 1, ...
    3 ...
);

historialMomentoExterno_B_Nm = zeros( ...
    numeroPasos + 1, ...
    3 ...
);

historialEmpujeMotores_N = zeros( ...
    numeroPasos + 1, ...
    P.motores.numero ...
);

historialSaturacionMezclador = false( ...
    numeroPasos + 1, ...
    1 ...
);

historialSaturacionControlador = false( ...
    numeroPasos + 1, ...
    1 ...
);

%% ================================================================
% SIMULACION
% ================================================================

fprintf('Ejecutando simulacion...\n\n');

for k = 1:numeroPasos

    t = tiempo_s(k);

    %% Perturbación externa

    E = perturbacion_pulso_actitud( ...
        t, ...
        ejePerturbacion, ...
        momentoPerturbacion_Nm, ...
        inicioPerturbacion_s, ...
        duracionPerturbacion_s ...
    );

    %% Controlador de actitud

    [ ...
        momentoDeseado_B_Nm, ...
        estadoControl, ...
        Dcontrol ...
    ] = controlador_actitud( ...
        comando, ...
        x, ...
        dt, ...
        Ccontrol, ...
        estadoControl, ...
        modelo ...
    );

    %% Empuje necesario para hover

    masa_kg = P.cuerpo.masa;

    gravedad_m_s2 = P.entorno.g;

    phi_rad = x(modelo.idx.phi);

    theta_rad = x(modelo.idx.theta);

    % Cuando el dron se inclina, solamente una parte del empuje
    % total queda apuntando verticalmente.
    %
    % Se aumenta el empuje colectivo para compensar esa pérdida.

    factorVertical = ...
        cos(phi_rad) * cos(theta_rad);

    factorVertical = max( ...
        factorVertical, ...
        0.65 ...
    );

    empujeTotal_N = ...
        masa_kg * gravedad_m_s2 / factorVertical;

    %% Mezclador de motores

    [U, Dmezclador] = mezclador_motores_x( ...
        empujeTotal_N, ...
        momentoDeseado_B_Nm, ...
        P ...
    );

    %% Integración del modelo con RK4

    x = paso_rk4( ...
        @modelo_no_lineal_12_estados, ...
        t, ...
        x, ...
        dt, ...
        U, ...
        E, ...
        P, ...
        modelo ...
    );

    %% Guardar resultados

    historialEstado(k + 1, :) = ...
        x.';

    historialReferenciaRoll_rad(k + 1) = ...
        Dcontrol.referencia.phi_rad;

    historialErrorRoll_rad(k + 1) = ...
        Dcontrol.error.roll_rad;

    historialMomentoControl_B_Nm(k + 1, :) = ...
        momentoDeseado_B_Nm.';

    historialMomentoExterno_B_Nm(k + 1, :) = ...
        E.momentoExterno_B_Nm.';

    historialEmpujeMotores_N(k + 1, :) = ...
        U.empujeMotores_N.';

    historialSaturacionMezclador(k + 1) = ...
        Dmezclador.huboSaturacion;

    diferenciaSaturacionControl = ...
        Dcontrol.momentoSinSaturar_B_Nm - ...
        Dcontrol.momentoSaturado_B_Nm;

    historialSaturacionControlador(k + 1) = ...
        any(abs(diferenciaSaturacionControl) > 1e-12);

end

%% ================================================================
% CONVERTIR RESULTADOS
% ================================================================

roll_rad = ...
    historialEstado(:, modelo.idx.phi);

velocidadRoll_rad_s = ...
    historialEstado(:, modelo.idx.p);

roll_deg = ...
    rad2deg(roll_rad);

velocidadRoll_deg_s = ...
    rad2deg(velocidadRoll_rad_s);

referenciaRoll_deg = ...
    rad2deg(historialReferenciaRoll_rad);

errorRoll_deg = ...
    rad2deg(historialErrorRoll_rad);

momentoControlRoll_Nm = ...
    historialMomentoControl_B_Nm(:, 1);

momentoExternoRoll_Nm = ...
    historialMomentoExterno_B_Nm(:, 1);

%% ================================================================
% CALCULAR INDICADORES
% ================================================================

indicesDespuesPerturbacion = ...
    tiempo_s >= inicioPerturbacion_s;

indicesDespuesPulso = ...
    tiempo_s >= finPerturbacion_s;

%% Desviación máxima

[desviacionMaxima_deg, indicePicoRelativo] = max( ...
    abs(roll_deg(indicesDespuesPerturbacion)) ...
);

indicesGlobales = find( ...
    indicesDespuesPerturbacion ...
);

indicePico = ...
    indicesGlobales(indicePicoRelativo);

tiempoPico_s = ...
    tiempo_s(indicePico);

rollEnPico_deg = ...
    roll_deg(indicePico);

%% Rebote del lado contrario

if rollEnPico_deg >= 0

    rollContrario_deg = min( ...
        roll_deg(indicePico:end) ...
    );

    reboteContrario_deg = max( ...
        0, ...
        -rollContrario_deg ...
    );

else

    rollContrario_deg = max( ...
        roll_deg(indicePico:end) ...
    );

    reboteContrario_deg = max( ...
        0, ...
        rollContrario_deg ...
    );

end

%% Tiempo de establecimiento

% Se considera estable cuando:
%
%   |roll| <= limiteRollEstable
%
% y
%
%   |p| <= limiteVelocidadEstable
%
% desde ese instante hasta terminar la simulación.

limiteRollEstable_deg = max( ...
    0.25, ...
    0.02 * desviacionMaxima_deg ...
);

limiteVelocidadEstable_deg_s = 0.50;

tiempoEstablecimiento_s = NaN;

indicesBusqueda = find( ...
    indicesDespuesPulso ...
);

for i = 1:numel(indicesBusqueda)

    indiceActual = ...
        indicesBusqueda(i);

    rollPermaneceEstable = all( ...
        abs(roll_deg(indiceActual:end)) <= ...
        limiteRollEstable_deg ...
    );

    velocidadPermaneceEstable = all( ...
        abs(velocidadRoll_deg_s(indiceActual:end)) <= ...
        limiteVelocidadEstable_deg_s ...
    );

    if rollPermaneceEstable && ...
            velocidadPermaneceEstable

        tiempoEstablecimiento_s = ...
            tiempo_s(indiceActual) - ...
            finPerturbacion_s;

        break;

    end

end

%% Esfuerzo de control

momentoControlMaximo_Nm = max( ...
    abs(momentoControlRoll_Nm) ...
);

diferenciaEmpujeMotoresMax_N = max( ...
    max(historialEmpujeMotores_N, [], 2) - ...
    min(historialEmpujeMotores_N, [], 2) ...
);

huboSaturacionMezclador = any( ...
    historialSaturacionMezclador ...
);

huboSaturacionControlador = any( ...
    historialSaturacionControlador ...
);

%% Estado final

rollFinal_deg = ...
    roll_deg(end);

velocidadRollFinal_deg_s = ...
    velocidadRoll_deg_s(end);

%% ================================================================
% VERIFICACIONES AUTOMATICAS
% ================================================================

assert( ...
    all(isfinite(historialEstado), 'all'), ...
    ['La simulacion produjo valores NaN o infinitos. ' ...
     'Revisa el modelo o el controlador.'] ...
);

assert( ...
    desviacionMaxima_deg > 0.50, ...
    ['La perturbacion no produjo una desviacion apreciable. ' ...
     'Revisa que el momento externo se este aplicando.'] ...
);

assert( ...
    desviacionMaxima_deg < 30.0, ...
    ['El dron se inclino demasiado. El controlador podria ' ...
     'ser inestable o la perturbacion demasiado grande.'] ...
);

assert( ...
    momentoControlMaximo_Nm > 0.001, ...
    ['El controlador no genero un momento correctivo ' ...
     'apreciable.'] ...
);

assert( ...
    min(momentoControlRoll_Nm) < -0.001, ...
    ['El controlador no produjo un momento contrario ' ...
     'a la perturbacion positiva de roll.'] ...
);

assert( ...
    abs(rollFinal_deg) < 0.50, ...
    ['El roll no regreso suficientemente cerca de cero ' ...
     'al terminar la simulacion.'] ...
);

assert( ...
    abs(velocidadRollFinal_deg_s) < 0.50, ...
    ['La velocidad angular de roll no regreso ' ...
     'suficientemente cerca de cero.'] ...
);

assert( ...
    isfinite(tiempoEstablecimiento_s), ...
    ['El dron no alcanzo la banda de establecimiento ' ...
     'antes de terminar la simulacion.'] ...
);

%% ================================================================
% GUARDAR RESULTADOS EN UNA ESTRUCTURA
% ================================================================

resultados.meta.nombre = ...
    "Rechazo de perturbacion externa en roll";

resultados.meta.caso = ...
    caso.meta.nombre;

resultados.configuracion.dt_s = ...
    dt;

resultados.configuracion.tiempoFinal_s = ...
    tiempoFinal_s;

resultados.configuracion.ejePerturbacion = ...
    ejePerturbacion;

resultados.configuracion.momentoPerturbacion_Nm = ...
    momentoPerturbacion_Nm;

resultados.configuracion.inicioPerturbacion_s = ...
    inicioPerturbacion_s;

resultados.configuracion.duracionPerturbacion_s = ...
    duracionPerturbacion_s;

resultados.configuracion.finPerturbacion_s = ...
    finPerturbacion_s;

resultados.tiempo_s = ...
    tiempo_s;

resultados.estado = ...
    historialEstado;

resultados.roll_deg = ...
    roll_deg;

resultados.velocidadRoll_deg_s = ...
    velocidadRoll_deg_s;

resultados.referenciaRoll_deg = ...
    referenciaRoll_deg;

resultados.errorRoll_deg = ...
    errorRoll_deg;

resultados.momentoControl_B_Nm = ...
    historialMomentoControl_B_Nm;

resultados.momentoExterno_B_Nm = ...
    historialMomentoExterno_B_Nm;

resultados.empujeMotores_N = ...
    historialEmpujeMotores_N;

resultados.metricas.desviacionMaxima_deg = ...
    desviacionMaxima_deg;

resultados.metricas.tiempoPico_s = ...
    tiempoPico_s;

resultados.metricas.rollEnPico_deg = ...
    rollEnPico_deg;

resultados.metricas.reboteContrario_deg = ...
    reboteContrario_deg;

resultados.metricas.tiempoEstablecimiento_s = ...
    tiempoEstablecimiento_s;

resultados.metricas.limiteRollEstable_deg = ...
    limiteRollEstable_deg;

resultados.metricas.momentoControlMaximo_Nm = ...
    momentoControlMaximo_Nm;

resultados.metricas.diferenciaEmpujeMotoresMax_N = ...
    diferenciaEmpujeMotoresMax_N;

resultados.metricas.rollFinal_deg = ...
    rollFinal_deg;

resultados.metricas.velocidadRollFinal_deg_s = ...
    velocidadRollFinal_deg_s;

resultados.metricas.huboSaturacionMezclador = ...
    huboSaturacionMezclador;

resultados.metricas.huboSaturacionControlador = ...
    huboSaturacionControlador;

%% ================================================================
% MOSTRAR RESULTADOS
% ================================================================

fprintf('Ganancias utilizadas en roll:\n\n');

fprintf('  Kp = %.8f\n', ...
    Ccontrol.roll.Kp);

fprintf('  Ki = %.8f\n', ...
    Ccontrol.roll.Ki);

fprintf('  Kd = %.8f\n\n', ...
    Ccontrol.roll.Kd);

fprintf('Resultados de la perturbacion:\n\n');

fprintf('  Desviacion maxima:          %.3f grados\n', ...
    desviacionMaxima_deg);

fprintf('  Instante del pico:          %.3f s\n', ...
    tiempoPico_s);

fprintf('  Roll en el pico:            %.3f grados\n', ...
    rollEnPico_deg);

fprintf('  Rebote contrario:           %.3f grados\n', ...
    reboteContrario_deg);

fprintf('  Tiempo de establecimiento:  %.3f s\n', ...
    tiempoEstablecimiento_s);

fprintf('  Banda de establecimiento:   +/- %.3f grados\n', ...
    limiteRollEstable_deg);

fprintf('  Roll final:                 %.3f grados\n', ...
    rollFinal_deg);

fprintf('  Velocidad roll final:       %.3f grados/s\n', ...
    velocidadRollFinal_deg_s);

fprintf('  Momento PID maximo:         %.4f N*m\n', ...
    momentoControlMaximo_Nm);

fprintf('  Diferencia maxima motores:  %.4f N\n', ...
    diferenciaEmpujeMotoresMax_N);

fprintf('  Saturacion controlador:     %s\n', ...
    string(huboSaturacionControlador));

fprintf('  Saturacion mezclador:       %s\n\n', ...
    string(huboSaturacionMezclador));

fprintf('============================================================\n');
fprintf(' PRUEBA APROBADA\n');
fprintf(' EL CONTROLADOR RECHAZA LA PERTURBACION EXTERNA EN ROLL\n');
fprintf('============================================================\n\n');

%% ================================================================
% GRAFICAS
% ================================================================

% El archivo de gráficas se agregará en el siguiente paso.
%
% Cuando exista graficar_rechazo_perturbacion.m, esta prueba
% lo ejecutará automáticamente.

if exist( ...
        'graficar_rechazo_perturbacion', ...
        'file' ...
    ) == 2

    graficar_rechazo_perturbacion( ...
        resultados ...
    );

else

    fprintf( ...
        ['El archivo de graficas todavia no existe.\n' ...
         'La simulacion y las verificaciones ya fueron ejecutadas.\n\n'] ...
    );

end