%% TEST_RECHAZO_PERTURBACION_YAW_REAL
% Valida el rechazo de una perturbacion externa en yaw usando
% los parametros fisicos del KIWO E88 real V1.
%
% IMPORTANTE:
%
% El controlador actual de yaw regula velocidad angular:
%
%       r_ref = 0 rad/s
%
% No controla directamente el angulo absoluto de yaw.
%
% Por tanto:
%
%   - La perturbacion puede cambiar el angulo psi.
%   - El controlador debe detener la velocidad de giro r.
%   - El angulo final de yaw no necesariamente regresa a cero.
%
% Secuencia:
%
%   0.0 a 2.0 s:
%       Hover estable y velocidad de yaw igual a cero.
%
%   2.0 a 2.15 s:
%       Momento externo positivo alrededor del eje Z_B.
%
%   2.15 a 8.0 s:
%       El controlador debe detener la rotacion.

clearvars;
clc;
close all;

fprintf('\n');
fprintf('============================================================\n');
fprintf(' RECHAZO DE PERTURBACION EN YAW - KIWO E88 REAL V1\n');
fprintf('============================================================\n\n');

%% ================================================================
% CARGAR MODELO REAL
% ================================================================

modelo = definicion_modelo();

P = parametros_fisicos();

Cdiseno = parametros_diseno();

R = reglas_competencia();

[P, Cdiseno, caso] = caso_real_dron( ...
    P, ...
    Cdiseno, ...
    R ...
);

% No se llama configuracion_motores_x porque reemplazaria
% la geometria rectangular real por una X cuadrada.

%% ================================================================
% VALIDAR PARAMETROS FISICOS
% ================================================================

reporteFisico = validar_parametros_fisicos(P);

if ~reporteFisico.completo

    fprintf('PARAMETROS FISICOS INCOMPLETOS O INVALIDOS:\n\n');

    for k = 1:numel(reporteFisico.faltantes)

        fprintf( ...
            '  Faltante: %s\n', ...
            reporteFisico.faltantes(k) ...
        );

    end

    for k = 1:numel(reporteFisico.errores)

        fprintf( ...
            '  Error: %s\n', ...
            reporteFisico.errores(k) ...
        );

    end

    error( ...
        'test_rechazo_perturbacion_yaw_real:ParametrosInvalidos', ...
        'El caso real no supero la validacion fisica.' ...
    );

end

%% ================================================================
% CONTROLADOR DEL CASO REAL
% ================================================================

Ccontrol = parametros_control_actitud(P);

estadoControl = [];

%% ================================================================
% CONFIGURACION TEMPORAL
% ================================================================

dt = 0.005;

tiempoFinal_s = 8.0;

numeroPasos = round( ...
    tiempoFinal_s / dt ...
);

tiempo_s = ...
    (0:numeroPasos).' * dt;

numeroMuestras = ...
    numeroPasos + 1;

%% ================================================================
% CONFIGURACION DE LA PERTURBACION
% ================================================================

ejePerturbacion = "yaw";

% Se utiliza un momento menor que en roll y pitch.
%
% El control de yaw depende del torque de reaccion de las helices,
% cuya autoridad es menor que la generada por los brazos para
% roll y pitch.

momentoPerturbacion_Nm = 0.00030;

inicioPerturbacion_s = 2.00;

duracionPerturbacion_s = 0.15;

finPerturbacion_s = ...
    inicioPerturbacion_s + ...
    duracionPerturbacion_s;

%% ================================================================
% MOSTRAR CONFIGURACION
% ================================================================

fprintf('Caso cargado:\n');
fprintf('  %s\n\n', ...
    caso.meta.nombre);

fprintf('Parametros principales:\n');

fprintf('  Masa total:                %.4f kg\n', ...
    P.cuerpo.masa);

fprintf('  Izz:                       %.8e kg*m^2\n', ...
    P.cuerpo.inercia_B(3, 3));

fprintf('  Empuje hover por motor:    %.4f N\n', ...
    caso.empujeHoverPorMotor_N);

fprintf('  Empuje maximo por motor:   %.4f N\n', ...
    caso.empujeMaximoPorMotor_N);

fprintf('  Relacion empuje/peso:      %.3f\n\n', ...
    caso.relacionEmpujePesoMaxima);

fprintf('Ganancias de velocidad yaw:\n');

fprintf('  Kp:                        %.8f\n', ...
    Ccontrol.yaw.Kp);

fprintf('  Ki:                        %.8f\n', ...
    Ccontrol.yaw.Ki);

fprintf('  Kd:                        %.8f\n', ...
    Ccontrol.yaw.Kd);

fprintf('  Momento maximo permitido:  %.6f N*m\n', ...
    Ccontrol.limites.momentoYawMax_Nm);

fprintf('  Metodo de limites:         %s\n\n', ...
    Ccontrol.autoridad.metodo);

fprintf('Perturbacion:\n');

fprintf('  Eje:                       %s\n', ...
    ejePerturbacion);

fprintf('  Magnitud:                  %.6f N*m\n', ...
    momentoPerturbacion_Nm);

fprintf('  Inicio:                    %.3f s\n', ...
    inicioPerturbacion_s);

fprintf('  Duracion:                  %.3f s\n', ...
    duracionPerturbacion_s);

fprintf('  Fin:                       %.3f s\n\n', ...
    finPerturbacion_s);

%% ================================================================
% ESTADO INICIAL
% ================================================================

x = zeros( ...
    modelo.numeroEstados, ...
    1 ...
);

% Marco NED:
% zD negativa representa altura positiva.

x(modelo.idx.zD) = -1.0;

%% ================================================================
% REFERENCIAS DEL CONTROLADOR
% ================================================================

comando.roll = 0;
comando.pitch = 0;

% En yaw, cero representa velocidad angular deseada igual a cero.

comando.yaw = 0;

comando.throttle = 0.50;

comando.armado = true;

%% ================================================================
% CREAR HISTORIALES
% ================================================================

historialEstado = zeros( ...
    numeroMuestras, ...
    modelo.numeroEstados ...
);

historialEstado(1, :) = ...
    x.';

historialReferenciaYawRate_rad_s = zeros( ...
    numeroMuestras, ...
    1 ...
);

historialErrorYawRate_rad_s = zeros( ...
    numeroMuestras, ...
    1 ...
);

historialMomentoControl_B_Nm = zeros( ...
    numeroMuestras, ...
    3 ...
);

historialMomentoRealMotores_B_Nm = zeros( ...
    numeroMuestras, ...
    3 ...
);

historialMomentoExterno_B_Nm = zeros( ...
    numeroMuestras, ...
    3 ...
);

historialEmpujeMotores_N = zeros( ...
    numeroMuestras, ...
    P.motores.numero ...
);

historialTorqueReaccionMotores_Nm = zeros( ...
    numeroMuestras, ...
    P.motores.numero ...
);

historialSaturacionControlador = false( ...
    numeroMuestras, ...
    1 ...
);

historialSaturacionMezclador = false( ...
    numeroMuestras, ...
    1 ...
);

%% ================================================================
% INICIALIZAR MOTORES EN HOVER
% ================================================================

empujeHoverTotal_N = ...
    P.cuerpo.masa * ...
    P.entorno.g;

[Uhover, Dhover] = mezclador_motores_x( ...
    empujeHoverTotal_N, ...
    zeros(3, 1), ...
    P ...
);

historialEmpujeMotores_N(1, :) = ...
    Uhover.empujeMotores_N.';

historialMomentoRealMotores_B_Nm(1, :) = ...
    Dhover.momentoReal_B_Nm.';

historialTorqueReaccionMotores_Nm(1, :) = ...
    Uhover.torqueReaccionMotores_Nm.';

%% ================================================================
% SIMULACION
% ================================================================

fprintf('Ejecutando simulacion del caso real...\n\n');

for k = 1:numeroPasos

    t = ...
        tiempo_s(k);

    %% Perturbacion externa

    E = perturbacion_pulso_actitud( ...
        t, ...
        ejePerturbacion, ...
        momentoPerturbacion_Nm, ...
        inicioPerturbacion_s, ...
        duracionPerturbacion_s ...
    );

    %% Controlador

    [ ...
        momentoDeseado_B_Nm, ...
        estadoControl, ...
        Dcontrol ...
    ] = controlador_actitud( ...
        comando, ...
        x, ...
        dt, ...
        Ccontrol, ...
        estadoControl, ...
        modelo ...
    );

    %% Empuje colectivo

    phi_rad = ...
        x(modelo.idx.phi);

    theta_rad = ...
        x(modelo.idx.theta);

    factorVertical = ...
        cos(phi_rad) * ...
        cos(theta_rad);

    factorVertical = max( ...
        factorVertical, ...
        0.65 ...
    );

    empujeTotal_N = ...
        P.cuerpo.masa * ...
        P.entorno.g / ...
        factorVertical;

    %% Mezclador

    [U, Dmezclador] = mezclador_motores_x( ...
        empujeTotal_N, ...
        momentoDeseado_B_Nm, ...
        P ...
    );

    %% Integracion RK4

    x = paso_rk4( ...
        @modelo_no_lineal_12_estados, ...
        t, ...
        x, ...
        dt, ...
        U, ...
        E, ...
        P, ...
        modelo ...
    );

    %% Guardar datos

    historialEstado(k + 1, :) = ...
        x.';

    historialReferenciaYawRate_rad_s(k + 1) = ...
        Dcontrol.referencia.r_rad_s;

    historialErrorYawRate_rad_s(k + 1) = ...
        Dcontrol.error.yawRate_rad_s;

    historialMomentoControl_B_Nm(k + 1, :) = ...
        momentoDeseado_B_Nm.';

    historialMomentoRealMotores_B_Nm(k + 1, :) = ...
        Dmezclador.momentoReal_B_Nm.';

    historialMomentoExterno_B_Nm(k + 1, :) = ...
        E.momentoExterno_B_Nm.';

    historialEmpujeMotores_N(k + 1, :) = ...
        U.empujeMotores_N.';

    historialTorqueReaccionMotores_Nm(k + 1, :) = ...
        U.torqueReaccionMotores_Nm.';

    diferenciaSaturacionControl = ...
        Dcontrol.momentoSinSaturar_B_Nm - ...
        Dcontrol.momentoSaturado_B_Nm;

    historialSaturacionControlador(k + 1) = ...
        any( ...
            abs(diferenciaSaturacionControl) > 1e-12 ...
        );

    historialSaturacionMezclador(k + 1) = ...
        Dmezclador.huboSaturacion;

end

%% ================================================================
% PROCESAR RESULTADOS
% ================================================================

yaw_rad = ...
    historialEstado(:, modelo.idx.psi);

velocidadYaw_rad_s = ...
    historialEstado(:, modelo.idx.r);

yaw_deg = ...
    rad2deg(yaw_rad);

velocidadYaw_deg_s = ...
    rad2deg(velocidadYaw_rad_s);

referenciaYawRate_deg_s = ...
    rad2deg(historialReferenciaYawRate_rad_s);

errorYawRate_deg_s = ...
    rad2deg(historialErrorYawRate_rad_s);

momentoControlYaw_Nm = ...
    historialMomentoControl_B_Nm(:, 3);

momentoRealMotoresYaw_Nm = ...
    historialMomentoRealMotores_B_Nm(:, 3);

momentoExternoYaw_Nm = ...
    historialMomentoExterno_B_Nm(:, 3);

%% ================================================================
% CALCULAR INDICADORES
% ================================================================

indicesDesdePerturbacion = ...
    tiempo_s >= inicioPerturbacion_s;

indicesDespuesPulso = ...
    tiempo_s >= finPerturbacion_s;

%% Velocidad maxima de yaw

[velocidadYawMaxima_deg_s, indicePicoRelativo] = max( ...
    abs( ...
        velocidadYaw_deg_s(indicesDesdePerturbacion) ...
    ) ...
);

indicesGlobales = find( ...
    indicesDesdePerturbacion ...
);

indicePico = ...
    indicesGlobales(indicePicoRelativo);

tiempoPico_s = ...
    tiempo_s(indicePico);

velocidadYawEnPico_deg_s = ...
    velocidadYaw_deg_s(indicePico);

%% Rebote de velocidad en sentido contrario

if velocidadYawEnPico_deg_s >= 0

    velocidadContraria_deg_s = min( ...
        velocidadYaw_deg_s(indicePico:end) ...
    );

    reboteContrario_deg_s = max( ...
        0, ...
        -velocidadContraria_deg_s ...
    );

else

    velocidadContraria_deg_s = max( ...
        velocidadYaw_deg_s(indicePico:end) ...
    );

    reboteContrario_deg_s = max( ...
        0, ...
        velocidadContraria_deg_s ...
    );

end

%% Tiempo de establecimiento

limiteVelocidadYawEstable_deg_s = max( ...
    0.25, ...
    0.02 * velocidadYawMaxima_deg_s ...
);

tiempoEstablecimiento_s = NaN;

indicesBusqueda = find( ...
    indicesDespuesPulso ...
);

for i = 1:numel(indicesBusqueda)

    indiceActual = ...
        indicesBusqueda(i);

    velocidadPermaneceEstable = all( ...
        abs(velocidadYaw_deg_s(indiceActual:end)) <= ...
        limiteVelocidadYawEstable_deg_s ...
    );

    if velocidadPermaneceEstable

        tiempoEstablecimiento_s = ...
            tiempo_s(indiceActual) - ...
            finPerturbacion_s;

        break;

    end

end

%% Esfuerzo de control

momentoControlMaximo_Nm = max( ...
    abs(momentoControlYaw_Nm) ...
);

momentoRealMotoresMaximo_Nm = max( ...
    abs(momentoRealMotoresYaw_Nm) ...
);

diferenciaEmpujeMotores_N = ...
    max(historialEmpujeMotores_N, [], 2) - ...
    min(historialEmpujeMotores_N, [], 2);

diferenciaEmpujeMotoresMax_N = max( ...
    diferenciaEmpujeMotores_N ...
);

huboSaturacionControlador = any( ...
    historialSaturacionControlador ...
);

huboSaturacionMezclador = any( ...
    historialSaturacionMezclador ...
);

porcentajeMomentoUtilizado = ...
    100 * ...
    momentoControlMaximo_Nm / ...
    Ccontrol.limites.momentoYawMax_Nm;

%% Estado final

yawFinal_deg = ...
    yaw_deg(end);

velocidadYawFinal_deg_s = ...
    velocidadYaw_deg_s(end);

errorYawRateFinal_deg_s = ...
    errorYawRate_deg_s(end);

%% ================================================================
% VERIFICACIONES AUTOMATICAS
% ================================================================

assert( ...
    all(isfinite(historialEstado), 'all'), ...
    ['La simulacion real produjo valores NaN o infinitos. ' ...
     'Revisa los parametros fisicos.'] ...
);

assert( ...
    velocidadYawMaxima_deg_s > 0.50, ...
    ['La perturbacion no produjo una velocidad de yaw ' ...
     'apreciable.'] ...
);

assert( ...
    velocidadYawMaxima_deg_s < 90.0, ...
    ['La velocidad de yaw fue demasiado grande para la ' ...
     'perturbacion aplicada.'] ...
);

assert( ...
    momentoControlMaximo_Nm > 1e-6, ...
    ['El controlador no genero una correccion apreciable ' ...
     'en yaw.'] ...
);

assert( ...
    min(momentoControlYaw_Nm) < -1e-6, ...
    ['El controlador no solicito un momento contrario a la ' ...
     'perturbacion positiva de yaw.'] ...
);

assert( ...
    min(momentoRealMotoresYaw_Nm) < -1e-6, ...
    ['Los rotores no produjeron un momento real negativo ' ...
     'para detener el giro.'] ...
);

assert( ...
    abs(velocidadYawFinal_deg_s) < 0.50, ...
    ['La velocidad angular final de yaw no regreso ' ...
     'suficientemente cerca de cero.'] ...
);

assert( ...
    abs(errorYawRateFinal_deg_s) < 0.50, ...
    'El error final de velocidad de yaw es demasiado grande.' ...
);

assert( ...
    isfinite(tiempoEstablecimiento_s), ...
    ['La velocidad de yaw no alcanzo la banda de ' ...
     'establecimiento antes de terminar la simulacion.'] ...
);

%% ================================================================
% GUARDAR RESULTADOS PARA LA GRAFICA EXISTENTE
% ================================================================

resultadosYaw.meta.nombre = ...
    "Rechazo de perturbacion en yaw - KIWO E88 real V1";

resultadosYaw.meta.caso = ...
    caso.meta.nombre;

resultadosYaw.configuracion.dt_s = ...
    dt;

resultadosYaw.configuracion.tiempoFinal_s = ...
    tiempoFinal_s;

resultadosYaw.configuracion.ejePerturbacion = ...
    ejePerturbacion;

resultadosYaw.configuracion.momentoPerturbacion_Nm = ...
    momentoPerturbacion_Nm;

resultadosYaw.configuracion.inicioPerturbacion_s = ...
    inicioPerturbacion_s;

resultadosYaw.configuracion.duracionPerturbacion_s = ...
    duracionPerturbacion_s;

resultadosYaw.configuracion.finPerturbacion_s = ...
    finPerturbacion_s;

resultadosYaw.tiempo_s = ...
    tiempo_s;

resultadosYaw.estado = ...
    historialEstado;

resultadosYaw.yaw_deg = ...
    yaw_deg;

resultadosYaw.velocidadYaw_deg_s = ...
    velocidadYaw_deg_s;

resultadosYaw.referenciaYawRate_deg_s = ...
    referenciaYawRate_deg_s;

resultadosYaw.errorYawRate_deg_s = ...
    errorYawRate_deg_s;

resultadosYaw.momentoControl_B_Nm = ...
    historialMomentoControl_B_Nm;

resultadosYaw.momentoRealMotores_B_Nm = ...
    historialMomentoRealMotores_B_Nm;

resultadosYaw.momentoExterno_B_Nm = ...
    historialMomentoExterno_B_Nm;

resultadosYaw.momentoYawReal_Nm = ...
    momentoRealMotoresYaw_Nm;

resultadosYaw.empujeMotores_N = ...
    historialEmpujeMotores_N;

resultadosYaw.torqueReaccionMotores_Nm = ...
    historialTorqueReaccionMotores_Nm;

resultadosYaw.metricas.velocidadYawMaxima_deg_s = ...
    velocidadYawMaxima_deg_s;

resultadosYaw.metricas.tiempoPico_s = ...
    tiempoPico_s;

resultadosYaw.metricas.velocidadYawEnPico_deg_s = ...
    velocidadYawEnPico_deg_s;

resultadosYaw.metricas.reboteContrario_deg_s = ...
    reboteContrario_deg_s;

resultadosYaw.metricas.tiempoEstablecimiento_s = ...
    tiempoEstablecimiento_s;

resultadosYaw.metricas.limiteVelocidadYawEstable_deg_s = ...
    limiteVelocidadYawEstable_deg_s;

resultadosYaw.metricas.momentoControlMaximo_Nm = ...
    momentoControlMaximo_Nm;

resultadosYaw.metricas.momentoRealMotoresMaximo_Nm = ...
    momentoRealMotoresMaximo_Nm;

resultadosYaw.metricas.diferenciaEmpujeMotoresMax_N = ...
    diferenciaEmpujeMotoresMax_N;

resultadosYaw.metricas.porcentajeMomentoUtilizado = ...
    porcentajeMomentoUtilizado;

resultadosYaw.metricas.yawFinal_deg = ...
    yawFinal_deg;

resultadosYaw.metricas.velocidadYawFinal_deg_s = ...
    velocidadYawFinal_deg_s;

resultadosYaw.metricas.errorYawRateFinal_deg_s = ...
    errorYawRateFinal_deg_s;

resultadosYaw.metricas.huboSaturacionControlador = ...
    huboSaturacionControlador;

resultadosYaw.metricas.huboSaturacionMezclador = ...
    huboSaturacionMezclador;

%% ================================================================
% MOSTRAR RESULTADOS
% ================================================================

fprintf('============================================================\n');
fprintf(' RESULTADOS DEL KIWO E88 REAL V1 - YAW\n');
fprintf('============================================================\n\n');

fprintf('Respuesta de velocidad angular:\n');

fprintf('  Velocidad maxima yaw:       %.3f grados/s\n', ...
    velocidadYawMaxima_deg_s);

fprintf('  Instante del pico:          %.3f s\n', ...
    tiempoPico_s);

fprintf('  Velocidad en el pico:       %.3f grados/s\n', ...
    velocidadYawEnPico_deg_s);

fprintf('  Rebote contrario:           %.3f grados/s\n', ...
    reboteContrario_deg_s);

fprintf('  Tiempo de establecimiento:  %.3f s\n', ...
    tiempoEstablecimiento_s);

fprintf('  Banda de establecimiento:   +/- %.3f grados/s\n', ...
    limiteVelocidadYawEstable_deg_s);

fprintf('  Angulo yaw final:           %.3f grados\n', ...
    yawFinal_deg);

fprintf('  Velocidad yaw final:        %.3f grados/s\n', ...
    velocidadYawFinal_deg_s);

fprintf('  Error yaw rate final:       %.3f grados/s\n\n', ...
    errorYawRateFinal_deg_s);

fprintf('Esfuerzo de control:\n');

fprintf('  Momento PID maximo:         %.6f N*m\n', ...
    momentoControlMaximo_Nm);

fprintf('  Momento real motores max:   %.6f N*m\n', ...
    momentoRealMotoresMaximo_Nm);

fprintf('  Limite disponible yaw:      %.6f N*m\n', ...
    Ccontrol.limites.momentoYawMax_Nm);

fprintf('  Autoridad utilizada:        %.2f %%\n', ...
    porcentajeMomentoUtilizado);

fprintf('  Diferencia maxima motores:  %.6f N\n', ...
    diferenciaEmpujeMotoresMax_N);

fprintf('  Saturacion controlador:     %s\n', ...
    string(huboSaturacionControlador));

fprintf('  Saturacion mezclador:       %s\n\n', ...
    string(huboSaturacionMezclador));

fprintf('NOTA:\n');
fprintf(['  El angulo final de yaw no tiene que regresar a cero.\n' ...
         '  El controlador actual regula velocidad angular.\n' ...
         '  Lo importante es que r vuelva aproximadamente a cero.\n\n']);

fprintf('============================================================\n');
fprintf(' PRUEBA APROBADA\n');
fprintf(' EL KIWO E88 REAL V1 DETIENE LA PERTURBACION DE YAW\n');
fprintf('============================================================\n\n');

%% ================================================================
% REUTILIZAR GRAFICA DE YAW
% ================================================================

if exist( ...
        'graficar_rechazo_perturbacion_yaw', ...
        'file' ...
    ) == 2

    graficar_rechazo_perturbacion_yaw( ...
        resultadosYaw ...
    );

else

    fprintf( ...
        ['No se encontro graficar_rechazo_perturbacion_yaw.m.\n' ...
         'La simulacion real fue ejecutada correctamente.\n\n'] ...
    );

end