%% TEST_INTEGRACION_TEMPORAL
% Verifica ode45 utilizando soluciones analíticas conocidas.

clearvars;
clc;

fprintf("================================================\n");
fprintf("       PRUEBAS DE INTEGRACIÓN TEMPORAL\n");
fprintf("================================================\n\n");

%% Preparación del caso base

modelo = definicion_modelo();

P = parametros_fisicos();
R = reglas_competencia();
Dproyecto = requisitos_proyecto(R);
C = parametros_diseno();

[P, C, casoBase] = ...
    caso_base_teorico(P, C, R);

G = configuracion_motores_x( ...
    R, ...
    Dproyecto, ...
    C.geometria.distanciaCentroMotor, ...
    C.geometria.zMotor_B ...
);

P = aplicar_configuracion_motores(P, G);

masa = P.cuerpo.masa;
g = P.entorno.g;
numeroMotores = P.motores.numero;

toleranciaEstado = 1e-6;

x0 = zeros(modelo.numeroEstados, 1);

E0 = perturbacion_nula();

perturbacionCeroFcn = @(t, x) E0;


%% PRUEBA 1
% Hover ideal durante cinco segundos.
%
% El vector completo debe permanecer en cero.

Uhover = crear_entrada_actuadores(P);

empujeHoverMotor = ...
    masa * g / numeroMotores;

Uhover.empujeMotores_N = ...
    empujeHoverMotor * ones(numeroMotores, 1);

entradaHoverFcn = @(t, x) Uhover;

tiempos = linspace(0, 5, 501);

resultado = simular_dron_12_estados( ...
    tiempos, ...
    x0, ...
    entradaHoverFcn, ...
    perturbacionCeroFcn, ...
    P, ...
    modelo ...
);

assert( ...
    norm(resultado.estadoFinal) < toleranciaEstado, ...
    "Prueba 1 falló: el dron no permaneció en hover." ...
);

assert( ...
    max(abs(resultado.x), [], "all") < toleranciaEstado, ...
    "Prueba 1 falló: aparecieron movimientos durante el hover." ...
);

fprintf("Prueba 1 aprobada: hover durante 5 segundos.\n");


%% PRUEBA 2
% Caída libre.
%
% Para orientación nula:
%
% w(t)  = g*t
% zD(t) = 0.5*g*t^2

Uapagado = crear_entrada_actuadores(P);

entradaApagadaFcn = @(t, x) Uapagado;

tiempoFinal = 1.0;

tiempos = linspace(0, tiempoFinal, 101);

resultado = simular_dron_12_estados( ...
    tiempos, ...
    x0, ...
    entradaApagadaFcn, ...
    perturbacionCeroFcn, ...
    P, ...
    modelo ...
);

wEsperada = g * tiempoFinal;

zDEsperada = ...
    0.5 * g * tiempoFinal^2;

assert( ...
    abs( ...
        resultado.estadoFinal(modelo.idx.w) - ...
        wEsperada ...
    ) < toleranciaEstado, ...
    "Prueba 2 falló: velocidad vertical incorrecta." ...
);

assert( ...
    abs( ...
        resultado.estadoFinal(modelo.idx.zD) - ...
        zDEsperada ...
    ) < toleranciaEstado, ...
    "Prueba 2 falló: posición vertical incorrecta." ...
);

fprintf("Prueba 2 aprobada: caída libre durante 1 segundo.\n");


%% PRUEBA 3
% Fuerza constante de 2 N en +X_B durante hover.
%
% a_x  = F_x / m
% u(t) = a_x*t
% x(t) = 0.5*a_x*t^2

fuerzaX_N = 2.0;

Ehorizontal = perturbacion_nula();

Ehorizontal.fuerzaExterna_B_N = [
    fuerzaX_N
    0
    0
];

perturbacionHorizontalFcn = @(t, x) Ehorizontal;

tiempoFinal = 1.0;

tiempos = linspace(0, tiempoFinal, 101);

resultado = simular_dron_12_estados( ...
    tiempos, ...
    x0, ...
    entradaHoverFcn, ...
    perturbacionHorizontalFcn, ...
    P, ...
    modelo ...
);

aceleracionX = fuerzaX_N / masa;

uEsperada = aceleracionX * tiempoFinal;

xEsperada = ...
    0.5 * aceleracionX * tiempoFinal^2;

assert( ...
    abs( ...
        resultado.estadoFinal(modelo.idx.u) - ...
        uEsperada ...
    ) < toleranciaEstado, ...
    "Prueba 3 falló: velocidad longitudinal incorrecta." ...
);

assert( ...
    abs( ...
        resultado.estadoFinal(modelo.idx.xN) - ...
        xEsperada ...
    ) < toleranciaEstado, ...
    "Prueba 3 falló: desplazamiento longitudinal incorrecto." ...
);

assert( ...
    abs(resultado.estadoFinal(modelo.idx.zD)) < ...
        toleranciaEstado, ...
    "Prueba 3 falló: el hover vertical no se conservó." ...
);

fprintf("Prueba 3 aprobada: fuerza horizontal constante.\n");


%% PRUEBA 4
% Momento constante alrededor de X_B.
%
% p(t)   = alpha*t
% phi(t) = 0.5*alpha*t^2
%
% alpha = Mx/Ixx

momentoX_Nm = 0.05;

Eangular = perturbacion_nula();

Eangular.momentoExterno_B_Nm = [
    momentoX_Nm
    0
    0
];

perturbacionAngularFcn = @(t, x) Eangular;

tiempoFinal = 0.5;

tiempos = linspace(0, tiempoFinal, 101);

resultado = simular_dron_12_estados( ...
    tiempos, ...
    x0, ...
    entradaHoverFcn, ...
    perturbacionAngularFcn, ...
    P, ...
    modelo ...
);

Ixx = P.cuerpo.inercia_B(1, 1);

aceleracionAngular = ...
    momentoX_Nm / Ixx;

pEsperada = ...
    aceleracionAngular * tiempoFinal;

phiEsperado = ...
    0.5 * aceleracionAngular * tiempoFinal^2;

assert( ...
    abs( ...
        resultado.estadoFinal(modelo.idx.p) - ...
        pEsperada ...
    ) < toleranciaEstado, ...
    "Prueba 4 falló: velocidad angular de roll incorrecta." ...
);

assert( ...
    abs( ...
        resultado.estadoFinal(modelo.idx.phi) - ...
        phiEsperado ...
    ) < toleranciaEstado, ...
    "Prueba 4 falló: ángulo de roll incorrecto." ...
);

fprintf("Prueba 4 aprobada: momento externo constante.\n");


%% RESULTADOS NUMÉRICOS DE REFERENCIA

fprintf("\nValores analíticos verificados:\n");

fprintf("  Caída libre a 1 s:\n");
fprintf("    w  = %.6f m/s\n", wEsperada);
fprintf("    zD = %.6f m\n", zDEsperada);

fprintf("  Fuerza horizontal de %.2f N durante 1 s:\n", ...
    fuerzaX_N);

fprintf("    u  = %.6f m/s\n", uEsperada);
fprintf("    xN = %.6f m\n", xEsperada);

fprintf("  Momento de %.3f N*m durante %.2f s:\n", ...
    momentoX_Nm, tiempoFinal);

fprintf("    p   = %.6f rad/s\n", pEsperada);
fprintf("    phi = %.6f rad (%.3f grados)\n", ...
    phiEsperado, rad2deg(phiEsperado));


%% RESULTADO FINAL

fprintf("\n================================================\n");
fprintf(" TODAS LAS PRUEBAS DE INTEGRACIÓN APROBARON\n");
fprintf("================================================\n");