%% TEST_MODELO_NO_LINEAL_12_ESTADOS
% Verifica la integración correcta de cinemática, traslación
% y rotación dentro del modelo completo de 12 estados.

clearvars;
clc;

fprintf("====================================================\n");
fprintf("      PRUEBAS DEL MODELO NO LINEAL DE 12 ESTADOS\n");
fprintf("====================================================\n\n");

%% Preparación del caso teórico

modelo = definicion_modelo();

P = parametros_fisicos();
R = reglas_competencia();
Dproyecto = requisitos_proyecto(R);
C = parametros_diseno();

[P, C, casoBase] = ...
    caso_base_teorico(P, C, R);

G = configuracion_motores_x( ...
    R, ...
    Dproyecto, ...
    C.geometria.distanciaCentroMotor, ...
    C.geometria.zMotor_B ...
);

P = aplicar_configuracion_motores(P, G);

tolerancia = 1e-10;

masa = P.cuerpo.masa;
g = P.entorno.g;

t = 0;


%% PRUEBA 1
% Hover ideal con todos los estados iguales a cero.
%
% Toda la derivada del vector de estados debe ser cero.

x = zeros(modelo.numeroEstados, 1);

U = crear_entrada_actuadores(P);
E = perturbacion_nula();

empujeHoverPorMotor = ...
    masa * g / P.motores.numero;

U.empujeMotores_N = ...
    empujeHoverPorMotor * ones(P.motores.numero, 1);

[dx, S] = modelo_no_lineal_12_estados( ...
    t, ...
    x, ...
    U, ...
    E, ...
    P, ...
    modelo ...
);

assert( ...
    norm(dx) < tolerancia, ...
    "Prueba 1 falló: el estado no permanece constante en hover." ...
);

assert( ...
    norm(S.dinamicaTraslacional.fuerzaTotal_B_N) < tolerancia, ...
    "Prueba 1 falló: la fuerza total de hover no es cero." ...
);

assert( ...
    norm(S.dinamicaRotacional.momentoTotal_B_Nm) < tolerancia, ...
    "Prueba 1 falló: el momento total de hover no es cero." ...
);

fprintf("Prueba 1 aprobada: hover ideal.\n");


%% PRUEBA 2
% Caída libre con orientación nivelada.
%
% Debe producirse:
%
% w_dot = +g

x = zeros(modelo.numeroEstados, 1);

U = crear_entrada_actuadores(P);
E = perturbacion_nula();

dx = modelo_no_lineal_12_estados( ...
    t, ...
    x, ...
    U, ...
    E, ...
    P, ...
    modelo ...
);

assert( ...
    abs(dx(modelo.idx.w) - g) < tolerancia, ...
    "Prueba 2 falló: la aceleración de caída libre es incorrecta." ...
);

indicesRestantes = setdiff( ...
    1:modelo.numeroEstados, ...
    modelo.idx.w ...
);

assert( ...
    norm(dx(indicesRestantes)) < tolerancia, ...
    "Prueba 2 falló: aparecieron derivadas no esperadas." ...
);

fprintf("Prueba 2 aprobada: caída libre.\n");


%% PRUEBA 3
% Fuerza horizontal externa durante hover.
%
% Fx = 2 N
%
% u_dot = Fx / m

x = zeros(modelo.numeroEstados, 1);

U = crear_entrada_actuadores(P);
E = perturbacion_nula();

U.empujeMotores_N = ...
    empujeHoverPorMotor * ones(P.motores.numero, 1);

fuerzaPrueba_N = 2;

E.fuerzaExterna_B_N = [
    fuerzaPrueba_N
    0
    0
];

dx = modelo_no_lineal_12_estados( ...
    t, ...
    x, ...
    U, ...
    E, ...
    P, ...
    modelo ...
);

aceleracionEsperada = ...
    fuerzaPrueba_N / masa;

assert( ...
    abs(dx(modelo.idx.u) - aceleracionEsperada) < tolerancia, ...
    "Prueba 3 falló: la aceleración longitudinal es incorrecta." ...
);

assert( ...
    abs(dx(modelo.idx.v)) < tolerancia, ...
    "Prueba 3 falló: apareció aceleración lateral no esperada." ...
);

assert( ...
    abs(dx(modelo.idx.w)) < tolerancia, ...
    "Prueba 3 falló: el hover vertical no se conservó." ...
);

fprintf("Prueba 3 aprobada: fuerza horizontal externa.\n");


%% PRUEBA 4
% Momento externo alrededor del eje X_B durante hover.
%
% p_dot = Mx / Ixx

x = zeros(modelo.numeroEstados, 1);

U = crear_entrada_actuadores(P);
E = perturbacion_nula();

U.empujeMotores_N = ...
    empujeHoverPorMotor * ones(P.motores.numero, 1);

momentoPrueba_Nm = 0.05;

E.momentoExterno_B_Nm = [
    momentoPrueba_Nm
    0
    0
];

dx = modelo_no_lineal_12_estados( ...
    t, ...
    x, ...
    U, ...
    E, ...
    P, ...
    modelo ...
);

Ixx = P.cuerpo.inercia_B(1, 1);

aceleracionAngularEsperada = ...
    momentoPrueba_Nm / Ixx;

assert( ...
    abs( ...
        dx(modelo.idx.p) - ...
        aceleracionAngularEsperada ...
    ) < tolerancia, ...
    "Prueba 4 falló: la aceleración angular de roll es incorrecta." ...
);

assert( ...
    abs(dx(modelo.idx.q)) < tolerancia, ...
    "Prueba 4 falló: apareció aceleración de pitch no esperada." ...
);

assert( ...
    abs(dx(modelo.idx.r)) < tolerancia, ...
    "Prueba 4 falló: apareció aceleración de yaw no esperada." ...
);

fprintf("Prueba 4 aprobada: momento externo de roll.\n");


%% PRUEBA 5
% Verifica que el modelo completo coincida exactamente con sus
% tres módulos internos para un estado no trivial.

x = zeros(modelo.numeroEstados, 1);

x(modelo.idx.u) = 1.20;
x(modelo.idx.v) = -0.30;
x(modelo.idx.w) = 0.15;

x(modelo.idx.phi) = deg2rad(12);
x(modelo.idx.theta) = deg2rad(-8);
x(modelo.idx.psi) = deg2rad(25);

x(modelo.idx.p) = 0.40;
x(modelo.idx.q) = -0.20;
x(modelo.idx.r) = 0.10;

U = crear_entrada_actuadores(P);
E = perturbacion_nula();

U.empujeMotores_N = [
    2.40
    2.55
    2.35
    2.50
];

U.torqueReaccionMotores_Nm = [
    0.010
    0.011
    0.009
    0.010
];

E.fuerzaExterna_B_N = [
     0.30
    -0.10
     0.05
];

E.momentoExterno_B_Nm = [
     0.004
    -0.002
     0.001
];

[dx, S] = modelo_no_lineal_12_estados( ...
    1.5, ...
    x, ...
    U, ...
    E, ...
    P, ...
    modelo ...
);

K = cinematica_6dof(x, modelo);

DT = dinamica_traslacional( ...
    x, ...
    U.empujeMotores_N, ...
    E.fuerzaExterna_B_N, ...
    P, ...
    modelo ...
);

DR = dinamica_rotacional( ...
    x, ...
    U.empujeMotores_N, ...
    U.torqueReaccionMotores_Nm, ...
    E.momentoExterno_B_Nm, ...
    P, ...
    modelo ...
);

assert( ...
    norm( ...
        dx([
            modelo.idx.xN
            modelo.idx.yE
            modelo.idx.zD
        ]) - K.posicionDot_N ...
    ) < tolerancia, ...
    "Prueba 5 falló: error en las derivadas de posición." ...
);

assert( ...
    norm( ...
        dx([
            modelo.idx.u
            modelo.idx.v
            modelo.idx.w
        ]) - DT.velocidadDot_B ...
    ) < tolerancia, ...
    "Prueba 5 falló: error en las derivadas de velocidad." ...
);

assert( ...
    norm( ...
        dx([
            modelo.idx.phi
            modelo.idx.theta
            modelo.idx.psi
        ]) - K.eulerDot ...
    ) < tolerancia, ...
    "Prueba 5 falló: error en las derivadas de Euler." ...
);

assert( ...
    norm( ...
        dx([
            modelo.idx.p
            modelo.idx.q
            modelo.idx.r
        ]) - DR.velocidadAngularDot_B ...
    ) < tolerancia, ...
    "Prueba 5 falló: error en las aceleraciones angulares." ...
);

assert( ...
    all(isfinite(dx)), ...
    "Prueba 5 falló: la derivada contiene valores no finitos." ...
);

assert( ...
    norm(S.derivadaEstado - dx) < tolerancia, ...
    "Prueba 5 falló: el diagnóstico no coincide con dx." ...
);

fprintf("Prueba 5 aprobada: consistencia del modelo completo.\n");


%% RESULTADO FINAL

fprintf("\n====================================================\n");
fprintf(" TODAS LAS PRUEBAS DEL MODELO DE 12 ESTADOS APROBARON\n");
fprintf("====================================================\n");